(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/Button/index.svelte":
/*!********************************************!*\
  !*** ./src/components/Button/index.svelte ***!
  \********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _root_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./root.svelte */ "./src/components/Button/root.svelte");
/* src/components/Button/index.svelte generated by Svelte v3.24.1 */



const file = "src/components/Button/index.svelte";

// (8:0) <Root  {url}  {alt}  on:click >
function create_default_slot(ctx) {
	let current;
	const default_slot_template = /*$$slots*/ ctx[2].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	const block = {
		c: function create() {
			if (default_slot) default_slot.c();
		},
		l: function claim(nodes) {
			if (default_slot) default_slot.l(nodes);
		},
		m: function mount(target, anchor) {
			if (default_slot) {
				default_slot.m(target, anchor);
			}

			current = true;
		},
		p: function update(ctx, dirty) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (default_slot) default_slot.d(detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(8:0) <Root  {url}  {alt}  on:click >",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let root;
	let current;

	root = new _root_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({
			props: {
				url: /*url*/ ctx[0],
				alt: /*alt*/ ctx[1],
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	root.$on("click", /*click_handler*/ ctx[3]);

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(root.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(root.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(root, target, anchor);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			const root_changes = {};
			if (dirty & /*url*/ 1) root_changes.url = /*url*/ ctx[0];
			if (dirty & /*alt*/ 2) root_changes.alt = /*alt*/ ctx[1];

			if (dirty & /*$$scope*/ 16) {
				root_changes.$$scope = { dirty, ctx };
			}

			root.$set(root_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(root.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(root.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(root, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { url = null } = $$props;
	let { alt = false } = $$props;
	const writable_props = ["url", "alt"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Button> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Button", $$slots, ['default']);

	function click_handler(event) {
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bubble"])($$self, event);
	}

	$$self.$$set = $$props => {
		if ("url" in $$props) $$invalidate(0, url = $$props.url);
		if ("alt" in $$props) $$invalidate(1, alt = $$props.alt);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	$$self.$capture_state = () => ({ Root: _root_svelte__WEBPACK_IMPORTED_MODULE_1__["default"], url, alt });

	$$self.$inject_state = $$props => {
		if ("url" in $$props) $$invalidate(0, url = $$props.url);
		if ("alt" in $$props) $$invalidate(1, alt = $$props.alt);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [url, alt, $$slots, click_handler, $$scope];
}

class Button extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { url: 0, alt: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Button",
			options,
			id: create_fragment.name
		});
	}

	get url() {
		throw new Error("<Button>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set url(value) {
		throw new Error("<Button>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get alt() {
		throw new Error("<Button>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set alt(value) {
		throw new Error("<Button>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Button);

/***/ }),

/***/ "./src/components/Button/root.svelte":
/*!*******************************************!*\
  !*** ./src/components/Button/root.svelte ***!
  \*******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Button/root.svelte generated by Svelte v3.24.1 */


const file = "src/components/Button/root.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1viip7k-style";
	style.textContent = ".root.svelte-1viip7k{position:relative;display:flex;justify-content:center;align-items:center;width:100%;max-width:320px;height:60px;padding:0 36px;font-size:18px;line-height:1.2;text-decoration:none;background-color:var(--alternate-color);border-radius:var(--border-radius-rounded);border:none;outline:none;color:var(--silver-color);cursor:pointer;transition:background-color 0.2s ease-out}.root.svelte-1viip7k::before{content:'';position:absolute;top:0;right:0;bottom:0;left:0;opacity:0;border-left:2px solid var(--alternate-color-interactive);border-right:2px solid var(--alternate-color-interactive);border-radius:var(--border-radius-rounded)}.root.svelte-1viip7k::after{content:'';position:absolute;top:2px;right:2px;bottom:2px;left:2px;opacity:0;box-shadow:0 0 0 2px var(--silver-color);border-radius:var(--border-radius-rounded);transition:opacity 0.2s ease-out}.alt.svelte-1viip7k{background-color:transparent;border:2px solid var(--silver-color)}.alt.svelte-1viip7k::before{border-color:var(--silver-color)}.alt.svelte-1viip7k::after{content:none}.root.svelte-1viip7k:hover{background-color:var(--alternate-color-interactive)}.root.svelte-1viip7k:hover::before{animation:svelte-1viip7k-pulse 0.8s ease-out}.alt.svelte-1viip7k:hover{background-color:var(--alternate-color-faded)}.root.svelte-1viip7k:focus{background-color:var(--alternate-color-interactive)}.root.svelte-1viip7k:focus:after{opacity:1}@keyframes svelte-1viip7k-pulse{0%{opacity:0}50%{opacity:1}100%{opacity:0;transform:scale(1.2)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicm9vdC5zdmVsdGUiLCJzb3VyY2VzIjpbInJvb3Quc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG5cdGV4cG9ydCBsZXQgdXJsID0gbnVsbDtcblx0ZXhwb3J0IGxldCBhbHQgPSBmYWxzZTtcbjwvc2NyaXB0PlxuXG57I2lmIHVybH1cbjxhXG5cdGhyZWY9XCJ7dXJsfVwiXG5cdGNsYXNzPVwicm9vdFwiXG5cdGNsYXNzOmFsdD1cInthbHR9XCJcbj5cblx0PHNsb3Q+PC9zbG90PlxuPC9hPlxuezplbHNlfVxuPGJ1dHRvblxuXHR0eXBlPVwiYnV0dG9uXCJcblx0Y2xhc3M9XCJyb290XCJcblx0Y2xhc3M6YWx0PXthbHR9XG5cdG9uOmNsaWNrXG4+XG5cdDxzbG90Pjwvc2xvdD5cbjwvYnV0dG9uPlxuey9pZn1cblxuPHN0eWxlPlxuXHQucm9vdCB7XG5cdFx0cG9zaXRpb246IHJlbGF0aXZlO1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdG1heC13aWR0aDogMzIwcHg7XG5cdFx0aGVpZ2h0OiA2MHB4O1xuXHRcdHBhZGRpbmc6IDAgMzZweDtcblxuXHRcdGZvbnQtc2l6ZTogMThweDtcblx0XHRsaW5lLWhlaWdodDogMS4yO1xuXHRcdHRleHQtZGVjb3JhdGlvbjogbm9uZTtcblxuXHRcdGJhY2tncm91bmQtY29sb3I6IHZhcigtLWFsdGVybmF0ZS1jb2xvcik7XG5cdFx0Ym9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cy1yb3VuZGVkKTtcblx0XHRib3JkZXI6IG5vbmU7XG5cdFx0b3V0bGluZTogbm9uZTtcblx0XHRjb2xvcjogdmFyKC0tc2lsdmVyLWNvbG9yKTtcblxuXHRcdGN1cnNvcjogcG9pbnRlcjtcblxuXHRcdHRyYW5zaXRpb246IGJhY2tncm91bmQtY29sb3IgMC4ycyBlYXNlLW91dDtcblx0fVxuXG5cdC5yb290OjpiZWZvcmUge1xuXHRcdGNvbnRlbnQ6ICcnO1xuXG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRyaWdodDogMDtcblx0XHRib3R0b206IDA7XG5cdFx0bGVmdDogMDtcblxuXHRcdG9wYWNpdHk6IDA7XG5cdFx0Ym9yZGVyLWxlZnQ6IDJweCBzb2xpZCB2YXIoLS1hbHRlcm5hdGUtY29sb3ItaW50ZXJhY3RpdmUpO1xuXHRcdGJvcmRlci1yaWdodDogMnB4IHNvbGlkIHZhcigtLWFsdGVybmF0ZS1jb2xvci1pbnRlcmFjdGl2ZSk7XG5cdFx0Ym9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cy1yb3VuZGVkKTtcblx0fVxuXG5cdC5yb290OjphZnRlciB7XG5cdFx0Y29udGVudDogJyc7XG5cblx0XHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdFx0dG9wOiAycHg7XG5cdFx0cmlnaHQ6IDJweDtcblx0XHRib3R0b206IDJweDtcblx0XHRsZWZ0OiAycHg7XG5cblx0XHRvcGFjaXR5OiAwO1xuXHRcdGJveC1zaGFkb3c6IDAgMCAwIDJweCB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHRcdGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMtcm91bmRlZCk7XG5cblx0XHR0cmFuc2l0aW9uOiBvcGFjaXR5IDAuMnMgZWFzZS1vdXQ7XG5cdH1cblxuXHQuYWx0IHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB0cmFuc3BhcmVudDtcblx0XHRib3JkZXI6IDJweCBzb2xpZCB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LmFsdDo6YmVmb3JlIHtcblx0XHRib3JkZXItY29sb3I6IHZhcigtLXNpbHZlci1jb2xvcik7XG5cdH1cblxuXHQuYWx0OjphZnRlciB7XG5cdFx0Y29udGVudDogbm9uZTtcblx0fVxuXG5cdC5yb290OmhvdmVyIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItaW50ZXJhY3RpdmUpO1xuXHR9XG5cblx0LnJvb3Q6aG92ZXI6OmJlZm9yZSB7XG5cdFx0YW5pbWF0aW9uOiBwdWxzZSAwLjhzIGVhc2Utb3V0O1xuXHR9XG5cblx0LmFsdDpob3ZlciB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yLWZhZGVkKTtcblx0fVxuXG5cdC5yb290OmZvY3VzIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItaW50ZXJhY3RpdmUpO1xuXHR9XG5cblx0LnJvb3Q6Zm9jdXM6YWZ0ZXIge1xuXHRcdG9wYWNpdHk6IDE7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIHB1bHNlIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDUwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblxuXHRcdFx0dHJhbnNmb3JtOiBzY2FsZSgxLjIpO1xuXHRcdH1cblx0fVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF5QkMsS0FBSyxlQUFDLENBQUMsQUFDTixRQUFRLENBQUUsUUFBUSxDQUVsQixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBQ25CLEtBQUssQ0FBRSxJQUFJLENBQ1gsU0FBUyxDQUFFLEtBQUssQ0FDaEIsTUFBTSxDQUFFLElBQUksQ0FDWixPQUFPLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FFZixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGVBQWUsQ0FBRSxJQUFJLENBRXJCLGdCQUFnQixDQUFFLElBQUksaUJBQWlCLENBQUMsQ0FDeEMsYUFBYSxDQUFFLElBQUksdUJBQXVCLENBQUMsQ0FDM0MsTUFBTSxDQUFFLElBQUksQ0FDWixPQUFPLENBQUUsSUFBSSxDQUNiLEtBQUssQ0FBRSxJQUFJLGNBQWMsQ0FBQyxDQUUxQixNQUFNLENBQUUsT0FBTyxDQUVmLFVBQVUsQ0FBRSxnQkFBZ0IsQ0FBQyxJQUFJLENBQUMsUUFBUSxBQUMzQyxDQUFDLEFBRUQsb0JBQUssUUFBUSxBQUFDLENBQUMsQUFDZCxPQUFPLENBQUUsRUFBRSxDQUVYLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEdBQUcsQ0FBRSxDQUFDLENBQ04sS0FBSyxDQUFFLENBQUMsQ0FDUixNQUFNLENBQUUsQ0FBQyxDQUNULElBQUksQ0FBRSxDQUFDLENBRVAsT0FBTyxDQUFFLENBQUMsQ0FDVixXQUFXLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxJQUFJLDZCQUE2QixDQUFDLENBQ3pELFlBQVksQ0FBRSxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksNkJBQTZCLENBQUMsQ0FDMUQsYUFBYSxDQUFFLElBQUksdUJBQXVCLENBQUMsQUFDNUMsQ0FBQyxBQUVELG9CQUFLLE9BQU8sQUFBQyxDQUFDLEFBQ2IsT0FBTyxDQUFFLEVBQUUsQ0FFWCxRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsR0FBRyxDQUNSLEtBQUssQ0FBRSxHQUFHLENBQ1YsTUFBTSxDQUFFLEdBQUcsQ0FDWCxJQUFJLENBQUUsR0FBRyxDQUVULE9BQU8sQ0FBRSxDQUFDLENBQ1YsVUFBVSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxJQUFJLGNBQWMsQ0FBQyxDQUN6QyxhQUFhLENBQUUsSUFBSSx1QkFBdUIsQ0FBQyxDQUUzQyxVQUFVLENBQUUsT0FBTyxDQUFDLElBQUksQ0FBQyxRQUFRLEFBQ2xDLENBQUMsQUFFRCxJQUFJLGVBQUMsQ0FBQyxBQUNMLGdCQUFnQixDQUFFLFdBQVcsQ0FDN0IsTUFBTSxDQUFFLEdBQUcsQ0FBQyxLQUFLLENBQUMsSUFBSSxjQUFjLENBQUMsQUFDdEMsQ0FBQyxBQUVELG1CQUFJLFFBQVEsQUFBQyxDQUFDLEFBQ2IsWUFBWSxDQUFFLElBQUksY0FBYyxDQUFDLEFBQ2xDLENBQUMsQUFFRCxtQkFBSSxPQUFPLEFBQUMsQ0FBQyxBQUNaLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUVELG9CQUFLLE1BQU0sQUFBQyxDQUFDLEFBQ1osZ0JBQWdCLENBQUUsSUFBSSw2QkFBNkIsQ0FBQyxBQUNyRCxDQUFDLEFBRUQsb0JBQUssTUFBTSxRQUFRLEFBQUMsQ0FBQyxBQUNwQixTQUFTLENBQUUsb0JBQUssQ0FBQyxJQUFJLENBQUMsUUFBUSxBQUMvQixDQUFDLEFBRUQsbUJBQUksTUFBTSxBQUFDLENBQUMsQUFDWCxnQkFBZ0IsQ0FBRSxJQUFJLHVCQUF1QixDQUFDLEFBQy9DLENBQUMsQUFFRCxvQkFBSyxNQUFNLEFBQUMsQ0FBQyxBQUNaLGdCQUFnQixDQUFFLElBQUksNkJBQTZCLENBQUMsQUFDckQsQ0FBQyxBQUVELG9CQUFLLE1BQU0sTUFBTSxBQUFDLENBQUMsQUFDbEIsT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsV0FBVyxvQkFBTSxDQUFDLEFBQ2pCLEVBQUUsQUFBQyxDQUFDLEFBQ0gsT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsR0FBRyxBQUFDLENBQUMsQUFDSixPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxJQUFJLEFBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxDQUFDLENBRVYsU0FBUyxDQUFFLE1BQU0sR0FBRyxDQUFDLEFBQ3RCLENBQUMsQUFDRixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (14:0) {:else}
function create_else_block(ctx) {
	let button;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*$$slots*/ ctx[3].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[2], null);

	const block = {
		c: function create() {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BUTTON", { type: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			if (default_slot) default_slot.l(button_nodes);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "type", "button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "root svelte-1viip7k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button, "alt", /*alt*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 14, 0, 159);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, button, anchor);

			if (default_slot) {
				default_slot.m(button, null);
			}

			current = true;

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button, "click", /*click_handler*/ ctx[4], false, false, false);
				mounted = true;
			}
		},
		p: function update(ctx, dirty) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[2], dirty, null, null);
				}
			}

			if (dirty & /*alt*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button, "alt", /*alt*/ ctx[1]);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(button);
			if (default_slot) default_slot.d(detaching);
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(14:0) {:else}",
		ctx
	});

	return block;
}

// (6:0) {#if url}
function create_if_block(ctx) {
	let a;
	let current;
	const default_slot_template = /*$$slots*/ ctx[3].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[2], null);

	const block = {
		c: function create() {
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "A", { href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			if (default_slot) default_slot.l(a_nodes);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", /*url*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "root svelte-1viip7k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(a, "alt", /*alt*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 6, 0, 79);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, a, anchor);

			if (default_slot) {
				default_slot.m(a, null);
			}

			current = true;
		},
		p: function update(ctx, dirty) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[2], dirty, null, null);
				}
			}

			if (!current || dirty & /*url*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", /*url*/ ctx[0]);
			}

			if (dirty & /*alt*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(a, "alt", /*alt*/ ctx[1]);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(a);
			if (default_slot) default_slot.d(detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(6:0) {#if url}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let current_block_type_index;
	let if_block;
	let if_block_anchor;
	let current;
	const if_block_creators = [create_if_block, create_else_block];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*url*/ ctx[0]) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	const block = {
		c: function create() {
			if_block.c();
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		l: function claim(nodes) {
			if_block.l(nodes);
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		m: function mount(target, anchor) {
			if_blocks[current_block_type_index].m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, if_block_anchor, anchor);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if_blocks[current_block_type_index].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block = if_blocks[current_block_type_index];

				if (!if_block) {
					if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
				if_block.m(if_block_anchor.parentNode, if_block_anchor);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if_blocks[current_block_type_index].d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(if_block_anchor);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { url = null } = $$props;
	let { alt = false } = $$props;
	const writable_props = ["url", "alt"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Root> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Root", $$slots, ['default']);

	function click_handler(event) {
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bubble"])($$self, event);
	}

	$$self.$$set = $$props => {
		if ("url" in $$props) $$invalidate(0, url = $$props.url);
		if ("alt" in $$props) $$invalidate(1, alt = $$props.alt);
		if ("$$scope" in $$props) $$invalidate(2, $$scope = $$props.$$scope);
	};

	$$self.$capture_state = () => ({ url, alt });

	$$self.$inject_state = $$props => {
		if ("url" in $$props) $$invalidate(0, url = $$props.url);
		if ("alt" in $$props) $$invalidate(1, alt = $$props.alt);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [url, alt, $$scope, $$slots, click_handler];
}

class Root extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1viip7k-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { url: 0, alt: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Root",
			options,
			id: create_fragment.name
		});
	}

	get url() {
		throw new Error("<Root>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set url(value) {
		throw new Error("<Root>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get alt() {
		throw new Error("<Root>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set alt(value) {
		throw new Error("<Root>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Root);

/***/ }),

/***/ "./src/components/Icon/index.svelte":
/*!******************************************!*\
  !*** ./src/components/Icon/index.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte_inline_svg__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte-inline-svg */ "./node_modules/svelte-inline-svg/src/index.js");
/* src/components/Icon/index.svelte generated by Svelte v3.24.1 */



const file = "src/components/Icon/index.svelte";

function create_fragment(ctx) {
	let inlinesvg;
	let current;

	inlinesvg = new svelte_inline_svg__WEBPACK_IMPORTED_MODULE_1__["default"]({
			props: { src: /*src*/ ctx[0], width: /*w*/ ctx[1] },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(inlinesvg.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(inlinesvg.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(inlinesvg, target, anchor);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			const inlinesvg_changes = {};
			if (dirty & /*src*/ 1) inlinesvg_changes.src = /*src*/ ctx[0];
			if (dirty & /*w*/ 2) inlinesvg_changes.width = /*w*/ ctx[1];
			inlinesvg.$set(inlinesvg_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(inlinesvg.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(inlinesvg.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(inlinesvg, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { src = "" } = $$props;
	let { w = "auto" } = $$props;
	const writable_props = ["src", "w"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Icon> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Icon", $$slots, []);

	$$self.$$set = $$props => {
		if ("src" in $$props) $$invalidate(0, src = $$props.src);
		if ("w" in $$props) $$invalidate(1, w = $$props.w);
	};

	$$self.$capture_state = () => ({ InlineSVG: svelte_inline_svg__WEBPACK_IMPORTED_MODULE_1__["default"], src, w });

	$$self.$inject_state = $$props => {
		if ("src" in $$props) $$invalidate(0, src = $$props.src);
		if ("w" in $$props) $$invalidate(1, w = $$props.w);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [src, w];
}

class Icon extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { src: 0, w: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Icon",
			options,
			id: create_fragment.name
		});
	}

	get src() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set src(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get w() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set w(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Icon);

/***/ }),

/***/ "./src/components/index.js":
/*!*********************************!*\
  !*** ./src/components/index.js ***!
  \*********************************/
/*! exports provided: Button, Icon */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Button_index_svelte__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Button/index.svelte */ "./src/components/Button/index.svelte");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "Button", function() { return _Button_index_svelte__WEBPACK_IMPORTED_MODULE_0__["default"]; });

/* harmony import */ var _Icon_index_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./Icon/index.svelte */ "./src/components/Icon/index.svelte");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "Icon", function() { return _Icon_index_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]; });





/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../components */ "./src/components/index.js");
/* src/routes/index.svelte generated by Svelte v3.24.1 */






const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-163kunk-style";
	style.textContent = ".root.svelte-163kunk{display:flex;flex-direction:column;justify-content:space-between;align-items:center;max-width:420px;margin:0 auto;padding:30px 20px 50px}.logo__text.svelte-163kunk{font-size:30px;font-weight:200}.description__main.svelte-163kunk{margin-top:20px;font-size:18px}.description__extra.svelte-163kunk{display:block;margin-top:15px;font-size:14px;color:var(--silver-color-faded)}.highlight.svelte-163kunk{color:var(--highlight-color)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+V2VsY29tZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2NyaXB0PlxuXHRpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcblx0aW1wb3J0IHsgZmx5IH0gZnJvbSAnc3ZlbHRlL3RyYW5zaXRpb24nO1xuXHRpbXBvcnQgeyBlbGFzdGljT3V0LCBxdWludE91dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuXHRpbXBvcnQgeyBCdXR0b24sIEljb24gfSBmcm9tICcuLi9jb21wb25lbnRzJztcblxuXHRsZXQgbG9hZGVkID0gZmFsc2U7XG5cblx0b25Nb3VudCgoKSA9PiB7XG5cdFx0bG9hZGVkID0gdHJ1ZTtcblx0fSk7XG48L3NjcmlwdD5cblxueyNpZiBsb2FkZWR9XG5cdDxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHRcdDxoMVxuXHRcdFx0aW46Zmx5PXt7b3BhY2l0eTogMCwgeTogLTMwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMzAwfX1cblx0XHRcdG91dDpmbHk9e3tvcGFjaXR5OiAwLCB5OiAtMzAsIGVhc2luZzogcXVpbnRPdXR9fVxuXHRcdFx0Y2xhc3M9XCJsb2dvX190ZXh0XCJcblx0XHQ+XG5cdFx0XHRjb21hdGVcblx0XHQ8L2gxPlxuXG5cdFx0PGRpdj5cblx0XHRcdDxkaXZcblx0XHRcdFx0aW46Zmx5PXt7b3BhY2l0eTogMCwgeDogMjAwLCB5OiAtMjAwLCBlYXNpbmc6IHF1aW50T3V0LCBkdXJhdGlvbjogNjAwfX1cblx0XHRcdFx0b3V0OmZseT17e29wYWNpdHk6IDAsIHg6IC0yMDAsIHk6IDIwMCwgZWFzaW5nOiBxdWludE91dCwgZGVsYXk6IDIwMCwgZHVyYXRpb246IDYwMH19XG5cdFx0XHQ+XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2xvZ28uc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTAwXCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L2Rpdj5cblxuXHRcdFx0PHBcblx0XHRcdFx0Y2xhc3M9XCJkZXNjcmlwdGlvbl9fbWFpblwiXG5cdFx0XHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IHF1aW50T3V0LCBkZWxheTogMTAwfX1cblx0XHRcdFx0b3V0OmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IHF1aW50T3V0LCBkZWxheTogMTAwfX1cblx0XHRcdD5cblx0XHRcdFx0Q29tYXRlIGlzIGFuIGhvbmVzdCBhbGFybSBjbG9jayB0byA8c3BhbiBjbGFzcz1cImhpZ2hsaWdodFwiPmhlbHAgeW91IHNsZWVwLjwvc3Bhbj4gVGhlIGF2ZXJhZ2UgaHVtYW4gYmVpbmcgbmVlZHMgPHNwYW4gY2xhc3M9XCJoaWdobGlnaHRcIj44IGhvdXJzIG9mIHNsZWVwPC9zcGFuPiBwZXIgbmlnaHQuXG5cdFx0XHQ8L3A+XG5cblx0XHRcdDxzbWFsbFxuXHRcdFx0XHRjbGFzcz1cImRlc2NyaXB0aW9uX19leHRyYVwiXG5cdFx0XHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IHF1aW50T3V0LCBkZWxheTogMjAwfX1cblx0XHRcdFx0b3V0OmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IHF1aW50T3V0fX1cblx0XHRcdD5cblx0XHRcdFx0V2l0aCBjb21hdGUgeW91IGRvbid0IHNsZWVwIHRpbGwgN0FNLCB5b3Ugc2xlZXAgdGlsbCB5b3UndmUgaGFkIGVub3VnaCBzbGVlcCB0byBmdW5jdGlvbiBwcm9wZXJseSBldmVyeWRheS5cblx0XHRcdDwvc21hbGw+XG5cdFx0PC9kaXY+XG5cblx0XHQ8ZGl2XG5cdFx0XHRpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiA1MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDMwMH19XG5cdFx0XHRvdXQ6Zmx5PXt7b3BhY2l0eTogMCwgeTogNTAsIGVhc2luZzogcXVpbnRPdXR9fVxuXHRcdD5cblx0XHRcdDxCdXR0b24gdXJsPVwiL2FwcFwiPlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+UHV0IG1lIGluIGEgY29tYTwvc3Bhbj5cblxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9hcnJvdy5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxOFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9CdXR0b24+XG5cdFx0PC9kaXY+XG5cdDwvbWFpbj5cbnsvaWZ9XG5cbjxzdHlsZT5cblx0LnJvb3Qge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdG1heC13aWR0aDogNDIwcHg7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdFx0cGFkZGluZzogMzBweCAyMHB4IDUwcHg7XG5cdH1cblxuXHQubG9nb19fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAzMHB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdH1cblxuXHQuZGVzY3JpcHRpb25fX21haW4ge1xuXHRcdG1hcmdpbi10b3A6IDIwcHg7XG5cblx0XHRmb250LXNpemU6IDE4cHg7XG5cdH1cblxuXHQuZGVzY3JpcHRpb25fX2V4dHJhIHtcblx0XHRkaXNwbGF5OiBibG9jaztcblx0XHRtYXJnaW4tdG9wOiAxNXB4O1xuXG5cdFx0Zm9udC1zaXplOiAxNHB4O1xuXG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuaGlnaGxpZ2h0IHtcblx0XHRjb2xvcjogdmFyKC0taGlnaGxpZ2h0LWNvbG9yKTtcblx0fVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUEwRUMsS0FBSyxlQUFDLENBQUMsQUFDTixPQUFPLENBQUUsSUFBSSxDQUNiLGNBQWMsQ0FBRSxNQUFNLENBQ3RCLGVBQWUsQ0FBRSxhQUFhLENBQzlCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUNkLE9BQU8sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQUFDeEIsQ0FBQyxBQUVELFdBQVcsZUFBQyxDQUFDLEFBQ1osU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsR0FBRyxBQUNqQixDQUFDLEFBRUQsa0JBQWtCLGVBQUMsQ0FBQyxBQUNuQixVQUFVLENBQUUsSUFBSSxDQUVoQixTQUFTLENBQUUsSUFBSSxBQUNoQixDQUFDLEFBRUQsbUJBQW1CLGVBQUMsQ0FBQyxBQUNwQixPQUFPLENBQUUsS0FBSyxDQUNkLFVBQVUsQ0FBRSxJQUFJLENBRWhCLFNBQVMsQ0FBRSxJQUFJLENBRWYsS0FBSyxDQUFFLElBQUksb0JBQW9CLENBQUMsQUFDakMsQ0FBQyxBQUVELFVBQVUsZUFBQyxDQUFDLEFBQ1gsS0FBSyxDQUFFLElBQUksaUJBQWlCLENBQUMsQUFDOUIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (18:0) {#if loaded}
function create_if_block(ctx) {
	let main;
	let h1;
	let t0;
	let h1_intro;
	let h1_outro;
	let t1;
	let div1;
	let div0;
	let icon;
	let div0_intro;
	let div0_outro;
	let t2;
	let p;
	let t3;
	let span0;
	let t4;
	let t5;
	let span1;
	let t6;
	let t7;
	let p_intro;
	let p_outro;
	let t8;
	let small;
	let t9;
	let small_intro;
	let small_outro;
	let t10;
	let div2;
	let button;
	let div2_intro;
	let div2_outro;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_4__["Icon"]({
			props: { src: "/logo.svg", w: "100" },
			$$inline: true
		});

	button = new _components__WEBPACK_IMPORTED_MODULE_4__["Button"]({
			props: {
				url: "/app",
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("comate");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Comate is an honest alarm clock to ");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("help you sleep.");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(" The average human being needs ");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("8 hours of sleep");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(" per night.");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("With comate you don't sleep till 7AM, you sleep till you've had enough sleep to function properly everyday.");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "comate");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", {});
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, div0_nodes);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "Comate is an honest alarm clock to ");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, "help you sleep.");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, " The average human being needs ");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "8 hours of sleep");
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, " per night.");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SMALL", { class: true });
			var small_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small_nodes, "With comate you don't sleep till 7AM, you sleep till you've had enough sleep to function properly everyday.");
			small_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div2_nodes);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "logo__text svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 19, 2, 351);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 28, 3, 544);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "highlight svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 44, 39, 999);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "highlight svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 44, 116, 1076);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "description__main svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 39, 3, 795);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(small, "class", "description__extra svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small, file, 47, 3, 1147);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 27, 2, 535);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 56, 2, 1441);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "class", "root svelte-163kunk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 18, 1, 329);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, small);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(small, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div2, null);
			current = true;
		},
		i: function intro(local) {
			if (current) return;

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (h1_outro) h1_outro.end(1);

				if (!h1_intro) h1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(h1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
					opacity: 0,
					y: -30,
					easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
					duration: 1000,
					delay: 300
				});

				h1_intro.start();
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (div0_outro) div0_outro.end(1);

				if (!div0_intro) div0_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div0, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
					opacity: 0,
					x: 200,
					y: -200,
					easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
					duration: 600
				});

				div0_intro.start();
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (p_outro) p_outro.end(1);

				if (!p_intro) p_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(p, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
					opacity: 0,
					y: 30,
					easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
					delay: 100
				});

				p_intro.start();
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (small_outro) small_outro.end(1);

				if (!small_intro) small_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(small, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
					opacity: 0,
					y: 30,
					easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
					delay: 200
				});

				small_intro.start();
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (div2_outro) div2_outro.end(1);

				if (!div2_intro) div2_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div2, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
					opacity: 0,
					y: 50,
					easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
					duration: 1000,
					delay: 300
				});

				div2_intro.start();
			});

			current = true;
		},
		o: function outro(local) {
			if (h1_intro) h1_intro.invalidate();
			h1_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(h1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], { opacity: 0, y: -30, easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"] });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			if (div0_intro) div0_intro.invalidate();

			div0_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(div0, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
				opacity: 0,
				x: -200,
				y: 200,
				easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
				delay: 200,
				duration: 600
			});

			if (p_intro) p_intro.invalidate();

			p_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(p, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
				opacity: 0,
				y: 30,
				easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
				delay: 100
			});

			if (small_intro) small_intro.invalidate();
			small_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(small, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], { opacity: 0, y: 30, easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"] });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			if (div2_intro) div2_intro.invalidate();
			div2_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(div2, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], { opacity: 0, y: 50, easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"] });
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
			if (detaching && h1_outro) h1_outro.end();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon);
			if (detaching && div0_outro) div0_outro.end();
			if (detaching && p_outro) p_outro.end();
			if (detaching && small_outro) small_outro.end();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
			if (detaching && div2_outro) div2_outro.end();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(18:0) {#if loaded}",
		ctx
	});

	return block;
}

// (61:3) <Button url="/app">
function create_default_slot(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_4__["Icon"]({
			props: { src: "/arrow.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Put me in a coma");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Put me in a coma");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 61, 4, 1608);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 2) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(61:3) <Button url=\\\"/app\\\">",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t;
	let if_block_anchor;
	let current;
	let if_block = /*loaded*/ ctx[0] && create_if_block(ctx);

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block) if_block.c();
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-czi6z8\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			if (if_block) if_block.l(nodes);
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		h: function hydrate() {
			document.title = "Welcome";
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
			if (if_block) if_block.m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, if_block_anchor, anchor);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (/*loaded*/ ctx[0]) {
				if (if_block) {
					if (dirty & /*loaded*/ 1) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
			if (if_block) if_block.d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(if_block_anchor);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let loaded = false;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
		$$invalidate(0, loaded = true);
	});

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"],
		elasticOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
		quintOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["quintOut"],
		Button: _components__WEBPACK_IMPORTED_MODULE_4__["Button"],
		Icon: _components__WEBPACK_IMPORTED_MODULE_4__["Icon"],
		loaded
	});

	$$self.$inject_state = $$props => {
		if ("loaded" in $$props) $$invalidate(0, loaded = $$props.loaded);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [loaded];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-163kunk-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9CdXR0b24vaW5kZXguc3ZlbHRlIiwid2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL0J1dHRvbi9yb290LnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9JY29uL2luZGV4LnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9pbmRleC5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7O0FBQ2tDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztPQUV0QixHQUFHLEdBQUcsSUFBSTtPQUNWLEdBQUcsR0FBRyxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytGQ2FYLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0dBQUgsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1RkFWUCxHQUFHOzswRkFFRSxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3RkFGUixHQUFHOzs7OzJGQUVFLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2NBSlgsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztPQUpJLEdBQUcsR0FBRyxJQUFJO09BQ1YsR0FBRyxHQUFHLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDRG9COzs7Ozs7Ozs4Q0FNbkIsR0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7O3dEQUFELEdBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BSmIsR0FBRyxHQUFHLEVBQUU7T0FDUixDQUFDLEdBQUcsTUFBTTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNKdEI7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBMEQ7QUFDSjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0lwQjtBQUNPO0FBQ2E7QUFDUjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztLQVlsQyxPQUFPLEVBQUUsQ0FBQztLQUFFLENBQUMsR0FBRyxFQUFFO0tBQUUsTUFBTSxFQUFFLHdEQUFVO0tBQUUsUUFBUSxFQUFFLElBQUk7S0FBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7O0tBU2pFLE9BQU8sRUFBRSxDQUFDO0tBQUUsQ0FBQyxFQUFFLEdBQUc7S0FBRSxDQUFDLEdBQUcsR0FBRztLQUFFLE1BQU0sRUFBRSxzREFBUTtLQUFFLFFBQVEsRUFBRSxHQUFHOzs7Ozs7Ozs7O0tBWTVELE9BQU8sRUFBRSxDQUFDO0tBQUUsQ0FBQyxFQUFFLEVBQUU7S0FBRSxNQUFNLEVBQUUsc0RBQVE7S0FBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7OztLQVEvQyxPQUFPLEVBQUUsQ0FBQztLQUFFLENBQUMsRUFBRSxFQUFFO0tBQUUsTUFBTSxFQUFFLHNEQUFRO0tBQUUsS0FBSyxFQUFFLEdBQUc7Ozs7Ozs7Ozs7OztLQVFoRCxPQUFPLEVBQUUsQ0FBQztLQUFFLENBQUMsRUFBRSxFQUFFO0tBQUUsTUFBTSxFQUFFLHdEQUFVO0tBQUUsUUFBUSxFQUFFLElBQUk7S0FBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozt5SkFwQ2hFLE9BQU8sRUFBRSxDQUFDLEVBQUUsQ0FBQyxHQUFHLEVBQUUsRUFBRSxNQUFNLEVBQUUsc0RBQVE7Ozs7O0lBU25DLE9BQU8sRUFBRSxDQUFDO0lBQUUsQ0FBQyxHQUFHLEdBQUc7SUFBRSxDQUFDLEVBQUUsR0FBRztJQUFFLE1BQU0sRUFBRSxzREFBUTtJQUFFLEtBQUssRUFBRSxHQUFHO0lBQUUsUUFBUSxFQUFFLEdBQUc7Ozs7OztJQVl4RSxPQUFPLEVBQUUsQ0FBQztJQUFFLENBQUMsRUFBRSxFQUFFO0lBQUUsTUFBTSxFQUFFLHNEQUFRO0lBQUUsS0FBSyxFQUFFLEdBQUc7Ozs7K0pBUS9DLE9BQU8sRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLEVBQUUsRUFBRSxNQUFNLEVBQUUsc0RBQVE7Ozs2SkFRcEMsT0FBTyxFQUFFLENBQUMsRUFBRSxDQUFDLEVBQUUsRUFBRSxFQUFFLE1BQU0sRUFBRSxzREFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkJBekMzQyxHQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0JBQU4sR0FBTTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztLQVBOLE1BQU0sR0FBRyxLQUFLOztDQUVsQixzREFBTztrQkFDTixNQUFNLEdBQUcsSUFBSSIsImZpbGUiOiI2ZmZiODgzNTIzM2FiMWU1M2U3Ni9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG5cdGltcG9ydCBSb290IGZyb20gJy4vcm9vdC5zdmVsdGUnO1xuXG5cdGV4cG9ydCBsZXQgdXJsID0gbnVsbDtcblx0ZXhwb3J0IGxldCBhbHQgPSBmYWxzZTtcbjwvc2NyaXB0PlxuXG48Um9vdFxuXHR7dXJsfVxuXHR7YWx0fVxuXHRvbjpjbGlja1xuPlxuXHQ8c2xvdD48L3Nsb3Q+XG48L1Jvb3Q+XG4iLCI8c2NyaXB0PlxuXHRleHBvcnQgbGV0IHVybCA9IG51bGw7XG5cdGV4cG9ydCBsZXQgYWx0ID0gZmFsc2U7XG48L3NjcmlwdD5cblxueyNpZiB1cmx9XG48YVxuXHRocmVmPVwie3VybH1cIlxuXHRjbGFzcz1cInJvb3RcIlxuXHRjbGFzczphbHQ9XCJ7YWx0fVwiXG4+XG5cdDxzbG90Pjwvc2xvdD5cbjwvYT5cbns6ZWxzZX1cbjxidXR0b25cblx0dHlwZT1cImJ1dHRvblwiXG5cdGNsYXNzPVwicm9vdFwiXG5cdGNsYXNzOmFsdD17YWx0fVxuXHRvbjpjbGlja1xuPlxuXHQ8c2xvdD48L3Nsb3Q+XG48L2J1dHRvbj5cbnsvaWZ9XG5cbjxzdHlsZT5cblx0LnJvb3Qge1xuXHRcdHBvc2l0aW9uOiByZWxhdGl2ZTtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0XHRtYXgtd2lkdGg6IDMyMHB4O1xuXHRcdGhlaWdodDogNjBweDtcblx0XHRwYWRkaW5nOiAwIDM2cHg7XG5cblx0XHRmb250LXNpemU6IDE4cHg7XG5cdFx0bGluZS1oZWlnaHQ6IDEuMjtcblx0XHR0ZXh0LWRlY29yYXRpb246IG5vbmU7XG5cblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1hbHRlcm5hdGUtY29sb3IpO1xuXHRcdGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMtcm91bmRlZCk7XG5cdFx0Ym9yZGVyOiBub25lO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvcik7XG5cblx0XHRjdXJzb3I6IHBvaW50ZXI7XG5cblx0XHR0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kLWNvbG9yIDAuMnMgZWFzZS1vdXQ7XG5cdH1cblxuXHQucm9vdDo6YmVmb3JlIHtcblx0XHRjb250ZW50OiAnJztcblxuXHRcdHBvc2l0aW9uOiBhYnNvbHV0ZTtcblx0XHR0b3A6IDA7XG5cdFx0cmlnaHQ6IDA7XG5cdFx0Ym90dG9tOiAwO1xuXHRcdGxlZnQ6IDA7XG5cblx0XHRvcGFjaXR5OiAwO1xuXHRcdGJvcmRlci1sZWZ0OiAycHggc29saWQgdmFyKC0tYWx0ZXJuYXRlLWNvbG9yLWludGVyYWN0aXZlKTtcblx0XHRib3JkZXItcmlnaHQ6IDJweCBzb2xpZCB2YXIoLS1hbHRlcm5hdGUtY29sb3ItaW50ZXJhY3RpdmUpO1xuXHRcdGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMtcm91bmRlZCk7XG5cdH1cblxuXHQucm9vdDo6YWZ0ZXIge1xuXHRcdGNvbnRlbnQ6ICcnO1xuXG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMnB4O1xuXHRcdHJpZ2h0OiAycHg7XG5cdFx0Ym90dG9tOiAycHg7XG5cdFx0bGVmdDogMnB4O1xuXG5cdFx0b3BhY2l0eTogMDtcblx0XHRib3gtc2hhZG93OiAwIDAgMCAycHggdmFyKC0tc2lsdmVyLWNvbG9yKTtcblx0XHRib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzLXJvdW5kZWQpO1xuXG5cdFx0dHJhbnNpdGlvbjogb3BhY2l0eSAwLjJzIGVhc2Utb3V0O1xuXHR9XG5cblx0LmFsdCB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7XG5cdFx0Ym9yZGVyOiAycHggc29saWQgdmFyKC0tc2lsdmVyLWNvbG9yKTtcblx0fVxuXG5cdC5hbHQ6OmJlZm9yZSB7XG5cdFx0Ym9yZGVyLWNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LmFsdDo6YWZ0ZXIge1xuXHRcdGNvbnRlbnQ6IG5vbmU7XG5cdH1cblxuXHQucm9vdDpob3ZlciB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yLWludGVyYWN0aXZlKTtcblx0fVxuXG5cdC5yb290OmhvdmVyOjpiZWZvcmUge1xuXHRcdGFuaW1hdGlvbjogcHVsc2UgMC44cyBlYXNlLW91dDtcblx0fVxuXG5cdC5hbHQ6aG92ZXIge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHZhcigtLWFsdGVybmF0ZS1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQucm9vdDpmb2N1cyB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yLWludGVyYWN0aXZlKTtcblx0fVxuXG5cdC5yb290OmZvY3VzOmFmdGVyIHtcblx0XHRvcGFjaXR5OiAxO1xuXHR9XG5cblx0QGtleWZyYW1lcyBwdWxzZSB7XG5cdFx0MCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cblx0XHQ1MCUge1xuXHRcdFx0b3BhY2l0eTogMTtcblx0XHR9XG5cblx0XHQxMDAlIHtcblx0XHRcdG9wYWNpdHk6IDA7XG5cblx0XHRcdHRyYW5zZm9ybTogc2NhbGUoMS4yKTtcblx0XHR9XG5cdH1cbjwvc3R5bGU+XG4iLCI8c2NyaXB0PlxuXHRpbXBvcnQgSW5saW5lU1ZHIGZyb20gJ3N2ZWx0ZS1pbmxpbmUtc3ZnJztcblxuXHRleHBvcnQgbGV0IHNyYyA9ICcnO1xuXHRleHBvcnQgbGV0IHcgPSAnYXV0byc7XG48L3NjcmlwdD5cblxuPElubGluZVNWRyB7c3JjfSB3aWR0aD17d30gLz5cbiIsImV4cG9ydCB7IGRlZmF1bHQgYXMgQnV0dG9uIH0gZnJvbSBcIi4vQnV0dG9uL2luZGV4LnN2ZWx0ZVwiO1xuZXhwb3J0IHsgZGVmYXVsdCBhcyBJY29uIH0gZnJvbSBcIi4vSWNvbi9pbmRleC5zdmVsdGVcIjtcbiIsIjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPldlbGNvbWU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZseSB9IGZyb20gJ3N2ZWx0ZS90cmFuc2l0aW9uJztcblx0aW1wb3J0IHsgZWxhc3RpY091dCwgcXVpbnRPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgQnV0dG9uLCBJY29uIH0gZnJvbSAnLi4vY29tcG9uZW50cyc7XG5cblx0bGV0IGxvYWRlZCA9IGZhbHNlO1xuXG5cdG9uTW91bnQoKCkgPT4ge1xuXHRcdGxvYWRlZCA9IHRydWU7XG5cdH0pO1xuPC9zY3JpcHQ+XG5cbnsjaWYgbG9hZGVkfVxuXHQ8bWFpbiBjbGFzcz1cInJvb3RcIj5cblx0XHQ8aDFcblx0XHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC0zMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDMwMH19XG5cdFx0XHRvdXQ6Zmx5PXt7b3BhY2l0eTogMCwgeTogLTMwLCBlYXNpbmc6IHF1aW50T3V0fX1cblx0XHRcdGNsYXNzPVwibG9nb19fdGV4dFwiXG5cdFx0PlxuXHRcdFx0Y29tYXRlXG5cdFx0PC9oMT5cblxuXHRcdDxkaXY+XG5cdFx0XHQ8ZGl2XG5cdFx0XHRcdGluOmZseT17e29wYWNpdHk6IDAsIHg6IDIwMCwgeTogLTIwMCwgZWFzaW5nOiBxdWludE91dCwgZHVyYXRpb246IDYwMH19XG5cdFx0XHRcdG91dDpmbHk9e3tvcGFjaXR5OiAwLCB4OiAtMjAwLCB5OiAyMDAsIGVhc2luZzogcXVpbnRPdXQsIGRlbGF5OiAyMDAsIGR1cmF0aW9uOiA2MDB9fVxuXHRcdFx0PlxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9sb2dvLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjEwMFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9kaXY+XG5cblx0XHRcdDxwXG5cdFx0XHRcdGNsYXNzPVwiZGVzY3JpcHRpb25fX21haW5cIlxuXHRcdFx0XHRpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBxdWludE91dCwgZGVsYXk6IDEwMH19XG5cdFx0XHRcdG91dDpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBxdWludE91dCwgZGVsYXk6IDEwMH19XG5cdFx0XHQ+XG5cdFx0XHRcdENvbWF0ZSBpcyBhbiBob25lc3QgYWxhcm0gY2xvY2sgdG8gPHNwYW4gY2xhc3M9XCJoaWdobGlnaHRcIj5oZWxwIHlvdSBzbGVlcC48L3NwYW4+IFRoZSBhdmVyYWdlIGh1bWFuIGJlaW5nIG5lZWRzIDxzcGFuIGNsYXNzPVwiaGlnaGxpZ2h0XCI+OCBob3VycyBvZiBzbGVlcDwvc3Bhbj4gcGVyIG5pZ2h0LlxuXHRcdFx0PC9wPlxuXG5cdFx0XHQ8c21hbGxcblx0XHRcdFx0Y2xhc3M9XCJkZXNjcmlwdGlvbl9fZXh0cmFcIlxuXHRcdFx0XHRpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBxdWludE91dCwgZGVsYXk6IDIwMH19XG5cdFx0XHRcdG91dDpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBxdWludE91dH19XG5cdFx0XHQ+XG5cdFx0XHRcdFdpdGggY29tYXRlIHlvdSBkb24ndCBzbGVlcCB0aWxsIDdBTSwgeW91IHNsZWVwIHRpbGwgeW91J3ZlIGhhZCBlbm91Z2ggc2xlZXAgdG8gZnVuY3Rpb24gcHJvcGVybHkgZXZlcnlkYXkuXG5cdFx0XHQ8L3NtYWxsPlxuXHRcdDwvZGl2PlxuXG5cdFx0PGRpdlxuXHRcdFx0aW46Zmx5PXt7b3BhY2l0eTogMCwgeTogNTAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAzMDB9fVxuXHRcdFx0b3V0OmZseT17e29wYWNpdHk6IDAsIHk6IDUwLCBlYXNpbmc6IHF1aW50T3V0fX1cblx0XHQ+XG5cdFx0XHQ8QnV0dG9uIHVybD1cIi9hcHBcIj5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlB1dCBtZSBpbiBhIGNvbWE8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvYXJyb3cuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMThcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHQ8L21haW4+XG57L2lmfVxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXgtd2lkdGg6IDQyMHB4O1xuXHRcdG1hcmdpbjogMCBhdXRvO1xuXHRcdHBhZGRpbmc6IDMwcHggMjBweCA1MHB4O1xuXHR9XG5cblx0LmxvZ29fX3RleHQge1xuXHRcdGZvbnQtc2l6ZTogMzBweDtcblx0XHRmb250LXdlaWdodDogMjAwO1xuXHR9XG5cblx0LmRlc2NyaXB0aW9uX19tYWluIHtcblx0XHRtYXJnaW4tdG9wOiAyMHB4O1xuXG5cdFx0Zm9udC1zaXplOiAxOHB4O1xuXHR9XG5cblx0LmRlc2NyaXB0aW9uX19leHRyYSB7XG5cdFx0ZGlzcGxheTogYmxvY2s7XG5cdFx0bWFyZ2luLXRvcDogMTVweDtcblxuXHRcdGZvbnQtc2l6ZTogMTRweDtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LmhpZ2hsaWdodCB7XG5cdFx0Y29sb3I6IHZhcigtLWhpZ2hsaWdodC1jb2xvcik7XG5cdH1cbjwvc3R5bGU+XG4iXSwic291cmNlUm9vdCI6IiJ9