(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["app"],{

/***/ "./src/routes/app.svelte":
/*!*******************************!*\
  !*** ./src/routes/app.svelte ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _capacitor_core__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @capacitor/core */ "./node_modules/@capacitor/core/dist/esm/index.js");
/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../components */ "./src/components/index.js");
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");
/* src/routes/app.svelte generated by Svelte v3.24.1 */


const { console: console_1, document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];






const file = "src/routes/app.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-9n5j34-style";
	style.textContent = ".root.svelte-9n5j34{display:flex;flex-direction:column;justify-content:space-between;align-items:center;margin:0 auto;padding:15px 20px 50px}.header.svelte-9n5j34{display:flex;align-items:center;width:100%}.header__icon.svelte-9n5j34{width:25px;height:25px;display:flex;justify-content:center;align-items:center;color:var(--highlight-color)}.header__text.svelte-9n5j34{font-size:16px;font-weight:200;margin:0 auto}.hidden.svelte-9n5j34{opacity:0;visibility:hidden;pointer-events:none}.time.svelte-9n5j34{position:relative;width:250px;height:250px;display:flex;justify-content:center;align-items:center;font-size:60px;text-shadow:0 15px 30px rgba(0, 0, 0, 0.8)}.time__progress.svelte-9n5j34{position:absolute;top:0;left:0;width:100%;height:100%}.time__progress-background.svelte-9n5j34,.time__progress-ring.svelte-9n5j34{stroke-width:var(--progress-width);fill:transparent}.time__progress-background.svelte-9n5j34{stroke:var(--alternate-color-faded)}.time__progress-ring.svelte-9n5j34{stroke:var(--alternate-color);transition:stroke-dashoffset 0.3s ease-out;transform:rotate(-90deg);transform-origin:center}.time__seconds.svelte-9n5j34{color:var(--silver-color-faded)}.audio.svelte-9n5j34{display:flex;justify-content:center;align-items:center;margin-top:30px}.audio__button.svelte-9n5j34{width:30px;height:30px;margin-left:10px;display:flex;justify-content:center;align-items:center;color:var(--silver-color)}.pulse.svelte-9n5j34{animation:svelte-9n5j34-flash 2s ease-in infinite}@keyframes svelte-9n5j34-flash{0%{opacity:1}60%{opacity:1}61%{opacity:0}100%{opacity:0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXBwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiYXBwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5jb21hdGUg4oCSIHtkZXZNb2RlID8gJG1pbnV0ZXMgOiAkaG91cnN9OntkZXZNb2RlID8gJHNlY29uZHMgOiAkbWludXRlc308L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZhZGUsIGZseSwgc2NhbGUgfSBmcm9tICdzdmVsdGUvdHJhbnNpdGlvbic7XG5cdGltcG9ydCB7IGVsYXN0aWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgUGx1Z2lucyB9IGZyb20gJ0BjYXBhY2l0b3IvY29yZSc7XG5cdGltcG9ydCB7IEJ1dHRvbiwgSWNvbiwgQXVkaW9QbGF5ZXIgfSBmcm9tICcuLi9jb21wb25lbnRzJztcblx0aW1wb3J0IHsgZWxhcHNlZFRpbWUsIGhvdXJzLCBtaW51dGVzLCBzZWNvbmRzIH0gZnJvbSAnLi4vc3RvcmUvdGltZXIuanMnO1xuXG5cdGNvbnN0IHsgSGFwdGljcywgTG9jYWxOb3RpZmljYXRpb25zLCBUb2FzdCB9ID0gUGx1Z2lucztcblxuXHRjb25zb2xlLmxvZygkZWxhcHNlZFRpbWUpO1xuXG5cdGNvbnN0IHNvdW5kcyA9IFtcblx0XHR7XG5cdFx0XHRzcmM6ICcvYXVkaW8vc291bmQxLm1wMycsXG5cdFx0XHR0aXRsZTogJ0FsYW5lJyxcblx0XHRcdG1ha2VyOiAnUm9iaW4gU2NodWx6ICYgV2VzJ1xuXHRcdH1cblx0XVxuXG5cdGxldCB0aW1lciA9IG51bGw7XG5cdGxldCBkZXZNb2RlID0gZmFsc2U7XG5cblx0JDogZWxhcHNlZFRpbWUucmVzZXQoZGV2TW9kZSk7XG5cblx0bGV0IHByb2dyZXNzV2lkdGggPSAwO1xuXHRsZXQgY2lyY2xlID0gbnVsbDtcblx0bGV0IGNpcmN1bWZlcmVuY2UgPSAwO1xuXG5cdG9uTW91bnQoYXN5bmMoKSA9PiB7XG5cdFx0aW5pdFByb2dyZXNzUmluZygpO1xuXG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnJlcXVlc3RQZXJtaXNzaW9uKCk7XG5cdH0pO1xuXG5cdGNvbnN0IGluaXRQcm9ncmVzc1JpbmcgPSAoKSA9PiB7XG5cdFx0cHJvZ3Jlc3NXaWR0aCA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuZ2V0UHJvcGVydHlWYWx1ZSgnLS1wcm9ncmVzcy13aWR0aCcpO1xuXG5cdFx0Y2lyY3VtZmVyZW5jZSA9IGNpcmNsZS5yLmJhc2VWYWwudmFsdWUgKiAyICogTWF0aC5QSTtcblxuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNoYXJyYXkgPSBgJHtjaXJjdW1mZXJlbmNlfSAke2NpcmN1bWZlcmVuY2V9YDtcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IDA7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVQcm9ncmVzcyA9IChlbGFwc2VkVGltZSkgPT4ge1xuXHRcdGNvbnN0IHByb2dyZXNzID0gMSAtIChlbGFwc2VkVGltZSAvICR0aW1lKTtcblx0XHRjb25zdCBvZmZzZXQgPSBjaXJjdW1mZXJlbmNlICogcHJvZ3Jlc3M7XG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSBvZmZzZXQ7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVTdGFydCA9ICgpID0+IHtcblx0XHR0aW1lciA9IHNldEludGVydmFsKCgpID0+IHtcblx0XHRcdGVsYXBzZWRUaW1lLnVwZGF0ZSh0aW1lID0+IHRpbWUgLSAxMDAwKTtcblxuXHRcdFx0aGFuZGxlUHJvZ3Jlc3MoJGVsYXBzZWRUaW1lKTtcblxuXHRcdFx0aWYgKCRlbGFwc2VkVGltZSA8PSAwKSB7XG5cdFx0XHRcdGhhbmRsZVJlc2V0KCk7XG5cdFx0XHRcdGhhbmRsZVN0b3AoKTtcblx0XHRcdH1cblx0XHR9LCAxMDAwKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0b3AgPSBhc3luYygpID0+IHtcblx0XHRhd2FpdCBMb2NhbE5vdGlmaWNhdGlvbnMuc2NoZWR1bGUoe1xuXHRcdFx0bm90aWZpY2F0aW9uczogW1xuXHRcdFx0ICB7XG5cdFx0XHRcdHRpdGxlOiBcIldha2UgdXAhXCIsXG5cdFx0XHRcdGJvZHk6IFwiQSBsb3ZlbHkgZGF5IGlzIHdhaXRpbmcgZm9yIHlvdS5cIixcblx0XHRcdFx0aWQ6IDEsXG5cdFx0XHQgIH1cblx0XHRcdF1cblx0XHR9KTtcblxuXHRcdGF1ZGlvLnBsYXkoKTtcblxuXHRcdEhhcHRpY3MudmlicmF0ZSgpO1xuXG5cdFx0Y29uc29sZS5sb2coJ3BsYXkgc291bmQnKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVJlc2V0ID0gKCkgPT4ge1xuXHRcdGNsZWFySW50ZXJ2YWwodGltZXIpO1xuXG5cdFx0ZWxhcHNlZFRpbWUucmVzZXQoZGV2TW9kZSk7XG5cdFx0dGltZXIgPSBudWxsO1xuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNob2Zmc2V0ID0gMDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZURldk1vZGUgPSBhc3luYygpID0+IHtcblx0XHRkZXZNb2RlID0gIWRldk1vZGU7XG5cblx0XHRhd2FpdCBUb2FzdC5zaG93KHtcblx0XHRcdHRleHQ6IGRldk1vZGUgPyAnREVWIG1vZGUgZW5hYmxlZCcgOiAnREVWIG1vZGUgZGlzYWJsZWQnLFxuXHRcdFx0cG9zaXRpb246ICd0b3AnXG5cdFx0fSk7XG5cdH1cbjwvc2NyaXB0PlxuXG48bWFpbiBjbGFzcz1cInJvb3RcIj5cblx0PGhlYWRlclxuXHRcdGNsYXNzPVwiaGVhZGVyXCJcblx0XHRpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAtNTAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiA5NTB9fVxuXHQ+XG5cdFx0PGFcblx0XHRcdGhyZWY9XCIvXCJcblx0XHRcdGNsYXNzPVwiaGVhZGVyX19pY29uXCJcblx0XHQ+XG5cdFx0XHQ8SWNvblxuXHRcdFx0XHRzcmM9XCIvaW5mby5zdmdcIlxuXHRcdFx0XHR3PVwiNlwiXG5cdFx0XHQ+XG5cdFx0XHQ8L0ljb24+XG5cdFx0PC9hPlxuXG5cdFx0PGgxIGNsYXNzPVwiaGVhZGVyX190ZXh0XCI+XG5cdFx0XHRjb21hdGVcblx0XHQ8L2gxPlxuXG5cdFx0PGJ1dHRvblxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdFx0Y2xhc3M6aGlkZGVuPXshIXRpbWVyfVxuXHRcdFx0b246Y2xpY2s9e2hhbmRsZURldk1vZGV9XG5cdFx0PlxuXHRcdFx0eyNpZiAhZGV2TW9kZX1cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvY29kZS5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxOFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0ezplbHNlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jbG9jay5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxOFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0ey9pZn1cblx0XHQ8L2J1dHRvbj5cblx0PC9oZWFkZXI+XG5cblx0PGRpdj5cblx0XHQ8c3BhblxuXHRcdFx0aW46c2NhbGU9e3tvcGFjaXR5OiAwLCBzdGFydDogMC41LCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMTAwMH19XG5cdFx0XHRjbGFzcz1cInRpbWVcIlxuXHRcdD5cblx0XHRcdHsjaWYgZGV2TW9kZX1cblx0XHRcdFx0PHNwYW5cblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3NlY29uZHNcIlxuXHRcdFx0XHRcdGluOmZhZGVcblx0XHRcdFx0PlxuXHRcdFx0XHRcdHskbWludXRlc308c3BhbiBjbGFzczpwdWxzZT17dGltZXJ9Pjo8L3NwYW4+eyRzZWNvbmRzfVxuXHRcdFx0XHQ8L3NwYW4+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxzcGFuIGluOmZhZGU+XG5cdFx0XHRcdFx0eyRob3Vyc308c3BhbiBjbGFzczpwdWxzZT17dGltZXJ9Pjo8L3NwYW4+eyRtaW51dGVzfVxuXHRcdFx0XHQ8L3NwYW4+XG5cdFx0XHR7L2lmfVxuXG5cdFx0XHQ8c3ZnIGNsYXNzPVwidGltZV9fcHJvZ3Jlc3NcIj5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZFwiXG5cdFx0XHRcdFx0cj17MTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKX1cblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXG5cdFx0XHRcdDxjaXJjbGVcblx0XHRcdFx0XHRiaW5kOnRoaXM9e2NpcmNsZX1cblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3Byb2dyZXNzLXJpbmdcIlxuXHRcdFx0XHRcdHI9ezEyNSAtIChwcm9ncmVzc1dpZHRoIC8gMil9XG5cdFx0XHRcdFx0Y3g9XCIxMjVcIlxuXHRcdFx0XHRcdGN5PVwiMTI1XCJcblx0XHRcdFx0Lz5cblx0XHRcdDwvc3ZnPlxuXHRcdDwvc3Bhbj5cblxuXHRcdDxkaXYgY2xhc3M9XCJhdWRpb1wiPlxuXHRcdFx0eyNlYWNoIHNvdW5kcyBhcyBzb3VuZH1cblx0XHRcdFx0PEF1ZGlvUGxheWVyXG5cdFx0XHRcdFx0ey4uLnNvdW5kfVxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvQXVkaW9QbGF5ZXI+XG5cdFx0XHR7L2VhY2h9XG5cblx0XHRcdDxidXR0b25cblx0XHRcdFx0Y2xhc3M9XCJhdWRpb19fYnV0dG9uXCJcblx0XHRcdD5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvYXVkaW8uc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvYnV0dG9uPlxuXHRcdDwvZGl2PlxuXHQ8L2Rpdj5cblxuXHR7I2lmICF0aW1lcn1cblx0XHQ8ZGl2IGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMjAwfX0+XG5cdFx0XHQ8QnV0dG9uIG9uOmNsaWNrPXtoYW5kbGVTdGFydH0+XG5cdFx0XHRcdDxzcGFuIGNsYXNzPVwidS1pY29uLXNwYWNpbmdcIj5TdGFydCBzbGVlcCBjeWNsZTwvc3Bhbj5cblxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9wbGF5LnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE0XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L0J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0ezplbHNlfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b25cblx0XHRcdFx0YWx0XG5cdFx0XHRcdG9uOmNsaWNrPXtoYW5kbGVSZXNldH1cblx0XHRcdD5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlJlc2V0PC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3Jlc2V0LnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE2XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L0J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0ey9pZn1cbjwvbWFpbj5cblxuPHN0eWxlPlxuXHQucm9vdCB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuXHRcdGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2Vlbjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdFx0cGFkZGluZzogMTVweCAyMHB4IDUwcHg7XG5cdH1cblxuXHQuaGVhZGVyIHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdH1cblxuXHQuaGVhZGVyX19pY29uIHtcblx0XHR3aWR0aDogMjVweDtcblx0XHRoZWlnaHQ6IDI1cHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRjb2xvcjogdmFyKC0taGlnaGxpZ2h0LWNvbG9yKTtcblx0fVxuXG5cdC5oZWFkZXJfX3RleHQge1xuXHRcdGZvbnQtc2l6ZTogMTZweDtcblx0XHRmb250LXdlaWdodDogMjAwO1xuXHRcdG1hcmdpbjogMCBhdXRvO1xuXHR9XG5cblx0LmhpZGRlbiB7XG5cdFx0b3BhY2l0eTogMDtcblx0XHR2aXNpYmlsaXR5OiBoaWRkZW47XG5cdFx0cG9pbnRlci1ldmVudHM6IG5vbmU7XG5cdH1cblxuXHQudGltZSB7XG5cdFx0cG9zaXRpb246IHJlbGF0aXZlO1xuXHRcdHdpZHRoOiAyNTBweDtcblx0XHRoZWlnaHQ6IDI1MHB4O1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0Zm9udC1zaXplOiA2MHB4O1xuXHRcdHRleHQtc2hhZG93OiAwIDE1cHggMzBweCByZ2JhKDAsIDAsIDAsIDAuOCk7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3Mge1xuXHRcdHBvc2l0aW9uOiBhYnNvbHV0ZTtcblx0XHR0b3A6IDA7XG5cdFx0bGVmdDogMDtcblx0XHR3aWR0aDogMTAwJTtcblx0XHRoZWlnaHQ6IDEwMCU7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCxcblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZS13aWR0aDogdmFyKC0tcHJvZ3Jlc3Mtd2lkdGgpO1xuXHRcdGZpbGw6IHRyYW5zcGFyZW50O1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLWJhY2tncm91bmQge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yLWZhZGVkKTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1yaW5nIHtcblx0XHRzdHJva2U6IHZhcigtLWFsdGVybmF0ZS1jb2xvcik7XG5cblx0XHR0cmFuc2l0aW9uOiBzdHJva2UtZGFzaG9mZnNldCAwLjNzIGVhc2Utb3V0O1xuXHRcdHRyYW5zZm9ybTogcm90YXRlKC05MGRlZyk7XG5cdFx0dHJhbnNmb3JtLW9yaWdpbjogY2VudGVyO1xuXHR9XG5cblx0LnRpbWVfX3NlY29uZHMge1xuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LmF1ZGlvIHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cdFx0bWFyZ2luLXRvcDogMzBweDtcblx0fVxuXG5cdC5hdWRpb19fYnV0dG9uIHtcblx0XHR3aWR0aDogMzBweDtcblx0XHRoZWlnaHQ6IDMwcHg7XG5cdFx0bWFyZ2luLWxlZnQ6IDEwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRjb2xvcjogdmFyKC0tc2lsdmVyLWNvbG9yKTtcblx0fVxuXG5cdC5wdWxzZSB7XG5cdFx0YW5pbWF0aW9uOiBmbGFzaCAycyBlYXNlLWluIGluZmluaXRlO1xuXHR9XG5cblx0QGtleWZyYW1lcyBmbGFzaCB7XG5cdFx0MCUge1xuXHRcdFx0b3BhY2l0eTogMTtcblx0XHR9XG5cblx0XHQ2MCUge1xuXHRcdFx0b3BhY2l0eTogMTtcblx0XHR9XG5cblx0XHQ2MSUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cblx0XHQxMDAlIHtcblx0XHRcdG9wYWNpdHk6IDA7XG5cdFx0fVxuXHR9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1T0MsS0FBSyxjQUFDLENBQUMsQUFDTixPQUFPLENBQUUsSUFBSSxDQUNiLGNBQWMsQ0FBRSxNQUFNLENBQ3RCLGVBQWUsQ0FBRSxhQUFhLENBQzlCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUNkLE9BQU8sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQUFDeEIsQ0FBQyxBQUVELE9BQU8sY0FBQyxDQUFDLEFBQ1IsT0FBTyxDQUFFLElBQUksQ0FDYixXQUFXLENBQUUsTUFBTSxDQUNuQixLQUFLLENBQUUsSUFBSSxBQUNaLENBQUMsQUFFRCxhQUFhLGNBQUMsQ0FBQyxBQUNkLEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQ0FFWixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLEtBQUssQ0FBRSxJQUFJLGlCQUFpQixDQUFDLEFBQzlCLENBQUMsQUFFRCxhQUFhLGNBQUMsQ0FBQyxBQUNkLFNBQVMsQ0FBRSxJQUFJLENBQ2YsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLEFBQ2YsQ0FBQyxBQUVELE9BQU8sY0FBQyxDQUFDLEFBQ1IsT0FBTyxDQUFFLENBQUMsQ0FDVixVQUFVLENBQUUsTUFBTSxDQUNsQixjQUFjLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBRUQsS0FBSyxjQUFDLENBQUMsQUFDTixRQUFRLENBQUUsUUFBUSxDQUNsQixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxLQUFLLENBRWIsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUVuQixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxBQUM1QyxDQUFDLEFBRUQsZUFBZSxjQUFDLENBQUMsQUFDaEIsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsR0FBRyxDQUFFLENBQUMsQ0FDTixJQUFJLENBQUUsQ0FBQyxDQUNQLEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQUFDYixDQUFDLEFBRUQsd0NBQTBCLENBQzFCLG9CQUFvQixjQUFDLENBQUMsQUFDckIsWUFBWSxDQUFFLElBQUksZ0JBQWdCLENBQUMsQ0FDbkMsSUFBSSxDQUFFLFdBQVcsQUFDbEIsQ0FBQyxBQUVELDBCQUEwQixjQUFDLENBQUMsQUFDM0IsTUFBTSxDQUFFLElBQUksdUJBQXVCLENBQUMsQUFDckMsQ0FBQyxBQUVELG9CQUFvQixjQUFDLENBQUMsQUFDckIsTUFBTSxDQUFFLElBQUksaUJBQWlCLENBQUMsQ0FFOUIsVUFBVSxDQUFFLGlCQUFpQixDQUFDLElBQUksQ0FBQyxRQUFRLENBQzNDLFNBQVMsQ0FBRSxPQUFPLE1BQU0sQ0FBQyxDQUN6QixnQkFBZ0IsQ0FBRSxNQUFNLEFBQ3pCLENBQUMsQUFFRCxjQUFjLGNBQUMsQ0FBQyxBQUNmLEtBQUssQ0FBRSxJQUFJLG9CQUFvQixDQUFDLEFBQ2pDLENBQUMsQUFFRCxNQUFNLGNBQUMsQ0FBQyxBQUNQLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQ0FDbkIsVUFBVSxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUVELGNBQWMsY0FBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUNaLFdBQVcsQ0FBRSxJQUFJLENBRWpCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsS0FBSyxDQUFFLElBQUksY0FBYyxDQUFDLEFBQzNCLENBQUMsQUFFRCxNQUFNLGNBQUMsQ0FBQyxBQUNQLFNBQVMsQ0FBRSxtQkFBSyxDQUFDLEVBQUUsQ0FBQyxPQUFPLENBQUMsUUFBUSxBQUNyQyxDQUFDLEFBRUQsV0FBVyxtQkFBTSxDQUFDLEFBQ2pCLEVBQUUsQUFBQyxDQUFDLEFBQ0gsT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsR0FBRyxBQUFDLENBQUMsQUFDSixPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxHQUFHLEFBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxDQUFDLEFBQ1gsQ0FBQyxBQUVELElBQUksQUFBQyxDQUFDLEFBQ0wsT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBQ0YsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[21] = list[i];
	return child_ctx;
}

// (135:3) {:else}
function create_else_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/clock.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_2.name,
		type: "else",
		source: "(135:3) {:else}",
		ctx
	});

	return block;
}

// (129:3) {#if !devMode}
function create_if_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/code.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(129:3) {#if !devMode}",
		ctx
	});

	return block;
}

// (157:3) {:else}
function create_else_block_1(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$hours*/ ctx[5]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[4]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", {});
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$hours*/ ctx[5]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[4]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 158, 13, 3053);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 157, 4, 3025);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$hours*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$hours*/ ctx[5]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$minutes*/ 16) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$minutes*/ ctx[4]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_1.name,
		type: "else",
		source: "(157:3) {:else}",
		ctx
	});

	return block;
}

// (150:3) {#if devMode}
function create_if_block_1(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[4]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$seconds*/ ctx[6]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[4]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$seconds*/ ctx[6]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 154, 15, 2953);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "time__seconds svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 150, 4, 2886);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$minutes*/ 16) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$minutes*/ ctx[4]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$seconds*/ 64) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$seconds*/ ctx[6]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(150:3) {#if devMode}",
		ctx
	});

	return block;
}

// (182:3) {#each sounds as sound}
function create_each_block(ctx) {
	let audioplayer;
	let current;
	const audioplayer_spread_levels = [/*sound*/ ctx[21]];
	let audioplayer_props = {};

	for (let i = 0; i < audioplayer_spread_levels.length; i += 1) {
		audioplayer_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(audioplayer_props, audioplayer_spread_levels[i]);
	}

	audioplayer = new _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"]({ props: audioplayer_props, $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(audioplayer.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(audioplayer.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(audioplayer, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const audioplayer_changes = (dirty & /*sounds*/ 128)
			? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(audioplayer_spread_levels, [Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_object"])(/*sound*/ ctx[21])])
			: {};

			if (dirty & /*$$scope*/ 16777216) {
				audioplayer_changes.$$scope = { dirty, ctx };
			}

			audioplayer.$set(audioplayer_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(audioplayer.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(audioplayer.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(audioplayer, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(182:3) {#each sounds as sound}",
		ctx
	});

	return block;
}

// (213:1) {:else}
function create_else_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				alt: true,
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleReset*/ ctx[9]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 213, 2, 3975);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(213:1) {:else}",
		ctx
	});

	return block;
}

// (201:1) {#if !timer}
function create_if_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleStart*/ ctx[8]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 201, 2, 3704);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(201:1) {#if !timer}",
		ctx
	});

	return block;
}

// (215:3) <Button     alt     on:click={handleReset}    >
function create_default_slot_2(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/reset.svg", w: "16" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Reset");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Reset");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 218, 4, 4113);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(215:3) <Button     alt     on:click={handleReset}    >",
		ctx
	});

	return block;
}

// (203:3) <Button on:click={handleStart}>
function create_default_slot(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/play.svg", w: "14" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Start sleep cycle");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Start sleep cycle");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 203, 4, 3826);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(203:3) <Button on:click={handleStart}>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let main;
	let header;
	let a;
	let icon0;
	let t1;
	let h1;
	let t2;
	let t3;
	let button0;
	let current_block_type_index;
	let if_block0;
	let header_intro;
	let t4;
	let div1;
	let span;
	let t5;
	let svg;
	let circle0;
	let circle0_r_value;
	let circle1;
	let circle1_r_value;
	let span_intro;
	let t6;
	let div0;
	let t7;
	let button1;
	let icon1;
	let t8;
	let current_block_type_index_1;
	let if_block2;
	let current;
	let mounted;
	let dispose;

	document_1.title = title_value = "comate ‒ " + (/*devMode*/ ctx[1]
	? /*$minutes*/ ctx[4]
	: /*$hours*/ ctx[5]) + ":" + (/*devMode*/ ctx[1]
	? /*$seconds*/ ctx[6]
	: /*$minutes*/ ctx[4]);

	icon0 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/info.svg", w: "6" },
			$$inline: true
		});

	const if_block_creators = [create_if_block_2, create_else_block_2];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (!/*devMode*/ ctx[1]) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	function select_block_type_1(ctx, dirty) {
		if (/*devMode*/ ctx[1]) return create_if_block_1;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_1(ctx, -1);
	let if_block1 = current_block_type(ctx);
	let each_value = /*sounds*/ ctx[7];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	icon1 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/audio.svg", w: "16" },
			$$inline: true
		});

	const if_block_creators_1 = [create_if_block, create_else_block];
	const if_blocks_1 = [];

	function select_block_type_2(ctx, dirty) {
		if (!/*timer*/ ctx[0]) return 0;
		return 1;
	}

	current_block_type_index_1 = select_block_type_2(ctx, -1);
	if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon0.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("comate");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon1.$$.fragment);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if_block2.c();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1rk5ch9\"]", document_1.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "HEADER", { class: true });
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "A", { href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon0.$$.fragment, a_nodes);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "comate");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "BUTTON", { class: true });
			var button0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button0);
			if_block0.l(button0_nodes);
			button0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			if_block1.l(span_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "svg", { class: true }, 1);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div0_nodes);
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon1.$$.fragment, button1_nodes);
			button1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			if_block2.l(main_nodes);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 108, 2, 2312);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "header__text svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 119, 2, 2420);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button0, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button0, file, 123, 2, 2467);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(header, "class", "header svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 104, 1, 2202);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "class", "time__progress-background svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", circle0_r_value = 125 - /*progressWidth*/ ctx[2] / 2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle0, file, 163, 4, 3156);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "class", "time__progress-ring svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", circle1_r_value = 125 - /*progressWidth*/ ctx[2] / 2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle1, file, 170, 4, 3278);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "class", "time__progress svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 162, 3, 3123);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "time svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 145, 2, 2751);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button1, "class", "audio__button svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button1, file, 188, 3, 3556);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "audio svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 180, 2, 3436);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 144, 1, 2743);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "class", "root svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 103, 0, 2181);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon0, a, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, button0);
			if_blocks[current_block_type_index].m(button0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, span);
			if_block1.m(span, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle1);
			/*circle1_binding*/ ctx[11](circle1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon1, button1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t8);
			if_blocks_1[current_block_type_index_1].m(main, null);
			current = true;

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button0, "click", /*handleDevMode*/ ctx[10], false, false, false);
				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if ((!current || dirty & /*devMode, $minutes, $hours, $seconds*/ 114) && title_value !== (title_value = "comate ‒ " + (/*devMode*/ ctx[1]
			? /*$minutes*/ ctx[4]
			: /*$hours*/ ctx[5]) + ":" + (/*devMode*/ ctx[1]
			? /*$seconds*/ ctx[6]
			: /*$minutes*/ ctx[4]))) {
				document_1.title = title_value;
			}

			const icon0_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				icon0_changes.$$scope = { dirty, ctx };
			}

			icon0.$set(icon0_changes);
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index !== previous_block_index) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block0 = if_blocks[current_block_type_index];

				if (!if_block0) {
					if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block0.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
				if_block0.m(button0, null);
			}

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			}

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block1) {
				if_block1.p(ctx, dirty);
			} else {
				if_block1.d(1);
				if_block1 = current_block_type(ctx);

				if (if_block1) {
					if_block1.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					if_block1.m(span, t5);
				}
			}

			if (!current || dirty & /*progressWidth*/ 4 && circle0_r_value !== (circle0_r_value = 125 - /*progressWidth*/ ctx[2] / 2)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", circle0_r_value);
			}

			if (!current || dirty & /*progressWidth*/ 4 && circle1_r_value !== (circle1_r_value = 125 - /*progressWidth*/ ctx[2] / 2)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", circle1_r_value);
			}

			if (dirty & /*sounds*/ 128) {
				each_value = /*sounds*/ ctx[7];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(div0, t7);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			const icon1_changes = {};

			if (dirty & /*$$scope*/ 16777216) {
				icon1_changes.$$scope = { dirty, ctx };
			}

			icon1.$set(icon1_changes);
			let previous_block_index_1 = current_block_type_index_1;
			current_block_type_index_1 = select_block_type_2(ctx, dirty);

			if (current_block_type_index_1 === previous_block_index_1) {
				if_blocks_1[current_block_type_index_1].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks_1[previous_block_index_1], 1, 1, () => {
					if_blocks_1[previous_block_index_1] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block2 = if_blocks_1[current_block_type_index_1];

				if (!if_block2) {
					if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);
					if_block2.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2, 1);
				if_block2.m(main, null);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0);

			if (!header_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					header_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(header, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: -50,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 950
					});

					header_intro.start();
				});
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1);

			if (!span_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"], {
						opacity: 0,
						start: 0.5,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 1000
					});

					span_intro.start();
				});
			}

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0);
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block2);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon0);
			if_blocks[current_block_type_index].d();
			if_block1.d();
			/*circle1_binding*/ ctx[11](null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon1);
			if_blocks_1[current_block_type_index_1].d();
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $elapsedTime;
	let $time;
	let $minutes;
	let $hours;
	let $seconds;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], "elapsedTime");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], $$value => $$invalidate(13, $elapsedTime = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(time, "time");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, time, $$value => $$invalidate(14, $time = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], "minutes");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], $$value => $$invalidate(4, $minutes = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], "hours");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], $$value => $$invalidate(5, $hours = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], "seconds");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], $$value => $$invalidate(6, $seconds = $$value));
	const { Haptics, LocalNotifications, Toast } = _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"];
	console.log($elapsedTime);

	const sounds = [
		{
			src: "/audio/sound1.mp3",
			title: "Alane",
			maker: "Robin Schulz & Wes"
		}
	];

	let timer = null;
	let devMode = false;
	let progressWidth = 0;
	let circle = null;
	let circumference = 0;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		initProgressRing();
		await LocalNotifications.requestPermission();
	});

	const initProgressRing = () => {
		$$invalidate(2, progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue("--progress-width"));
		circumference = circle.r.baseVal.value * 2 * Math.PI;
		$$invalidate(3, circle.style.strokeDasharray = `${circumference} ${circumference}`, circle);
		$$invalidate(3, circle.style.strokeDashoffset = 0, circle);
	};

	const handleProgress = elapsedTime => {
		const progress = 1 - elapsedTime / $time;
		const offset = circumference * progress;
		$$invalidate(3, circle.style.strokeDashoffset = offset, circle);
	};

	const handleStart = () => {
		$$invalidate(0, timer = setInterval(
			() => {
				_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].update(time => time - 1000);
				handleProgress($elapsedTime);

				if ($elapsedTime <= 0) {
					handleReset();
					handleStop();
				}
			},
			1000
		));
	};

	const handleStop = async () => {
		await LocalNotifications.schedule({
			notifications: [
				{
					title: "Wake up!",
					body: "A lovely day is waiting for you.",
					id: 1
				}
			]
		});

		audio.play();
		Haptics.vibrate();
		console.log("play sound");
	};

	const handleReset = () => {
		clearInterval(timer);
		_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		$$invalidate(0, timer = null);
		$$invalidate(3, circle.style.strokeDashoffset = 0, circle);
	};

	const handleDevMode = async () => {
		$$invalidate(1, devMode = !devMode);

		await Toast.show({
			text: devMode ? "DEV mode enabled" : "DEV mode disabled",
			position: "top"
		});
	};

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<App> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("App", $$slots, []);

	function circle1_binding($$value) {
		svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"][$$value ? "unshift" : "push"](() => {
			circle = $$value;
			$$invalidate(3, circle);
		});
	}

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"],
		scale: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"],
		elasticOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
		Plugins: _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"],
		Button: _components__WEBPACK_IMPORTED_MODULE_5__["Button"],
		Icon: _components__WEBPACK_IMPORTED_MODULE_5__["Icon"],
		AudioPlayer: _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"],
		elapsedTime: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"],
		hours: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"],
		minutes: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"],
		seconds: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"],
		Haptics,
		LocalNotifications,
		Toast,
		sounds,
		timer,
		devMode,
		progressWidth,
		circle,
		circumference,
		initProgressRing,
		handleProgress,
		handleStart,
		handleStop,
		handleReset,
		handleDevMode,
		$elapsedTime,
		$time,
		$minutes,
		$hours,
		$seconds
	});

	$$self.$inject_state = $$props => {
		if ("timer" in $$props) $$invalidate(0, timer = $$props.timer);
		if ("devMode" in $$props) $$invalidate(1, devMode = $$props.devMode);
		if ("progressWidth" in $$props) $$invalidate(2, progressWidth = $$props.progressWidth);
		if ("circle" in $$props) $$invalidate(3, circle = $$props.circle);
		if ("circumference" in $$props) circumference = $$props.circumference;
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*devMode*/ 2) {
			$: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		}
	};

	return [
		timer,
		devMode,
		progressWidth,
		circle,
		$minutes,
		$hours,
		$seconds,
		sounds,
		handleStart,
		handleReset,
		handleDevMode,
		circle1_binding
	];
}

class App extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-9n5j34-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (App);

/***/ }),

/***/ "./src/store/timer.js":
/*!****************************!*\
  !*** ./src/store/timer.js ***!
  \****************************/
/*! exports provided: elapsedTime, hours, minutes, seconds */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "elapsedTime", function() { return elapsedTime; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "hours", function() { return hours; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "minutes", function() { return minutes; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "seconds", function() { return seconds; });
/* harmony import */ var svelte_store__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/store */ "./node_modules/svelte/store/index.mjs");


const TIME = 28800000; // 8 hours in milliseconds
const DEV_TIME = 10000; // 10 seconds in milliseconds

const leadingZero = (value) => {
	return ('0' + value).slice(-2);
};

const createStore = () => {
	const { subscribe, set } = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["writable"])(TIME);

	const handleReset = (isDev) => {
		if (isDev) {
			set(DEV_TIME);
		} else {
			set(TIME)
		}
	}

	const getTime = (isDev) => {
		if (isDev) {
			return DEV_TIME;
		} else {
			return TIME;
		}
	}

	return {
		subscribe,
		reset: handleReset,
		time: getTime
	}
}

const elapsedTime = createStore();

const hours = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / (1000 * 60 * 60)) % 24)));
const minutes = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000 / 60) % 60 )));
const seconds = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000) % 60)));

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2FwcC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3N0b3JlL3RpbWVyLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFLa0M7QUFDb0I7QUFDVjtBQUNEO0FBQ2dCO0FBQ2U7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnRkFvSnBFLEdBQU07OztrRkFBb0MsR0FBUTs7Ozs7O21HQUFsRCxHQUFNOzs7OztxR0FBb0MsR0FBUTs7Ozs7O2tHQUF4QixHQUFLOzs7Ozs7Ozs7Ozs7a0hBQS9CLEdBQU07OzttR0FBb0IsR0FBSzs7O3NIQUFXLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrRkFKbEQsR0FBUTs7O2tGQUFvQyxHQUFROzs7Ozs7cUdBQXBELEdBQVE7Ozs7O3FHQUFvQyxHQUFROzs7Ozs7a0dBQXhCLEdBQUs7Ozs7Ozs7Ozs7Ozs7c0hBQWpDLEdBQVE7OzttR0FBb0IsR0FBSzs7O3NIQUFXLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OENBNkJqRCxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytMQUFMLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FDQWlDQSxHQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUFIVCxPQUFPLEVBQUUsQ0FBQztNQUFFLENBQUMsRUFBRSxFQUFFO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FDQVg1RCxHQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUFEaEIsT0FBTyxFQUFFLENBQUM7TUFBRSxDQUFDLEVBQUUsRUFBRTtNQUFFLE1BQU0sRUFBRSx3REFBVTtNQUFFLFFBQVEsRUFBRSxJQUFJO01BQUUsS0FBSyxFQUFFLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZEQXhNL0QsR0FBTztnQkFBRyxHQUFRO2NBQUcsR0FBTSwwQkFBRyxHQUFPO2dCQUFHLEdBQVE7Z0JBQUcsR0FBUTs7Ozs7Ozs7Ozs7bUJBK0hwRSxHQUFPOzs7Ozs7OztrQkFxQlIsR0FBTzs7Ozs7OzZCQWdDTCxHQUFNOzs7O2dDQUFYLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O2lCQW1CRixHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1R0EzRU8sR0FBSzs7Ozs7b0dBd0NoQixHQUFHLHFCQUFJLEdBQWEsTUFBRyxDQUFDOzs7OztvR0FReEIsR0FBRyxxQkFBSSxHQUFhLE1BQUcsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxSEEvQ25CLEdBQWE7Ozs7O3NJQTdIUixHQUFPO2tCQUFHLEdBQVE7Z0JBQUcsR0FBTSwwQkFBRyxHQUFPO2tCQUFHLEdBQVE7a0JBQUcsR0FBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3R0E0SDFELEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7eUZBd0NoQixHQUFHLHFCQUFJLEdBQWEsTUFBRyxDQUFDOzs7O3lGQVF4QixHQUFHLHFCQUFJLEdBQWEsTUFBRyxDQUFDOzs7Ozs0QkFRdEIsR0FBTTs7OzsrQkFBWCxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7O3dCQUFKLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUEzRUUsT0FBTyxFQUFFLENBQUM7TUFBRSxDQUFDLEdBQUcsRUFBRTtNQUFFLE1BQU0sRUFBRSx3REFBVTtNQUFFLFFBQVEsRUFBRSxJQUFJO01BQUUsS0FBSyxFQUFFLEdBQUc7Ozs7Ozs7Ozs7OztNQXdDL0QsT0FBTyxFQUFFLENBQUM7TUFBRSxLQUFLLEVBQUUsR0FBRztNQUFFLE1BQU0sRUFBRSx3REFBVTtNQUFFLFFBQVEsRUFBRSxJQUFJO01BQUUsS0FBSyxFQUFFLElBQUk7Ozs7Ozs7a0NBbUNoRixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7U0F6S0EsT0FBTyxFQUFFLGtCQUFrQixFQUFFLEtBQUssS0FBSyx1REFBTztDQUV0RCxPQUFPLENBQUMsR0FBRyxDQUFDLFlBQVk7O09BRWxCLE1BQU07O0dBRVYsR0FBRyxFQUFFLG1CQUFtQjtHQUN4QixLQUFLLEVBQUUsT0FBTztHQUNkLEtBQUssRUFBRSxvQkFBb0I7Ozs7S0FJekIsS0FBSyxHQUFHLElBQUk7S0FDWixPQUFPLEdBQUcsS0FBSztLQUlmLGFBQWEsR0FBRyxDQUFDO0tBQ2pCLE1BQU0sR0FBRyxJQUFJO0tBQ2IsYUFBYSxHQUFHLENBQUM7O0NBRXJCLHNEQUFPO0VBQ04sZ0JBQWdCO1FBRVYsa0JBQWtCLENBQUMsaUJBQWlCOzs7T0FHckMsZ0JBQWdCO2tCQUNyQixhQUFhLEdBQUcsTUFBTSxDQUFDLGdCQUFnQixDQUFDLFFBQVEsQ0FBQyxlQUFlLEVBQUUsZ0JBQWdCLENBQUMsa0JBQWtCO0VBRXJHLGFBQWEsR0FBRyxNQUFNLENBQUMsQ0FBQyxDQUFDLE9BQU8sQ0FBQyxLQUFLLEdBQUcsQ0FBQyxHQUFHLElBQUksQ0FBQyxFQUFFO2tCQUVwRCxNQUFNLENBQUMsS0FBSyxDQUFDLGVBQWUsTUFBTSxhQUFhLElBQUksYUFBYTtrQkFDaEUsTUFBTSxDQUFDLEtBQUssQ0FBQyxnQkFBZ0IsR0FBRyxDQUFDOzs7T0FHNUIsY0FBYyxHQUFJLFdBQVc7UUFDNUIsUUFBUSxHQUFHLENBQUMsR0FBSSxXQUFXLEdBQUcsS0FBSztRQUNuQyxNQUFNLEdBQUcsYUFBYSxHQUFHLFFBQVE7a0JBQ3ZDLE1BQU0sQ0FBQyxLQUFLLENBQUMsZ0JBQWdCLEdBQUcsTUFBTTs7O09BR2pDLFdBQVc7a0JBQ2hCLEtBQUssR0FBRyxXQUFXOztJQUNsQiwyREFBVyxDQUFDLE1BQU0sQ0FBQyxJQUFJLElBQUksSUFBSSxHQUFHLElBQUk7SUFFdEMsY0FBYyxDQUFDLFlBQVk7O1FBRXZCLFlBQVksSUFBSSxDQUFDO0tBQ3BCLFdBQVc7S0FDWCxVQUFVOzs7R0FFVCxJQUFJOzs7O09BR0YsVUFBVTtRQUNULGtCQUFrQixDQUFDLFFBQVE7R0FDaEMsYUFBYTs7S0FFWixLQUFLLEVBQUUsVUFBVTtLQUNqQixJQUFJLEVBQUUsa0NBQWtDO0tBQ3hDLEVBQUUsRUFBRSxDQUFDOzs7OztFQUtQLEtBQUssQ0FBQyxJQUFJO0VBRVYsT0FBTyxDQUFDLE9BQU87RUFFZixPQUFPLENBQUMsR0FBRyxDQUFDLFlBQVk7OztPQUduQixXQUFXO0VBQ2hCLGFBQWEsQ0FBQyxLQUFLO0VBRW5CLDJEQUFXLENBQUMsS0FBSyxDQUFDLE9BQU87a0JBQ3pCLEtBQUssR0FBRyxJQUFJO2tCQUNaLE1BQU0sQ0FBQyxLQUFLLENBQUMsZ0JBQWdCLEdBQUcsQ0FBQzs7O09BRzVCLGFBQWE7a0JBQ2xCLE9BQU8sSUFBSSxPQUFPOztRQUVaLEtBQUssQ0FBQyxJQUFJO0dBQ2YsSUFBSSxFQUFFLE9BQU8sR0FBRyxrQkFBa0IsR0FBRyxtQkFBbUI7R0FDeEQsUUFBUSxFQUFFLEtBQUs7Ozs7Ozs7Ozs7Ozs7OztHQXlFRixNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBaEpyQixDQUFDLEVBQUUsMkRBQVcsQ0FBQyxLQUFLLENBQUMsT0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUMzQjdCO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFpRDs7QUFFakQsc0JBQXNCO0FBQ3RCLHVCQUF1Qjs7QUFFdkI7QUFDQTtBQUNBOztBQUVBO0FBQ0EsUUFBUSxpQkFBaUIsR0FBRyw2REFBUTs7QUFFcEM7QUFDQTtBQUNBO0FBQ0EsR0FBRztBQUNIO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQSxHQUFHO0FBQ0g7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFTzs7QUFFQSxjQUFjLDREQUFPO0FBQ3JCLGdCQUFnQiw0REFBTztBQUN2QixnQkFBZ0IsNERBQU8sbUYiLCJmaWxlIjoiOGFiZGQ0ZTQwNDYzM2UwOGM1M2UvYXBwLmFwcC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPmNvbWF0ZSDigJIge2Rldk1vZGUgPyAkbWludXRlcyA6ICRob3Vyc306e2Rldk1vZGUgPyAkc2Vjb25kcyA6ICRtaW51dGVzfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2NyaXB0PlxuXHRpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcblx0aW1wb3J0IHsgZmFkZSwgZmx5LCBzY2FsZSB9IGZyb20gJ3N2ZWx0ZS90cmFuc2l0aW9uJztcblx0aW1wb3J0IHsgZWxhc3RpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuXHRpbXBvcnQgeyBQbHVnaW5zIH0gZnJvbSAnQGNhcGFjaXRvci9jb3JlJztcblx0aW1wb3J0IHsgQnV0dG9uLCBJY29uLCBBdWRpb1BsYXllciB9IGZyb20gJy4uL2NvbXBvbmVudHMnO1xuXHRpbXBvcnQgeyBlbGFwc2VkVGltZSwgaG91cnMsIG1pbnV0ZXMsIHNlY29uZHMgfSBmcm9tICcuLi9zdG9yZS90aW1lci5qcyc7XG5cblx0Y29uc3QgeyBIYXB0aWNzLCBMb2NhbE5vdGlmaWNhdGlvbnMsIFRvYXN0IH0gPSBQbHVnaW5zO1xuXG5cdGNvbnNvbGUubG9nKCRlbGFwc2VkVGltZSk7XG5cblx0Y29uc3Qgc291bmRzID0gW1xuXHRcdHtcblx0XHRcdHNyYzogJy9hdWRpby9zb3VuZDEubXAzJyxcblx0XHRcdHRpdGxlOiAnQWxhbmUnLFxuXHRcdFx0bWFrZXI6ICdSb2JpbiBTY2h1bHogJiBXZXMnXG5cdFx0fVxuXHRdXG5cblx0bGV0IHRpbWVyID0gbnVsbDtcblx0bGV0IGRldk1vZGUgPSBmYWxzZTtcblxuXHQkOiBlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblxuXHRsZXQgcHJvZ3Jlc3NXaWR0aCA9IDA7XG5cdGxldCBjaXJjbGUgPSBudWxsO1xuXHRsZXQgY2lyY3VtZmVyZW5jZSA9IDA7XG5cblx0b25Nb3VudChhc3luYygpID0+IHtcblx0XHRpbml0UHJvZ3Jlc3NSaW5nKCk7XG5cblx0XHRhd2FpdCBMb2NhbE5vdGlmaWNhdGlvbnMucmVxdWVzdFBlcm1pc3Npb24oKTtcblx0fSk7XG5cblx0Y29uc3QgaW5pdFByb2dyZXNzUmluZyA9ICgpID0+IHtcblx0XHRwcm9ncmVzc1dpZHRoID0gd2luZG93LmdldENvbXB1dGVkU3R5bGUoZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50KS5nZXRQcm9wZXJ0eVZhbHVlKCctLXByb2dyZXNzLXdpZHRoJyk7XG5cblx0XHRjaXJjdW1mZXJlbmNlID0gY2lyY2xlLnIuYmFzZVZhbC52YWx1ZSAqIDIgKiBNYXRoLlBJO1xuXG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hhcnJheSA9IGAke2NpcmN1bWZlcmVuY2V9ICR7Y2lyY3VtZmVyZW5jZX1gO1xuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNob2Zmc2V0ID0gMDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVByb2dyZXNzID0gKGVsYXBzZWRUaW1lKSA9PiB7XG5cdFx0Y29uc3QgcHJvZ3Jlc3MgPSAxIC0gKGVsYXBzZWRUaW1lIC8gJHRpbWUpO1xuXHRcdGNvbnN0IG9mZnNldCA9IGNpcmN1bWZlcmVuY2UgKiBwcm9ncmVzcztcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IG9mZnNldDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0YXJ0ID0gKCkgPT4ge1xuXHRcdHRpbWVyID0gc2V0SW50ZXJ2YWwoKCkgPT4ge1xuXHRcdFx0ZWxhcHNlZFRpbWUudXBkYXRlKHRpbWUgPT4gdGltZSAtIDEwMDApO1xuXG5cdFx0XHRoYW5kbGVQcm9ncmVzcygkZWxhcHNlZFRpbWUpO1xuXG5cdFx0XHRpZiAoJGVsYXBzZWRUaW1lIDw9IDApIHtcblx0XHRcdFx0aGFuZGxlUmVzZXQoKTtcblx0XHRcdFx0aGFuZGxlU3RvcCgpO1xuXHRcdFx0fVxuXHRcdH0sIDEwMDApO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlU3RvcCA9IGFzeW5jKCkgPT4ge1xuXHRcdGF3YWl0IExvY2FsTm90aWZpY2F0aW9ucy5zY2hlZHVsZSh7XG5cdFx0XHRub3RpZmljYXRpb25zOiBbXG5cdFx0XHQgIHtcblx0XHRcdFx0dGl0bGU6IFwiV2FrZSB1cCFcIixcblx0XHRcdFx0Ym9keTogXCJBIGxvdmVseSBkYXkgaXMgd2FpdGluZyBmb3IgeW91LlwiLFxuXHRcdFx0XHRpZDogMSxcblx0XHRcdCAgfVxuXHRcdFx0XVxuXHRcdH0pO1xuXG5cdFx0YXVkaW8ucGxheSgpO1xuXG5cdFx0SGFwdGljcy52aWJyYXRlKCk7XG5cblx0XHRjb25zb2xlLmxvZygncGxheSBzb3VuZCcpO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlUmVzZXQgPSAoKSA9PiB7XG5cdFx0Y2xlYXJJbnRlcnZhbCh0aW1lcik7XG5cblx0XHRlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblx0XHR0aW1lciA9IG51bGw7XG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSAwO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlRGV2TW9kZSA9IGFzeW5jKCkgPT4ge1xuXHRcdGRldk1vZGUgPSAhZGV2TW9kZTtcblxuXHRcdGF3YWl0IFRvYXN0LnNob3coe1xuXHRcdFx0dGV4dDogZGV2TW9kZSA/ICdERVYgbW9kZSBlbmFibGVkJyA6ICdERVYgbW9kZSBkaXNhYmxlZCcsXG5cdFx0XHRwb3NpdGlvbjogJ3RvcCdcblx0XHR9KTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHQ8aGVhZGVyXG5cdFx0Y2xhc3M9XCJoZWFkZXJcIlxuXHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC01MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDk1MH19XG5cdD5cblx0XHQ8YVxuXHRcdFx0aHJlZj1cIi9cIlxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdD5cblx0XHRcdDxJY29uXG5cdFx0XHRcdHNyYz1cIi9pbmZvLnN2Z1wiXG5cdFx0XHRcdHc9XCI2XCJcblx0XHRcdD5cblx0XHRcdDwvSWNvbj5cblx0XHQ8L2E+XG5cblx0XHQ8aDEgY2xhc3M9XCJoZWFkZXJfX3RleHRcIj5cblx0XHRcdGNvbWF0ZVxuXHRcdDwvaDE+XG5cblx0XHQ8YnV0dG9uXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0XHRjbGFzczpoaWRkZW49eyEhdGltZXJ9XG5cdFx0XHRvbjpjbGljaz17aGFuZGxlRGV2TW9kZX1cblx0XHQ+XG5cdFx0XHR7I2lmICFkZXZNb2RlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jb2RlLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2Nsb2NrLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7L2lmfVxuXHRcdDwvYnV0dG9uPlxuXHQ8L2hlYWRlcj5cblxuXHQ8ZGl2PlxuXHRcdDxzcGFuXG5cdFx0XHRpbjpzY2FsZT17e29wYWNpdHk6IDAsIHN0YXJ0OiAwLjUsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAxMDAwfX1cblx0XHRcdGNsYXNzPVwidGltZVwiXG5cdFx0PlxuXHRcdFx0eyNpZiBkZXZNb2RlfVxuXHRcdFx0XHQ8c3BhblxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fc2Vjb25kc1wiXG5cdFx0XHRcdFx0aW46ZmFkZVxuXHRcdFx0XHQ+XG5cdFx0XHRcdFx0eyRtaW51dGVzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JHNlY29uZHN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PHNwYW4gaW46ZmFkZT5cblx0XHRcdFx0XHR7JGhvdXJzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JG1pbnV0ZXN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHsvaWZ9XG5cblx0XHRcdDxzdmcgY2xhc3M9XCJ0aW1lX19wcm9ncmVzc1wiPlxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kXCJcblx0XHRcdFx0XHRyPXsxMjUgLSAocHJvZ3Jlc3NXaWR0aCAvIDIpfVxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdGJpbmQ6dGhpcz17Y2lyY2xlfVxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtcmluZ1wiXG5cdFx0XHRcdFx0cj17MTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKX1cblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXHRcdFx0PC9zdmc+XG5cdFx0PC9zcGFuPlxuXG5cdFx0PGRpdiBjbGFzcz1cImF1ZGlvXCI+XG5cdFx0XHR7I2VhY2ggc291bmRzIGFzIHNvdW5kfVxuXHRcdFx0XHQ8QXVkaW9QbGF5ZXJcblx0XHRcdFx0XHR7Li4uc291bmR9XG5cdFx0XHRcdD5cblx0XHRcdFx0PC9BdWRpb1BsYXllcj5cblx0XHRcdHsvZWFjaH1cblxuXHRcdFx0PGJ1dHRvblxuXHRcdFx0XHRjbGFzcz1cImF1ZGlvX19idXR0b25cIlxuXHRcdFx0PlxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9hdWRpby5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9idXR0b24+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdHsjaWYgIXRpbWVyfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b24gb246Y2xpY2s9e2hhbmRsZVN0YXJ0fT5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlN0YXJ0IHNsZWVwIGN5Y2xlPC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3BsYXkuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTRcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7OmVsc2V9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvblxuXHRcdFx0XHRhbHRcblx0XHRcdFx0b246Y2xpY2s9e2hhbmRsZVJlc2V0fVxuXHRcdFx0PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+UmVzZXQ8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcmVzZXQuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7L2lmfVxuPC9tYWluPlxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXJnaW46IDAgYXV0bztcblx0XHRwYWRkaW5nOiAxNXB4IDIwcHggNTBweDtcblx0fVxuXG5cdC5oZWFkZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5oZWFkZXJfX2ljb24ge1xuXHRcdHdpZHRoOiAyNXB4O1xuXHRcdGhlaWdodDogMjVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1oaWdobGlnaHQtY29sb3IpO1xuXHR9XG5cblx0LmhlYWRlcl9fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAxNnB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdH1cblxuXHQuaGlkZGVuIHtcblx0XHRvcGFjaXR5OiAwO1xuXHRcdHZpc2liaWxpdHk6IGhpZGRlbjtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0fVxuXG5cdC50aW1lIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0d2lkdGg6IDI1MHB4O1xuXHRcdGhlaWdodDogMjUwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRmb250LXNpemU6IDYwcHg7XG5cdFx0dGV4dC1zaGFkb3c6IDAgMTVweCAzMHB4IHJnYmEoMCwgMCwgMCwgMC44KTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcyB7XG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRsZWZ0OiAwO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kLFxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlLXdpZHRoOiB2YXIoLS1wcm9ncmVzcy13aWR0aCk7XG5cdFx0ZmlsbDogdHJhbnNwYXJlbnQ7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yKTtcblxuXHRcdHRyYW5zaXRpb246IHN0cm9rZS1kYXNob2Zmc2V0IDAuM3MgZWFzZS1vdXQ7XG5cdFx0dHJhbnNmb3JtOiByb3RhdGUoLTkwZGVnKTtcblx0XHR0cmFuc2Zvcm0tb3JpZ2luOiBjZW50ZXI7XG5cdH1cblxuXHQudGltZV9fc2Vjb25kcyB7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuYXVkaW8ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cblx0LmF1ZGlvX19idXR0b24ge1xuXHRcdHdpZHRoOiAzMHB4O1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRtYXJnaW4tbGVmdDogMTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LnB1bHNlIHtcblx0XHRhbmltYXRpb246IGZsYXNoIDJzIGVhc2UtaW4gaW5maW5pdGU7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIGZsYXNoIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYxJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cdH1cbjwvc3R5bGU+IiwiaW1wb3J0IHsgd3JpdGFibGUsIGRlcml2ZWQgfSBmcm9tICdzdmVsdGUvc3RvcmUnO1xuXG5jb25zdCBUSU1FID0gMjg4MDAwMDA7IC8vIDggaG91cnMgaW4gbWlsbGlzZWNvbmRzXG5jb25zdCBERVZfVElNRSA9IDEwMDAwOyAvLyAxMCBzZWNvbmRzIGluIG1pbGxpc2Vjb25kc1xuXG5jb25zdCBsZWFkaW5nWmVybyA9ICh2YWx1ZSkgPT4ge1xuXHRyZXR1cm4gKCcwJyArIHZhbHVlKS5zbGljZSgtMik7XG59O1xuXG5jb25zdCBjcmVhdGVTdG9yZSA9ICgpID0+IHtcblx0Y29uc3QgeyBzdWJzY3JpYmUsIHNldCB9ID0gd3JpdGFibGUoVElNRSk7XG5cblx0Y29uc3QgaGFuZGxlUmVzZXQgPSAoaXNEZXYpID0+IHtcblx0XHRpZiAoaXNEZXYpIHtcblx0XHRcdHNldChERVZfVElNRSk7XG5cdFx0fSBlbHNlIHtcblx0XHRcdHNldChUSU1FKVxuXHRcdH1cblx0fVxuXG5cdGNvbnN0IGdldFRpbWUgPSAoaXNEZXYpID0+IHtcblx0XHRpZiAoaXNEZXYpIHtcblx0XHRcdHJldHVybiBERVZfVElNRTtcblx0XHR9IGVsc2Uge1xuXHRcdFx0cmV0dXJuIFRJTUU7XG5cdFx0fVxuXHR9XG5cblx0cmV0dXJuIHtcblx0XHRzdWJzY3JpYmUsXG5cdFx0cmVzZXQ6IGhhbmRsZVJlc2V0LFxuXHRcdHRpbWU6IGdldFRpbWVcblx0fVxufVxuXG5leHBvcnQgY29uc3QgZWxhcHNlZFRpbWUgPSBjcmVhdGVTdG9yZSgpO1xuXG5leHBvcnQgY29uc3QgaG91cnMgPSBkZXJpdmVkKGVsYXBzZWRUaW1lLCAkZWxhcHNlZFRpbWUgPT4gbGVhZGluZ1plcm8oTWF0aC5mbG9vcigoJGVsYXBzZWRUaW1lIC8gKDEwMDAgKiA2MCAqIDYwKSkgJSAyNCkpKTtcbmV4cG9ydCBjb25zdCBtaW51dGVzID0gZGVyaXZlZChlbGFwc2VkVGltZSwgJGVsYXBzZWRUaW1lID0+IGxlYWRpbmdaZXJvKE1hdGguZmxvb3IoKCRlbGFwc2VkVGltZSAvIDEwMDAgLyA2MCkgJSA2MCApKSk7XG5leHBvcnQgY29uc3Qgc2Vjb25kcyA9IGRlcml2ZWQoZWxhcHNlZFRpbWUsICRlbGFwc2VkVGltZSA9PiBsZWFkaW5nWmVybyhNYXRoLmZsb29yKCgkZWxhcHNlZFRpbWUgLyAxMDAwKSAlIDYwKSkpOyJdLCJzb3VyY2VSb290IjoiIn0=