(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["app"],{

/***/ "./src/data/sounds.js":
/*!****************************!*\
  !*** ./src/data/sounds.js ***!
  \****************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = ([
	{
		src: '/audio/sound1.mp3',
		title: 'Alane',
		maker: 'Robin Schulz & Wes'
	},
	{
		src: '/audio/sound2.mp3',
		title: 'Heat Waves',
		maker: 'Glass Animals'
	},
	{
		src: '/audio/sound3.mp3',
		title: 'Fairytale Gone Bad',
		maker: 'Sunrise Avenue'
	},
]);

/***/ }),

/***/ "./src/hooks/progress.js":
/*!*******************************!*\
  !*** ./src/hooks/progress.js ***!
  \*******************************/
/*! exports provided: progress, progressBackground */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "progress", function() { return progress; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "progressBackground", function() { return progressBackground; });
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");


const progress = (node) => {
	let circumference = 0;

	const progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue('--progress-width');

	circumference = node.r.baseVal.value * 2 * Math.PI;

	node.style.strokeDasharray = `${circumference} ${circumference}`;
	node.style.strokeDashoffset = 0;

	node.setAttribute('r', 125 - (progressWidth / 2));

	return {
		update({ time, devMode }) {
			console.log(time);
			const progress = 1 - (time / _store_timer_js__WEBPACK_IMPORTED_MODULE_0__["elapsedTime"].time(devMode));
			const offset = circumference * progress;
			node.style.strokeDashoffset = offset;
		}
	};
}

const progressBackground = (node) => {
	const progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue('--progress-width');

	node.setAttribute('r', 125 - (progressWidth / 2));
}

/***/ }),

/***/ "./src/routes/app.svelte":
/*!*******************************!*\
  !*** ./src/routes/app.svelte ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _capacitor_core__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @capacitor/core */ "./node_modules/@capacitor/core/dist/esm/index.js");
/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../components */ "./src/components/index.js");
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");
/* harmony import */ var _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../hooks/progress.js */ "./src/hooks/progress.js");
/* harmony import */ var _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../data/sounds.js */ "./src/data/sounds.js");
/* src/routes/app.svelte generated by Svelte v3.24.1 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];








const file = "src/routes/app.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-9n5j34-style";
	style.textContent = ".root.svelte-9n5j34{display:flex;flex-direction:column;justify-content:space-between;align-items:center;margin:0 auto;padding:15px 20px 50px}.header.svelte-9n5j34{display:flex;align-items:center;width:100%}.header__icon.svelte-9n5j34{width:25px;height:25px;display:flex;justify-content:center;align-items:center;color:var(--highlight-color)}.header__text.svelte-9n5j34{font-size:16px;font-weight:200;margin:0 auto}.hidden.svelte-9n5j34{opacity:0;visibility:hidden;pointer-events:none}.time.svelte-9n5j34{position:relative;width:250px;height:250px;display:flex;justify-content:center;align-items:center;font-size:60px;text-shadow:0 15px 30px rgba(0, 0, 0, 0.8)}.time__progress.svelte-9n5j34{position:absolute;top:0;left:0;width:100%;height:100%}.time__progress-background.svelte-9n5j34,.time__progress-ring.svelte-9n5j34{stroke-width:var(--progress-width);fill:transparent}.time__progress-background.svelte-9n5j34{stroke:var(--alternate-color-faded)}.time__progress-ring.svelte-9n5j34{stroke:var(--alternate-color);transition:stroke-dashoffset 0.3s ease-out;transform:rotate(-90deg);transform-origin:center}.time__seconds.svelte-9n5j34{color:var(--silver-color-faded)}.audio.svelte-9n5j34{display:flex;justify-content:center;align-items:center;margin-top:30px}.audio__button.svelte-9n5j34{width:30px;height:30px;margin-left:10px;display:flex;justify-content:center;align-items:center;color:var(--silver-color)}.pulse.svelte-9n5j34{animation:svelte-9n5j34-flash 2s ease-in infinite}@keyframes svelte-9n5j34-flash{0%{opacity:1}60%{opacity:1}61%{opacity:0}100%{opacity:0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXBwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiYXBwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5jb21hdGUg4oCSIHtkZXZNb2RlID8gJG1pbnV0ZXMgOiAkaG91cnN9OntkZXZNb2RlID8gJHNlY29uZHMgOiAkbWludXRlc308L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZhZGUsIGZseSwgc2NhbGUgfSBmcm9tICdzdmVsdGUvdHJhbnNpdGlvbic7XG5cdGltcG9ydCB7IGVsYXN0aWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgUGx1Z2lucyB9IGZyb20gJ0BjYXBhY2l0b3IvY29yZSc7XG5cdGltcG9ydCB7IEJ1dHRvbiwgSWNvbiwgQXVkaW9QbGF5ZXIgfSBmcm9tICcuLi9jb21wb25lbnRzJztcblx0aW1wb3J0IHsgZWxhcHNlZFRpbWUsIGhvdXJzLCBtaW51dGVzLCBzZWNvbmRzIH0gZnJvbSAnLi4vc3RvcmUvdGltZXIuanMnO1xuXHRpbXBvcnQgeyBwcm9ncmVzcywgcHJvZ3Jlc3NCYWNrZ3JvdW5kIH0gZnJvbSAnLi4vaG9va3MvcHJvZ3Jlc3MuanMnO1xuXHRpbXBvcnQgc291bmRzIGZyb20gJy4uL2RhdGEvc291bmRzLmpzJztcblxuXHRjb25zdCB7IEhhcHRpY3MsIExvY2FsTm90aWZpY2F0aW9ucywgVG9hc3QgfSA9IFBsdWdpbnM7XG5cblx0bGV0IHRpbWVyID0gbnVsbDtcblx0bGV0IGRldk1vZGUgPSBmYWxzZTtcblxuXHQkOiBlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblxuXHRvbk1vdW50KGFzeW5jKCkgPT4ge1xuXHRcdGF3YWl0IExvY2FsTm90aWZpY2F0aW9ucy5yZXF1ZXN0UGVybWlzc2lvbigpO1xuXHR9KTtcblxuXHRjb25zdCBoYW5kbGVTdGFydCA9ICgpID0+IHtcblx0XHR0aW1lciA9IHNldEludGVydmFsKCgpID0+IHtcblx0XHRcdGVsYXBzZWRUaW1lLnVwZGF0ZSh0aW1lID0+IHRpbWUgLSAxMDAwKTtcblxuXHRcdFx0aWYgKCRlbGFwc2VkVGltZSA8PSAwKSB7XG5cdFx0XHRcdGhhbmRsZVJlc2V0KCk7XG5cdFx0XHRcdGhhbmRsZVN0b3AoKTtcblx0XHRcdH1cblx0XHR9LCAxMDAwKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0b3AgPSBhc3luYygpID0+IHtcblx0XHRhd2FpdCBMb2NhbE5vdGlmaWNhdGlvbnMuc2NoZWR1bGUoe1xuXHRcdFx0bm90aWZpY2F0aW9uczogW1xuXHRcdFx0ICB7XG5cdFx0XHRcdHRpdGxlOiBcIldha2UgdXAhXCIsXG5cdFx0XHRcdGJvZHk6IFwiQSBsb3ZlbHkgZGF5IGlzIHdhaXRpbmcgZm9yIHlvdS5cIixcblx0XHRcdFx0aWQ6IDEsXG5cdFx0XHQgIH1cblx0XHRcdF1cblx0XHR9KTtcblxuXHRcdGF1ZGlvLnBsYXkoKTtcblxuXHRcdEhhcHRpY3MudmlicmF0ZSgpO1xuXG5cdFx0Y29uc29sZS5sb2coJ3BsYXkgc291bmQnKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVJlc2V0ID0gKCkgPT4ge1xuXHRcdGNsZWFySW50ZXJ2YWwodGltZXIpO1xuXG5cdFx0ZWxhcHNlZFRpbWUucmVzZXQoZGV2TW9kZSk7XG5cdFx0dGltZXIgPSBudWxsO1xuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNob2Zmc2V0ID0gMDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZURldk1vZGUgPSBhc3luYygpID0+IHtcblx0XHRkZXZNb2RlID0gIWRldk1vZGU7XG5cblx0XHRhd2FpdCBUb2FzdC5zaG93KHtcblx0XHRcdHRleHQ6IGRldk1vZGUgPyAnREVWIG1vZGUgZW5hYmxlZCcgOiAnREVWIG1vZGUgZGlzYWJsZWQnLFxuXHRcdFx0cG9zaXRpb246ICd0b3AnXG5cdFx0fSk7XG5cdH1cbjwvc2NyaXB0PlxuXG48bWFpbiBjbGFzcz1cInJvb3RcIj5cblx0PGhlYWRlclxuXHRcdGNsYXNzPVwiaGVhZGVyXCJcblx0XHRpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAtNTAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiA5NTB9fVxuXHQ+XG5cdFx0PGFcblx0XHRcdGhyZWY9XCIvXCJcblx0XHRcdGNsYXNzPVwiaGVhZGVyX19pY29uXCJcblx0XHQ+XG5cdFx0XHQ8SWNvblxuXHRcdFx0XHRzcmM9XCIvaW5mby5zdmdcIlxuXHRcdFx0XHR3PVwiNlwiXG5cdFx0XHQ+XG5cdFx0XHQ8L0ljb24+XG5cdFx0PC9hPlxuXG5cdFx0PGgxIGNsYXNzPVwiaGVhZGVyX190ZXh0XCI+XG5cdFx0XHRjb21hdGVcblx0XHQ8L2gxPlxuXG5cdFx0PGJ1dHRvblxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdFx0Y2xhc3M6aGlkZGVuPXshIXRpbWVyfVxuXHRcdFx0b246Y2xpY2s9e2hhbmRsZURldk1vZGV9XG5cdFx0PlxuXHRcdFx0eyNpZiAhZGV2TW9kZX1cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvY29kZS5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxOFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0ezplbHNlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jbG9jay5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxOFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0ey9pZn1cblx0XHQ8L2J1dHRvbj5cblx0PC9oZWFkZXI+XG5cblx0PGRpdj5cblx0XHQ8c3BhblxuXHRcdFx0aW46c2NhbGU9e3tvcGFjaXR5OiAwLCBzdGFydDogMC41LCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMTAwMH19XG5cdFx0XHRjbGFzcz1cInRpbWVcIlxuXHRcdD5cblx0XHRcdHsjaWYgZGV2TW9kZX1cblx0XHRcdFx0PHNwYW5cblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3NlY29uZHNcIlxuXHRcdFx0XHRcdGluOmZhZGVcblx0XHRcdFx0PlxuXHRcdFx0XHRcdHskbWludXRlc308c3BhbiBjbGFzczpwdWxzZT17dGltZXJ9Pjo8L3NwYW4+eyRzZWNvbmRzfVxuXHRcdFx0XHQ8L3NwYW4+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxzcGFuIGluOmZhZGU+XG5cdFx0XHRcdFx0eyRob3Vyc308c3BhbiBjbGFzczpwdWxzZT17dGltZXJ9Pjo8L3NwYW4+eyRtaW51dGVzfVxuXHRcdFx0XHQ8L3NwYW4+XG5cdFx0XHR7L2lmfVxuXG5cdFx0XHQ8c3ZnIGNsYXNzPVwidGltZV9fcHJvZ3Jlc3NcIj5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdHVzZTpwcm9ncmVzc0JhY2tncm91bmRcblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3Byb2dyZXNzLWJhY2tncm91bmRcIlxuXHRcdFx0XHRcdHI9XCIxMjVcIlxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdHVzZTpwcm9ncmVzcz17e1xuXHRcdFx0XHRcdFx0dGltZTogJGVsYXBzZWRUaW1lLFxuXHRcdFx0XHRcdFx0ZGV2TW9kZVxuXHRcdFx0XHRcdH19XG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19wcm9ncmVzcy1yaW5nXCJcblx0XHRcdFx0XHRyPVwiMTI1XCJcblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXHRcdFx0PC9zdmc+XG5cdFx0PC9zcGFuPlxuXG5cdFx0PGRpdiBjbGFzcz1cImF1ZGlvXCI+XG5cdFx0XHR7I2VhY2ggc291bmRzIGFzIHNvdW5kfVxuXHRcdFx0XHQ8QXVkaW9QbGF5ZXJcblx0XHRcdFx0XHR7Li4uc291bmR9XG5cdFx0XHRcdD5cblx0XHRcdFx0PC9BdWRpb1BsYXllcj5cblx0XHRcdHsvZWFjaH1cblxuXHRcdFx0PGJ1dHRvblxuXHRcdFx0XHRjbGFzcz1cImF1ZGlvX19idXR0b25cIlxuXHRcdFx0PlxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9hdWRpby5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9idXR0b24+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdHsjaWYgIXRpbWVyfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b24gb246Y2xpY2s9e2hhbmRsZVN0YXJ0fT5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlN0YXJ0IHNsZWVwIGN5Y2xlPC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3BsYXkuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTRcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7OmVsc2V9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvblxuXHRcdFx0XHRhbHRcblx0XHRcdFx0b246Y2xpY2s9e2hhbmRsZVJlc2V0fVxuXHRcdFx0PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+UmVzZXQ8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcmVzZXQuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7L2lmfVxuPC9tYWluPlxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXJnaW46IDAgYXV0bztcblx0XHRwYWRkaW5nOiAxNXB4IDIwcHggNTBweDtcblx0fVxuXG5cdC5oZWFkZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5oZWFkZXJfX2ljb24ge1xuXHRcdHdpZHRoOiAyNXB4O1xuXHRcdGhlaWdodDogMjVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1oaWdobGlnaHQtY29sb3IpO1xuXHR9XG5cblx0LmhlYWRlcl9fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAxNnB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdH1cblxuXHQuaGlkZGVuIHtcblx0XHRvcGFjaXR5OiAwO1xuXHRcdHZpc2liaWxpdHk6IGhpZGRlbjtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0fVxuXG5cdC50aW1lIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0d2lkdGg6IDI1MHB4O1xuXHRcdGhlaWdodDogMjUwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRmb250LXNpemU6IDYwcHg7XG5cdFx0dGV4dC1zaGFkb3c6IDAgMTVweCAzMHB4IHJnYmEoMCwgMCwgMCwgMC44KTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcyB7XG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRsZWZ0OiAwO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kLFxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlLXdpZHRoOiB2YXIoLS1wcm9ncmVzcy13aWR0aCk7XG5cdFx0ZmlsbDogdHJhbnNwYXJlbnQ7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yKTtcblxuXHRcdHRyYW5zaXRpb246IHN0cm9rZS1kYXNob2Zmc2V0IDAuM3MgZWFzZS1vdXQ7XG5cdFx0dHJhbnNmb3JtOiByb3RhdGUoLTkwZGVnKTtcblx0XHR0cmFuc2Zvcm0tb3JpZ2luOiBjZW50ZXI7XG5cdH1cblxuXHQudGltZV9fc2Vjb25kcyB7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuYXVkaW8ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cblx0LmF1ZGlvX19idXR0b24ge1xuXHRcdHdpZHRoOiAzMHB4O1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRtYXJnaW4tbGVmdDogMTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LnB1bHNlIHtcblx0XHRhbmltYXRpb246IGZsYXNoIDJzIGVhc2UtaW4gaW5maW5pdGU7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIGZsYXNoIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYxJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cdH1cbjwvc3R5bGU+Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQTRNQyxLQUFLLGNBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsZUFBZSxDQUFFLGFBQWEsQ0FDOUIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxBQUN4QixDQUFDLEFBRUQsT0FBTyxjQUFDLENBQUMsQUFDUixPQUFPLENBQUUsSUFBSSxDQUNiLFdBQVcsQ0FBRSxNQUFNLENBQ25CLEtBQUssQ0FBRSxJQUFJLEFBQ1osQ0FBQyxBQUVELGFBQWEsY0FBQyxDQUFDLEFBQ2QsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUVaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsS0FBSyxDQUFFLElBQUksaUJBQWlCLENBQUMsQUFDOUIsQ0FBQyxBQUVELGFBQWEsY0FBQyxDQUFDLEFBQ2QsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsR0FBRyxDQUNoQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDZixDQUFDLEFBRUQsT0FBTyxjQUFDLENBQUMsQUFDUixPQUFPLENBQUUsQ0FBQyxDQUNWLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLGNBQWMsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFFRCxLQUFLLGNBQUMsQ0FBQyxBQUNOLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQ0FFYixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLFNBQVMsQ0FBRSxJQUFJLENBQ2YsV0FBVyxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLEFBQzVDLENBQUMsQUFFRCxlQUFlLGNBQUMsQ0FBQyxBQUNoQixRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsQ0FBQyxDQUNOLElBQUksQ0FBRSxDQUFDLENBQ1AsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxBQUNiLENBQUMsQUFFRCx3Q0FBMEIsQ0FDMUIsb0JBQW9CLGNBQUMsQ0FBQyxBQUNyQixZQUFZLENBQUUsSUFBSSxnQkFBZ0IsQ0FBQyxDQUNuQyxJQUFJLENBQUUsV0FBVyxBQUNsQixDQUFDLEFBRUQsMEJBQTBCLGNBQUMsQ0FBQyxBQUMzQixNQUFNLENBQUUsSUFBSSx1QkFBdUIsQ0FBQyxBQUNyQyxDQUFDLEFBRUQsb0JBQW9CLGNBQUMsQ0FBQyxBQUNyQixNQUFNLENBQUUsSUFBSSxpQkFBaUIsQ0FBQyxDQUU5QixVQUFVLENBQUUsaUJBQWlCLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FDM0MsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLENBQ3pCLGdCQUFnQixDQUFFLE1BQU0sQUFDekIsQ0FBQyxBQUVELGNBQWMsY0FBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksb0JBQW9CLENBQUMsQUFDakMsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUNuQixVQUFVLENBQUUsSUFBSSxBQUNqQixDQUFDLEFBRUQsY0FBYyxjQUFDLENBQUMsQUFDZixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osV0FBVyxDQUFFLElBQUksQ0FFakIsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUVuQixLQUFLLENBQUUsSUFBSSxjQUFjLENBQUMsQUFDM0IsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLG1CQUFLLENBQUMsRUFBRSxDQUFDLE9BQU8sQ0FBQyxRQUFRLEFBQ3JDLENBQUMsQUFFRCxXQUFXLG1CQUFNLENBQUMsQUFDakIsRUFBRSxBQUFDLENBQUMsQUFDSCxPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxHQUFHLEFBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxDQUFDLEFBQ1gsQ0FBQyxBQUVELEdBQUcsQUFBQyxDQUFDLEFBQ0osT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsSUFBSSxBQUFDLENBQUMsQUFDTCxPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFDRixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[13] = list[i];
	return child_ctx;
}

// (104:3) {:else}
function create_else_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/clock.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_2.name,
		type: "else",
		source: "(104:3) {:else}",
		ctx
	});

	return block;
}

// (98:3) {#if !devMode}
function create_if_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/code.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(98:3) {#if !devMode}",
		ctx
	});

	return block;
}

// (126:3) {:else}
function create_else_block_1(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$hours*/ ctx[4]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[3]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", {});
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$hours*/ ctx[4]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[3]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 127, 13, 2413);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 126, 4, 2385);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$hours*/ 16) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$hours*/ ctx[4]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$minutes*/ 8) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$minutes*/ ctx[3]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_1.name,
		type: "else",
		source: "(126:3) {:else}",
		ctx
	});

	return block;
}

// (119:3) {#if devMode}
function create_if_block_1(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[3]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$seconds*/ ctx[5]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[3]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$seconds*/ ctx[5]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 123, 15, 2313);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "time__seconds svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 119, 4, 2246);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$minutes*/ 8) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$minutes*/ ctx[3]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$seconds*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$seconds*/ ctx[5]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(119:3) {#if devMode}",
		ctx
	});

	return block;
}

// (155:3) {#each sounds as sound}
function create_each_block(ctx) {
	let audioplayer;
	let current;
	const audioplayer_spread_levels = [/*sound*/ ctx[13]];
	let audioplayer_props = {};

	for (let i = 0; i < audioplayer_spread_levels.length; i += 1) {
		audioplayer_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(audioplayer_props, audioplayer_spread_levels[i]);
	}

	audioplayer = new _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"]({ props: audioplayer_props, $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(audioplayer.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(audioplayer.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(audioplayer, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const audioplayer_changes = (dirty & /*sounds*/ 0)
			? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(audioplayer_spread_levels, [Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_object"])(/*sound*/ ctx[13])])
			: {};

			if (dirty & /*$$scope*/ 65536) {
				audioplayer_changes.$$scope = { dirty, ctx };
			}

			audioplayer.$set(audioplayer_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(audioplayer.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(audioplayer.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(audioplayer, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(155:3) {#each sounds as sound}",
		ctx
	});

	return block;
}

// (186:1) {:else}
function create_else_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				alt: true,
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleReset*/ ctx[7]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 186, 2, 3364);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(186:1) {:else}",
		ctx
	});

	return block;
}

// (174:1) {#if !timer}
function create_if_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleStart*/ ctx[6]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 174, 2, 3093);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(174:1) {#if !timer}",
		ctx
	});

	return block;
}

// (188:3) <Button     alt     on:click={handleReset}    >
function create_default_slot_2(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/reset.svg", w: "16" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Reset");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Reset");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 191, 4, 3502);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(188:3) <Button     alt     on:click={handleReset}    >",
		ctx
	});

	return block;
}

// (176:3) <Button on:click={handleStart}>
function create_default_slot(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/play.svg", w: "14" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Start sleep cycle");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Start sleep cycle");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 176, 4, 3215);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(176:3) <Button on:click={handleStart}>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let main;
	let header;
	let a;
	let icon0;
	let t1;
	let h1;
	let t2;
	let t3;
	let button0;
	let current_block_type_index;
	let if_block0;
	let header_intro;
	let t4;
	let div1;
	let span;
	let t5;
	let svg;
	let circle0;
	let progressBackground_action;
	let circle1;
	let progress_action;
	let span_intro;
	let t6;
	let div0;
	let t7;
	let button1;
	let icon1;
	let t8;
	let current_block_type_index_1;
	let if_block2;
	let current;
	let mounted;
	let dispose;

	document.title = title_value = "comate ‒ " + (/*devMode*/ ctx[1]
	? /*$minutes*/ ctx[3]
	: /*$hours*/ ctx[4]) + ":" + (/*devMode*/ ctx[1]
	? /*$seconds*/ ctx[5]
	: /*$minutes*/ ctx[3]);

	icon0 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/info.svg", w: "6" },
			$$inline: true
		});

	const if_block_creators = [create_if_block_2, create_else_block_2];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (!/*devMode*/ ctx[1]) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	function select_block_type_1(ctx, dirty) {
		if (/*devMode*/ ctx[1]) return create_if_block_1;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_1(ctx, -1);
	let if_block1 = current_block_type(ctx);
	let each_value = _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	icon1 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/audio.svg", w: "16" },
			$$inline: true
		});

	const if_block_creators_1 = [create_if_block, create_else_block];
	const if_blocks_1 = [];

	function select_block_type_2(ctx, dirty) {
		if (!/*timer*/ ctx[0]) return 0;
		return 1;
	}

	current_block_type_index_1 = select_block_type_2(ctx, -1);
	if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon0.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("comate");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon1.$$.fragment);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if_block2.c();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1rk5ch9\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "HEADER", { class: true });
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "A", { href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon0.$$.fragment, a_nodes);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "comate");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "BUTTON", { class: true });
			var button0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button0);
			if_block0.l(button0_nodes);
			button0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			if_block1.l(span_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "svg", { class: true }, 1);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div0_nodes);
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon1.$$.fragment, button1_nodes);
			button1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			if_block2.l(main_nodes);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 77, 2, 1672);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "header__text svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 88, 2, 1780);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button0, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button0, file, 92, 2, 1827);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(header, "class", "header svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 73, 1, 1562);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "class", "time__progress-background svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle0, file, 132, 4, 2516);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "class", "time__progress-ring svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle1, file, 140, 4, 2644);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "class", "time__progress svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 131, 3, 2483);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "time svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 114, 2, 2111);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button1, "class", "audio__button svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button1, file, 161, 3, 2945);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "audio svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 153, 2, 2825);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 113, 1, 2103);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "class", "root svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 72, 0, 1541);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon0, a, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, button0);
			if_blocks[current_block_type_index].m(button0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, span);
			if_block1.m(span, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon1, button1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t8);
			if_blocks_1[current_block_type_index_1].m(main, null);
			current = true;

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button0, "click", /*handleDevMode*/ ctx[8], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["action_destroyer"])(progressBackground_action = _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progressBackground"].call(null, circle0)),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["action_destroyer"])(progress_action = _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progress"].call(null, circle1, {
						time: /*$elapsedTime*/ ctx[2],
						devMode: /*devMode*/ ctx[1]
					}))
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if ((!current || dirty & /*devMode, $minutes, $hours, $seconds*/ 58) && title_value !== (title_value = "comate ‒ " + (/*devMode*/ ctx[1]
			? /*$minutes*/ ctx[3]
			: /*$hours*/ ctx[4]) + ":" + (/*devMode*/ ctx[1]
			? /*$seconds*/ ctx[5]
			: /*$minutes*/ ctx[3]))) {
				document.title = title_value;
			}

			const icon0_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				icon0_changes.$$scope = { dirty, ctx };
			}

			icon0.$set(icon0_changes);
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index !== previous_block_index) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block0 = if_blocks[current_block_type_index];

				if (!if_block0) {
					if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block0.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
				if_block0.m(button0, null);
			}

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			}

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block1) {
				if_block1.p(ctx, dirty);
			} else {
				if_block1.d(1);
				if_block1 = current_block_type(ctx);

				if (if_block1) {
					if_block1.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					if_block1.m(span, t5);
				}
			}

			if (progress_action && Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(progress_action.update) && dirty & /*$elapsedTime, devMode*/ 6) progress_action.update.call(null, {
				time: /*$elapsedTime*/ ctx[2],
				devMode: /*devMode*/ ctx[1]
			});

			if (dirty & /*sounds*/ 0) {
				each_value = _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(div0, t7);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			const icon1_changes = {};

			if (dirty & /*$$scope*/ 65536) {
				icon1_changes.$$scope = { dirty, ctx };
			}

			icon1.$set(icon1_changes);
			let previous_block_index_1 = current_block_type_index_1;
			current_block_type_index_1 = select_block_type_2(ctx, dirty);

			if (current_block_type_index_1 === previous_block_index_1) {
				if_blocks_1[current_block_type_index_1].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks_1[previous_block_index_1], 1, 1, () => {
					if_blocks_1[previous_block_index_1] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block2 = if_blocks_1[current_block_type_index_1];

				if (!if_block2) {
					if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);
					if_block2.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2, 1);
				if_block2.m(main, null);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0);

			if (!header_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					header_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(header, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: -50,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 950
					});

					header_intro.start();
				});
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1);

			if (!span_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"], {
						opacity: 0,
						start: 0.5,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 1000
					});

					span_intro.start();
				});
			}

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0);
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block2);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon0);
			if_blocks[current_block_type_index].d();
			if_block1.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon1);
			if_blocks_1[current_block_type_index_1].d();
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $elapsedTime;
	let $minutes;
	let $hours;
	let $seconds;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], "elapsedTime");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], $$value => $$invalidate(2, $elapsedTime = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], "minutes");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], $$value => $$invalidate(3, $minutes = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], "hours");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], $$value => $$invalidate(4, $hours = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], "seconds");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], $$value => $$invalidate(5, $seconds = $$value));
	const { Haptics, LocalNotifications, Toast } = _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"];
	let timer = null;
	let devMode = false;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await LocalNotifications.requestPermission();
	});

	const handleStart = () => {
		$$invalidate(0, timer = setInterval(
			() => {
				_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].update(time => time - 1000);

				if ($elapsedTime <= 0) {
					handleReset();
					handleStop();
				}
			},
			1000
		));
	};

	const handleStop = async () => {
		await LocalNotifications.schedule({
			notifications: [
				{
					title: "Wake up!",
					body: "A lovely day is waiting for you.",
					id: 1
				}
			]
		});

		audio.play();
		Haptics.vibrate();
		console.log("play sound");
	};

	const handleReset = () => {
		clearInterval(timer);
		_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		$$invalidate(0, timer = null);
		circle.style.strokeDashoffset = 0;
	};

	const handleDevMode = async () => {
		$$invalidate(1, devMode = !devMode);

		await Toast.show({
			text: devMode ? "DEV mode enabled" : "DEV mode disabled",
			position: "top"
		});
	};

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<App> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("App", $$slots, []);

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"],
		scale: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"],
		elasticOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
		Plugins: _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"],
		Button: _components__WEBPACK_IMPORTED_MODULE_5__["Button"],
		Icon: _components__WEBPACK_IMPORTED_MODULE_5__["Icon"],
		AudioPlayer: _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"],
		elapsedTime: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"],
		hours: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"],
		minutes: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"],
		seconds: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"],
		progress: _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progress"],
		progressBackground: _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progressBackground"],
		sounds: _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"],
		Haptics,
		LocalNotifications,
		Toast,
		timer,
		devMode,
		handleStart,
		handleStop,
		handleReset,
		handleDevMode,
		$elapsedTime,
		$minutes,
		$hours,
		$seconds
	});

	$$self.$inject_state = $$props => {
		if ("timer" in $$props) $$invalidate(0, timer = $$props.timer);
		if ("devMode" in $$props) $$invalidate(1, devMode = $$props.devMode);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*devMode*/ 2) {
			$: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		}
	};

	return [
		timer,
		devMode,
		$elapsedTime,
		$minutes,
		$hours,
		$seconds,
		handleStart,
		handleReset,
		handleDevMode
	];
}

class App extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-9n5j34-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (App);

/***/ }),

/***/ "./src/store/timer.js":
/*!****************************!*\
  !*** ./src/store/timer.js ***!
  \****************************/
/*! exports provided: elapsedTime, hours, minutes, seconds */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "elapsedTime", function() { return elapsedTime; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "hours", function() { return hours; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "minutes", function() { return minutes; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "seconds", function() { return seconds; });
/* harmony import */ var svelte_store__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/store */ "./node_modules/svelte/store/index.mjs");


const TIME = 28800000; // 8 hours in milliseconds
const DEV_TIME = 10000; // 10 seconds in milliseconds

const leadingZero = (value) => {
	return ('0' + value).slice(-2);
};

const createStore = () => {
	const { subscribe, set, update } = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["writable"])(TIME);

	const handleReset = (isDev) => {
		if (isDev) {
			set(DEV_TIME);
		} else {
			set(TIME)
		}
	}

	const getTime = (isDev) => {
		if (isDev) {
			return DEV_TIME;
		} else {
			return TIME;
		}
	}

	return {
		subscribe,
		update,
		reset: handleReset,
		time: getTime
	}
}

const elapsedTime = createStore();

const hours = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / (1000 * 60 * 60)) % 24)));
const minutes = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000 / 60) % 60 )));
const seconds = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000) % 60)));

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvZGF0YS9zb3VuZHMuanMiLCJ3ZWJwYWNrOi8vLy4vc3JjL2hvb2tzL3Byb2dyZXNzLmpzIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvYXBwLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvc3RvcmUvdGltZXIuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztBQUFBO0FBQWU7QUFDZjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRixDOzs7Ozs7Ozs7Ozs7QUNoQkE7QUFBQTtBQUFBO0FBQUE7QUFBZ0Q7O0FBRXpDO0FBQ1A7O0FBRUE7O0FBRUE7O0FBRUEsaUNBQWlDLGNBQWMsR0FBRyxjQUFjO0FBQ2hFOztBQUVBOztBQUVBO0FBQ0EsVUFBVSxnQkFBZ0I7QUFDMUI7QUFDQSxnQ0FBZ0MsMkRBQVc7QUFDM0M7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFTztBQUNQOztBQUVBO0FBQ0EsQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN2QmtDO0FBQ29CO0FBQ1Y7QUFDRDtBQUNnQjtBQUNlO0FBQ0w7QUFDN0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnRkFtSGxDLEdBQU07OztrRkFBb0MsR0FBUTs7Ozs7O21HQUFsRCxHQUFNOzs7OztxR0FBb0MsR0FBUTs7Ozs7O2tHQUF4QixHQUFLOzs7Ozs7Ozs7Ozs7a0hBQS9CLEdBQU07OzttR0FBb0IsR0FBSzs7O3FIQUFXLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrRkFKbEQsR0FBUTs7O2tGQUFvQyxHQUFROzs7Ozs7cUdBQXBELEdBQVE7Ozs7O3FHQUFvQyxHQUFROzs7Ozs7a0dBQXhCLEdBQUs7Ozs7Ozs7Ozs7Ozs7cUhBQWpDLEdBQVE7OzttR0FBb0IsR0FBSzs7O3NIQUFXLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OENBaUNqRCxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytMQUFMLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FDQWlDQSxHQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUFIVCxPQUFPLEVBQUUsQ0FBQztNQUFFLENBQUMsRUFBRSxFQUFFO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FDQVg1RCxHQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUFEaEIsT0FBTyxFQUFFLENBQUM7TUFBRSxDQUFDLEVBQUUsRUFBRTtNQUFFLE1BQU0sRUFBRSx3REFBVTtNQUFFLFFBQVEsRUFBRSxJQUFJO01BQUUsS0FBSyxFQUFFLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzJEQTdLL0QsR0FBTztnQkFBRyxHQUFRO2NBQUcsR0FBTSwwQkFBRyxHQUFPO2dCQUFHLEdBQVE7Z0JBQUcsR0FBUTs7Ozs7Ozs7Ozs7bUJBZ0dwRSxHQUFPOzs7Ozs7OztrQkFxQlIsR0FBTzs7Ozs7O2tCQW9DTCx1REFBTTs7OztnQ0FBWCxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7OztpQkFtQkYsR0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUdBL0VPLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRHQUNYLEdBQWE7OztNQStDcEIsSUFBSSxtQkFBRSxHQUFZO01BQ2xCLE9BQU8sY0FBUCxHQUFPOzs7Ozs7OztxSUE5SUssR0FBTztrQkFBRyxHQUFRO2dCQUFHLEdBQU0sMEJBQUcsR0FBTztrQkFBRyxHQUFRO2tCQUFHLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0dBNkYxRCxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7OztJQWdEbEIsSUFBSSxtQkFBRSxHQUFZO0lBQ2xCLE9BQU8sY0FBUCxHQUFPOzs7O2lCQVdILHVEQUFNOzs7OytCQUFYLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7d0JBQUosTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQS9FRSxPQUFPLEVBQUUsQ0FBQztNQUFFLENBQUMsR0FBRyxFQUFFO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7O01Bd0MvRCxPQUFPLEVBQUUsQ0FBQztNQUFFLEtBQUssRUFBRSxHQUFHO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsSUFBSTs7Ozs7OztrQ0F1Q2hGLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O1NBNUlBLE9BQU8sRUFBRSxrQkFBa0IsRUFBRSxLQUFLLEtBQUssdURBQU87S0FFbEQsS0FBSyxHQUFHLElBQUk7S0FDWixPQUFPLEdBQUcsS0FBSzs7Q0FJbkIsc0RBQU87UUFDQSxrQkFBa0IsQ0FBQyxpQkFBaUI7OztPQUdyQyxXQUFXO2tCQUNoQixLQUFLLEdBQUcsV0FBVzs7SUFDbEIsMkRBQVcsQ0FBQyxNQUFNLENBQUMsSUFBSSxJQUFJLElBQUksR0FBRyxJQUFJOztRQUVsQyxZQUFZLElBQUksQ0FBQztLQUNwQixXQUFXO0tBQ1gsVUFBVTs7O0dBRVQsSUFBSTs7OztPQUdGLFVBQVU7UUFDVCxrQkFBa0IsQ0FBQyxRQUFRO0dBQ2hDLGFBQWE7O0tBRVosS0FBSyxFQUFFLFVBQVU7S0FDakIsSUFBSSxFQUFFLGtDQUFrQztLQUN4QyxFQUFFLEVBQUUsQ0FBQzs7Ozs7RUFLUCxLQUFLLENBQUMsSUFBSTtFQUVWLE9BQU8sQ0FBQyxPQUFPO0VBRWYsT0FBTyxDQUFDLEdBQUcsQ0FBQyxZQUFZOzs7T0FHbkIsV0FBVztFQUNoQixhQUFhLENBQUMsS0FBSztFQUVuQiwyREFBVyxDQUFDLEtBQUssQ0FBQyxPQUFPO2tCQUN6QixLQUFLLEdBQUcsSUFBSTtFQUNaLE1BQU0sQ0FBQyxLQUFLLENBQUMsZ0JBQWdCLEdBQUcsQ0FBQzs7O09BRzVCLGFBQWE7a0JBQ2xCLE9BQU8sSUFBSSxPQUFPOztRQUVaLEtBQUssQ0FBQyxJQUFJO0dBQ2YsSUFBSSxFQUFFLE9BQU8sR0FBRyxrQkFBa0IsR0FBRyxtQkFBbUI7R0FDeEQsUUFBUSxFQUFFLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBaERqQixDQUFDLEVBQUUsMkRBQVcsQ0FBQyxLQUFLLENBQUMsT0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNuQjdCO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFpRDs7QUFFakQsc0JBQXNCO0FBQ3RCLHVCQUF1Qjs7QUFFdkI7QUFDQTtBQUNBOztBQUVBO0FBQ0EsUUFBUSx5QkFBeUIsR0FBRyw2REFBUTs7QUFFNUM7QUFDQTtBQUNBO0FBQ0EsR0FBRztBQUNIO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQSxHQUFHO0FBQ0g7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVPOztBQUVBLGNBQWMsNERBQU87QUFDckIsZ0JBQWdCLDREQUFPO0FBQ3ZCLGdCQUFnQiw0REFBTyxtRiIsImZpbGUiOiJjMjczMjBkMmU1YWUwODNkZGFlZi9hcHAuYXBwLmpzIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQgW1xuXHR7XG5cdFx0c3JjOiAnL2F1ZGlvL3NvdW5kMS5tcDMnLFxuXHRcdHRpdGxlOiAnQWxhbmUnLFxuXHRcdG1ha2VyOiAnUm9iaW4gU2NodWx6ICYgV2VzJ1xuXHR9LFxuXHR7XG5cdFx0c3JjOiAnL2F1ZGlvL3NvdW5kMi5tcDMnLFxuXHRcdHRpdGxlOiAnSGVhdCBXYXZlcycsXG5cdFx0bWFrZXI6ICdHbGFzcyBBbmltYWxzJ1xuXHR9LFxuXHR7XG5cdFx0c3JjOiAnL2F1ZGlvL3NvdW5kMy5tcDMnLFxuXHRcdHRpdGxlOiAnRmFpcnl0YWxlIEdvbmUgQmFkJyxcblx0XHRtYWtlcjogJ1N1bnJpc2UgQXZlbnVlJ1xuXHR9LFxuXSIsImltcG9ydCB7IGVsYXBzZWRUaW1lIH0gZnJvbSAnLi4vc3RvcmUvdGltZXIuanMnO1xuXG5leHBvcnQgY29uc3QgcHJvZ3Jlc3MgPSAobm9kZSkgPT4ge1xuXHRsZXQgY2lyY3VtZmVyZW5jZSA9IDA7XG5cblx0Y29uc3QgcHJvZ3Jlc3NXaWR0aCA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuZ2V0UHJvcGVydHlWYWx1ZSgnLS1wcm9ncmVzcy13aWR0aCcpO1xuXG5cdGNpcmN1bWZlcmVuY2UgPSBub2RlLnIuYmFzZVZhbC52YWx1ZSAqIDIgKiBNYXRoLlBJO1xuXG5cdG5vZGUuc3R5bGUuc3Ryb2tlRGFzaGFycmF5ID0gYCR7Y2lyY3VtZmVyZW5jZX0gJHtjaXJjdW1mZXJlbmNlfWA7XG5cdG5vZGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IDA7XG5cblx0bm9kZS5zZXRBdHRyaWJ1dGUoJ3InLCAxMjUgLSAocHJvZ3Jlc3NXaWR0aCAvIDIpKTtcblxuXHRyZXR1cm4ge1xuXHRcdHVwZGF0ZSh7IHRpbWUsIGRldk1vZGUgfSkge1xuXHRcdFx0Y29uc29sZS5sb2codGltZSk7XG5cdFx0XHRjb25zdCBwcm9ncmVzcyA9IDEgLSAodGltZSAvIGVsYXBzZWRUaW1lLnRpbWUoZGV2TW9kZSkpO1xuXHRcdFx0Y29uc3Qgb2Zmc2V0ID0gY2lyY3VtZmVyZW5jZSAqIHByb2dyZXNzO1xuXHRcdFx0bm9kZS5zdHlsZS5zdHJva2VEYXNob2Zmc2V0ID0gb2Zmc2V0O1xuXHRcdH1cblx0fTtcbn1cblxuZXhwb3J0IGNvbnN0IHByb2dyZXNzQmFja2dyb3VuZCA9IChub2RlKSA9PiB7XG5cdGNvbnN0IHByb2dyZXNzV2lkdGggPSB3aW5kb3cuZ2V0Q29tcHV0ZWRTdHlsZShkb2N1bWVudC5kb2N1bWVudEVsZW1lbnQpLmdldFByb3BlcnR5VmFsdWUoJy0tcHJvZ3Jlc3Mtd2lkdGgnKTtcblxuXHRub2RlLnNldEF0dHJpYnV0ZSgncicsIDEyNSAtIChwcm9ncmVzc1dpZHRoIC8gMikpO1xufSIsIjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPmNvbWF0ZSDigJIge2Rldk1vZGUgPyAkbWludXRlcyA6ICRob3Vyc306e2Rldk1vZGUgPyAkc2Vjb25kcyA6ICRtaW51dGVzfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2NyaXB0PlxuXHRpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcblx0aW1wb3J0IHsgZmFkZSwgZmx5LCBzY2FsZSB9IGZyb20gJ3N2ZWx0ZS90cmFuc2l0aW9uJztcblx0aW1wb3J0IHsgZWxhc3RpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuXHRpbXBvcnQgeyBQbHVnaW5zIH0gZnJvbSAnQGNhcGFjaXRvci9jb3JlJztcblx0aW1wb3J0IHsgQnV0dG9uLCBJY29uLCBBdWRpb1BsYXllciB9IGZyb20gJy4uL2NvbXBvbmVudHMnO1xuXHRpbXBvcnQgeyBlbGFwc2VkVGltZSwgaG91cnMsIG1pbnV0ZXMsIHNlY29uZHMgfSBmcm9tICcuLi9zdG9yZS90aW1lci5qcyc7XG5cdGltcG9ydCB7IHByb2dyZXNzLCBwcm9ncmVzc0JhY2tncm91bmQgfSBmcm9tICcuLi9ob29rcy9wcm9ncmVzcy5qcyc7XG5cdGltcG9ydCBzb3VuZHMgZnJvbSAnLi4vZGF0YS9zb3VuZHMuanMnO1xuXG5cdGNvbnN0IHsgSGFwdGljcywgTG9jYWxOb3RpZmljYXRpb25zLCBUb2FzdCB9ID0gUGx1Z2lucztcblxuXHRsZXQgdGltZXIgPSBudWxsO1xuXHRsZXQgZGV2TW9kZSA9IGZhbHNlO1xuXG5cdCQ6IGVsYXBzZWRUaW1lLnJlc2V0KGRldk1vZGUpO1xuXG5cdG9uTW91bnQoYXN5bmMoKSA9PiB7XG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnJlcXVlc3RQZXJtaXNzaW9uKCk7XG5cdH0pO1xuXG5cdGNvbnN0IGhhbmRsZVN0YXJ0ID0gKCkgPT4ge1xuXHRcdHRpbWVyID0gc2V0SW50ZXJ2YWwoKCkgPT4ge1xuXHRcdFx0ZWxhcHNlZFRpbWUudXBkYXRlKHRpbWUgPT4gdGltZSAtIDEwMDApO1xuXG5cdFx0XHRpZiAoJGVsYXBzZWRUaW1lIDw9IDApIHtcblx0XHRcdFx0aGFuZGxlUmVzZXQoKTtcblx0XHRcdFx0aGFuZGxlU3RvcCgpO1xuXHRcdFx0fVxuXHRcdH0sIDEwMDApO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlU3RvcCA9IGFzeW5jKCkgPT4ge1xuXHRcdGF3YWl0IExvY2FsTm90aWZpY2F0aW9ucy5zY2hlZHVsZSh7XG5cdFx0XHRub3RpZmljYXRpb25zOiBbXG5cdFx0XHQgIHtcblx0XHRcdFx0dGl0bGU6IFwiV2FrZSB1cCFcIixcblx0XHRcdFx0Ym9keTogXCJBIGxvdmVseSBkYXkgaXMgd2FpdGluZyBmb3IgeW91LlwiLFxuXHRcdFx0XHRpZDogMSxcblx0XHRcdCAgfVxuXHRcdFx0XVxuXHRcdH0pO1xuXG5cdFx0YXVkaW8ucGxheSgpO1xuXG5cdFx0SGFwdGljcy52aWJyYXRlKCk7XG5cblx0XHRjb25zb2xlLmxvZygncGxheSBzb3VuZCcpO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlUmVzZXQgPSAoKSA9PiB7XG5cdFx0Y2xlYXJJbnRlcnZhbCh0aW1lcik7XG5cblx0XHRlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblx0XHR0aW1lciA9IG51bGw7XG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSAwO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlRGV2TW9kZSA9IGFzeW5jKCkgPT4ge1xuXHRcdGRldk1vZGUgPSAhZGV2TW9kZTtcblxuXHRcdGF3YWl0IFRvYXN0LnNob3coe1xuXHRcdFx0dGV4dDogZGV2TW9kZSA/ICdERVYgbW9kZSBlbmFibGVkJyA6ICdERVYgbW9kZSBkaXNhYmxlZCcsXG5cdFx0XHRwb3NpdGlvbjogJ3RvcCdcblx0XHR9KTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHQ8aGVhZGVyXG5cdFx0Y2xhc3M9XCJoZWFkZXJcIlxuXHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC01MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDk1MH19XG5cdD5cblx0XHQ8YVxuXHRcdFx0aHJlZj1cIi9cIlxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdD5cblx0XHRcdDxJY29uXG5cdFx0XHRcdHNyYz1cIi9pbmZvLnN2Z1wiXG5cdFx0XHRcdHc9XCI2XCJcblx0XHRcdD5cblx0XHRcdDwvSWNvbj5cblx0XHQ8L2E+XG5cblx0XHQ8aDEgY2xhc3M9XCJoZWFkZXJfX3RleHRcIj5cblx0XHRcdGNvbWF0ZVxuXHRcdDwvaDE+XG5cblx0XHQ8YnV0dG9uXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0XHRjbGFzczpoaWRkZW49eyEhdGltZXJ9XG5cdFx0XHRvbjpjbGljaz17aGFuZGxlRGV2TW9kZX1cblx0XHQ+XG5cdFx0XHR7I2lmICFkZXZNb2RlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jb2RlLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2Nsb2NrLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7L2lmfVxuXHRcdDwvYnV0dG9uPlxuXHQ8L2hlYWRlcj5cblxuXHQ8ZGl2PlxuXHRcdDxzcGFuXG5cdFx0XHRpbjpzY2FsZT17e29wYWNpdHk6IDAsIHN0YXJ0OiAwLjUsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAxMDAwfX1cblx0XHRcdGNsYXNzPVwidGltZVwiXG5cdFx0PlxuXHRcdFx0eyNpZiBkZXZNb2RlfVxuXHRcdFx0XHQ8c3BhblxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fc2Vjb25kc1wiXG5cdFx0XHRcdFx0aW46ZmFkZVxuXHRcdFx0XHQ+XG5cdFx0XHRcdFx0eyRtaW51dGVzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JHNlY29uZHN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PHNwYW4gaW46ZmFkZT5cblx0XHRcdFx0XHR7JGhvdXJzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JG1pbnV0ZXN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHsvaWZ9XG5cblx0XHRcdDxzdmcgY2xhc3M9XCJ0aW1lX19wcm9ncmVzc1wiPlxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0dXNlOnByb2dyZXNzQmFja2dyb3VuZFxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZFwiXG5cdFx0XHRcdFx0cj1cIjEyNVwiXG5cdFx0XHRcdFx0Y3g9XCIxMjVcIlxuXHRcdFx0XHRcdGN5PVwiMTI1XCJcblx0XHRcdFx0Lz5cblxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0dXNlOnByb2dyZXNzPXt7XG5cdFx0XHRcdFx0XHR0aW1lOiAkZWxhcHNlZFRpbWUsXG5cdFx0XHRcdFx0XHRkZXZNb2RlXG5cdFx0XHRcdFx0fX1cblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3Byb2dyZXNzLXJpbmdcIlxuXHRcdFx0XHRcdHI9XCIxMjVcIlxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cdFx0XHQ8L3N2Zz5cblx0XHQ8L3NwYW4+XG5cblx0XHQ8ZGl2IGNsYXNzPVwiYXVkaW9cIj5cblx0XHRcdHsjZWFjaCBzb3VuZHMgYXMgc291bmR9XG5cdFx0XHRcdDxBdWRpb1BsYXllclxuXHRcdFx0XHRcdHsuLi5zb3VuZH1cblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0F1ZGlvUGxheWVyPlxuXHRcdFx0ey9lYWNofVxuXG5cdFx0XHQ8YnV0dG9uXG5cdFx0XHRcdGNsYXNzPVwiYXVkaW9fX2J1dHRvblwiXG5cdFx0XHQ+XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2F1ZGlvLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE2XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L2J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0PC9kaXY+XG5cblx0eyNpZiAhdGltZXJ9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvbiBvbjpjbGljaz17aGFuZGxlU3RhcnR9PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+U3RhcnQgc2xlZXAgY3ljbGU8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcGxheS5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9CdXR0b24+XG5cdFx0PC9kaXY+XG5cdHs6ZWxzZX1cblx0XHQ8ZGl2IGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMjAwfX0+XG5cdFx0XHQ8QnV0dG9uXG5cdFx0XHRcdGFsdFxuXHRcdFx0XHRvbjpjbGljaz17aGFuZGxlUmVzZXR9XG5cdFx0XHQ+XG5cdFx0XHRcdDxzcGFuIGNsYXNzPVwidS1pY29uLXNwYWNpbmdcIj5SZXNldDwvc3Bhbj5cblxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9yZXNldC5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9CdXR0b24+XG5cdFx0PC9kaXY+XG5cdHsvaWZ9XG48L21haW4+XG5cbjxzdHlsZT5cblx0LnJvb3Qge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdG1hcmdpbjogMCBhdXRvO1xuXHRcdHBhZGRpbmc6IDE1cHggMjBweCA1MHB4O1xuXHR9XG5cblx0LmhlYWRlciB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHR9XG5cblx0LmhlYWRlcl9faWNvbiB7XG5cdFx0d2lkdGg6IDI1cHg7XG5cdFx0aGVpZ2h0OiAyNXB4O1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0Y29sb3I6IHZhcigtLWhpZ2hsaWdodC1jb2xvcik7XG5cdH1cblxuXHQuaGVhZGVyX190ZXh0IHtcblx0XHRmb250LXNpemU6IDE2cHg7XG5cdFx0Zm9udC13ZWlnaHQ6IDIwMDtcblx0XHRtYXJnaW46IDAgYXV0bztcblx0fVxuXG5cdC5oaWRkZW4ge1xuXHRcdG9wYWNpdHk6IDA7XG5cdFx0dmlzaWJpbGl0eTogaGlkZGVuO1xuXHRcdHBvaW50ZXItZXZlbnRzOiBub25lO1xuXHR9XG5cblx0LnRpbWUge1xuXHRcdHBvc2l0aW9uOiByZWxhdGl2ZTtcblx0XHR3aWR0aDogMjUwcHg7XG5cdFx0aGVpZ2h0OiAyNTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGZvbnQtc2l6ZTogNjBweDtcblx0XHR0ZXh0LXNoYWRvdzogMCAxNXB4IDMwcHggcmdiYSgwLCAwLCAwLCAwLjgpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzIHtcblx0XHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdFx0dG9wOiAwO1xuXHRcdGxlZnQ6IDA7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdFx0aGVpZ2h0OiAxMDAlO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLWJhY2tncm91bmQsXG5cdC50aW1lX19wcm9ncmVzcy1yaW5nIHtcblx0XHRzdHJva2Utd2lkdGg6IHZhcigtLXByb2dyZXNzLXdpZHRoKTtcblx0XHRmaWxsOiB0cmFuc3BhcmVudDtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kIHtcblx0XHRzdHJva2U6IHZhcigtLWFsdGVybmF0ZS1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3IpO1xuXG5cdFx0dHJhbnNpdGlvbjogc3Ryb2tlLWRhc2hvZmZzZXQgMC4zcyBlYXNlLW91dDtcblx0XHR0cmFuc2Zvcm06IHJvdGF0ZSgtOTBkZWcpO1xuXHRcdHRyYW5zZm9ybS1vcmlnaW46IGNlbnRlcjtcblx0fVxuXG5cdC50aW1lX19zZWNvbmRzIHtcblx0XHRjb2xvcjogdmFyKC0tc2lsdmVyLWNvbG9yLWZhZGVkKTtcblx0fVxuXG5cdC5hdWRpbyB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdG1hcmdpbi10b3A6IDMwcHg7XG5cdH1cblxuXHQuYXVkaW9fX2J1dHRvbiB7XG5cdFx0d2lkdGg6IDMwcHg7XG5cdFx0aGVpZ2h0OiAzMHB4O1xuXHRcdG1hcmdpbi1sZWZ0OiAxMHB4O1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvcik7XG5cdH1cblxuXHQucHVsc2Uge1xuXHRcdGFuaW1hdGlvbjogZmxhc2ggMnMgZWFzZS1pbiBpbmZpbml0ZTtcblx0fVxuXG5cdEBrZXlmcmFtZXMgZmxhc2gge1xuXHRcdDAlIHtcblx0XHRcdG9wYWNpdHk6IDE7XG5cdFx0fVxuXG5cdFx0NjAlIHtcblx0XHRcdG9wYWNpdHk6IDE7XG5cdFx0fVxuXG5cdFx0NjElIHtcblx0XHRcdG9wYWNpdHk6IDA7XG5cdFx0fVxuXG5cdFx0MTAwJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblx0fVxuPC9zdHlsZT4iLCJpbXBvcnQgeyB3cml0YWJsZSwgZGVyaXZlZCB9IGZyb20gJ3N2ZWx0ZS9zdG9yZSc7XG5cbmNvbnN0IFRJTUUgPSAyODgwMDAwMDsgLy8gOCBob3VycyBpbiBtaWxsaXNlY29uZHNcbmNvbnN0IERFVl9USU1FID0gMTAwMDA7IC8vIDEwIHNlY29uZHMgaW4gbWlsbGlzZWNvbmRzXG5cbmNvbnN0IGxlYWRpbmdaZXJvID0gKHZhbHVlKSA9PiB7XG5cdHJldHVybiAoJzAnICsgdmFsdWUpLnNsaWNlKC0yKTtcbn07XG5cbmNvbnN0IGNyZWF0ZVN0b3JlID0gKCkgPT4ge1xuXHRjb25zdCB7IHN1YnNjcmliZSwgc2V0LCB1cGRhdGUgfSA9IHdyaXRhYmxlKFRJTUUpO1xuXG5cdGNvbnN0IGhhbmRsZVJlc2V0ID0gKGlzRGV2KSA9PiB7XG5cdFx0aWYgKGlzRGV2KSB7XG5cdFx0XHRzZXQoREVWX1RJTUUpO1xuXHRcdH0gZWxzZSB7XG5cdFx0XHRzZXQoVElNRSlcblx0XHR9XG5cdH1cblxuXHRjb25zdCBnZXRUaW1lID0gKGlzRGV2KSA9PiB7XG5cdFx0aWYgKGlzRGV2KSB7XG5cdFx0XHRyZXR1cm4gREVWX1RJTUU7XG5cdFx0fSBlbHNlIHtcblx0XHRcdHJldHVybiBUSU1FO1xuXHRcdH1cblx0fVxuXG5cdHJldHVybiB7XG5cdFx0c3Vic2NyaWJlLFxuXHRcdHVwZGF0ZSxcblx0XHRyZXNldDogaGFuZGxlUmVzZXQsXG5cdFx0dGltZTogZ2V0VGltZVxuXHR9XG59XG5cbmV4cG9ydCBjb25zdCBlbGFwc2VkVGltZSA9IGNyZWF0ZVN0b3JlKCk7XG5cbmV4cG9ydCBjb25zdCBob3VycyA9IGRlcml2ZWQoZWxhcHNlZFRpbWUsICRlbGFwc2VkVGltZSA9PiBsZWFkaW5nWmVybyhNYXRoLmZsb29yKCgkZWxhcHNlZFRpbWUgLyAoMTAwMCAqIDYwICogNjApKSAlIDI0KSkpO1xuZXhwb3J0IGNvbnN0IG1pbnV0ZXMgPSBkZXJpdmVkKGVsYXBzZWRUaW1lLCAkZWxhcHNlZFRpbWUgPT4gbGVhZGluZ1plcm8oTWF0aC5mbG9vcigoJGVsYXBzZWRUaW1lIC8gMTAwMCAvIDYwKSAlIDYwICkpKTtcbmV4cG9ydCBjb25zdCBzZWNvbmRzID0gZGVyaXZlZChlbGFwc2VkVGltZSwgJGVsYXBzZWRUaW1lID0+IGxlYWRpbmdaZXJvKE1hdGguZmxvb3IoKCRlbGFwc2VkVGltZSAvIDEwMDApICUgNjApKSk7Il0sInNvdXJjZVJvb3QiOiIifQ==