(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["app"],{

/***/ "./src/routes/app.svelte":
/*!*******************************!*\
  !*** ./src/routes/app.svelte ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _capacitor_core__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @capacitor/core */ "./node_modules/@capacitor/core/dist/esm/index.js");
/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../components */ "./src/components/index.js");
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");
/* src/routes/app.svelte generated by Svelte v3.24.1 */


const { console: console_1, document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];






const file = "src/routes/app.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-9n5j34-style";
	style.textContent = ".root.svelte-9n5j34{display:flex;flex-direction:column;justify-content:space-between;align-items:center;margin:0 auto;padding:15px 20px 50px}.header.svelte-9n5j34{display:flex;align-items:center;width:100%}.header__icon.svelte-9n5j34{width:25px;height:25px;display:flex;justify-content:center;align-items:center;color:var(--highlight-color)}.header__text.svelte-9n5j34{font-size:16px;font-weight:200;margin:0 auto}.hidden.svelte-9n5j34{opacity:0;visibility:hidden;pointer-events:none}.time.svelte-9n5j34{position:relative;width:250px;height:250px;display:flex;justify-content:center;align-items:center;font-size:60px;text-shadow:0 15px 30px rgba(0, 0, 0, 0.8)}.time__progress.svelte-9n5j34{position:absolute;top:0;left:0;width:100%;height:100%}.time__progress-background.svelte-9n5j34,.time__progress-ring.svelte-9n5j34{stroke-width:var(--progress-width);fill:transparent}.time__progress-background.svelte-9n5j34{stroke:var(--alternate-color-faded)}.time__progress-ring.svelte-9n5j34{stroke:var(--alternate-color);transition:stroke-dashoffset 0.3s ease-out;transform:rotate(-90deg);transform-origin:center}.time__seconds.svelte-9n5j34{color:var(--silver-color-faded)}.audio.svelte-9n5j34{display:flex;justify-content:center;align-items:center;margin-top:30px}.audio__button.svelte-9n5j34{width:30px;height:30px;margin-left:10px;display:flex;justify-content:center;align-items:center;color:var(--silver-color)}.pulse.svelte-9n5j34{animation:svelte-9n5j34-flash 2s ease-in infinite}@keyframes svelte-9n5j34-flash{0%{opacity:1}60%{opacity:1}61%{opacity:0}100%{opacity:0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXBwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiYXBwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5jb21hdGUg4oCSIHtkZXZNb2RlID8gJGVsYXBzZWRUaW1lLm1pbnV0ZXMgOiAkZWxhcHNlZFRpbWUuaG91cnN9OntkZXZNb2RlID8gJGVsYXBzZWRUaW1lLnNlY29uZHMgOiAkZWxhcHNlZFRpbWUubWludXRlc308L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZhZGUsIGZseSwgc2NhbGUgfSBmcm9tICdzdmVsdGUvdHJhbnNpdGlvbic7XG5cdGltcG9ydCB7IGVsYXN0aWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgUGx1Z2lucyB9IGZyb20gJ0BjYXBhY2l0b3IvY29yZSc7XG5cdGltcG9ydCB7IEJ1dHRvbiwgSWNvbiwgQXVkaW9QbGF5ZXIgfSBmcm9tICcuLi9jb21wb25lbnRzJztcblx0aW1wb3J0IHsgdGltZSwgZWxhcHNlZFRpbWUgfSBmcm9tICcuLi9zdG9yZS90aW1lci5qcyc7XG5cblx0Y29uc3QgeyBIYXB0aWNzLCBMb2NhbE5vdGlmaWNhdGlvbnMsIFRvYXN0IH0gPSBQbHVnaW5zO1xuXG5cdCQ6IGlmIChkZXZNb2RlKSB7XG5cdFx0dGltZS5zZXQoMTAwMDApO1xuXHR9IGVsc2Uge1xuXHRcdHRpbWUuc2V0KDI4ODAwMDAwKTtcblx0fVxuXG5cdGNvbnN0IHNvdW5kcyA9IFtcblx0XHR7XG5cdFx0XHRzcmM6ICcvYXVkaW8vc291bmQxLm1wMycsXG5cdFx0XHR0aXRsZTogJ0FsYW5lJyxcblx0XHRcdG1ha2VyOiAnUm9iaW4gU2NodWx6ICYgV2VzJ1xuXHRcdH1cblx0XVxuXG5cdGxldCB0aW1lciA9IG51bGw7XG5cdGxldCBkZXZNb2RlID0gZmFsc2U7XG5cblx0bGV0IHByb2dyZXNzV2lkdGggPSAwO1xuXHRsZXQgY2lyY2xlID0gbnVsbDtcblx0bGV0IGNpcmN1bWZlcmVuY2UgPSAwO1xuXG5cdG9uTW91bnQoYXN5bmMoKSA9PiB7XG5cdFx0aW5pdFByb2dyZXNzUmluZygpO1xuXG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnJlcXVlc3RQZXJtaXNzaW9uKCk7XG5cdH0pO1xuXG5cdGNvbnN0IGluaXRQcm9ncmVzc1JpbmcgPSAoKSA9PiB7XG5cdFx0cHJvZ3Jlc3NXaWR0aCA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuZ2V0UHJvcGVydHlWYWx1ZSgnLS1wcm9ncmVzcy13aWR0aCcpO1xuXG5cdFx0Y2lyY3VtZmVyZW5jZSA9IGNpcmNsZS5yLmJhc2VWYWwudmFsdWUgKiAyICogTWF0aC5QSTtcblxuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNoYXJyYXkgPSBgJHtjaXJjdW1mZXJlbmNlfSAke2NpcmN1bWZlcmVuY2V9YDtcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IDA7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVQcm9ncmVzcyA9IChlbGFwc2VkVGltZSkgPT4ge1xuXHRcdGNvbnN0IHByb2dyZXNzID0gMSAtIChlbGFwc2VkVGltZSAvIHRpbWUpO1xuXHRcdGNvbnN0IG9mZnNldCA9IGNpcmN1bWZlcmVuY2UgKiBwcm9ncmVzcztcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IG9mZnNldDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0YXJ0ID0gKCkgPT4ge1xuXHRcdHRpbWVyID0gc2V0SW50ZXJ2YWwoKCkgPT4ge1xuXHRcdFx0ZWxhcHNlZFRpbWUgLT0gMTAwMDtcblxuXHRcdFx0aGFuZGxlUHJvZ3Jlc3MoZWxhcHNlZFRpbWUpO1xuXG5cdFx0XHRpZiAoZWxhcHNlZFRpbWUgPD0gMCkge1xuXHRcdFx0XHRoYW5kbGVSZXNldCgpO1xuXHRcdFx0XHRoYW5kbGVTdG9wKCk7XG5cdFx0XHR9XG5cdFx0fSwgMTAwMCk7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVTdG9wID0gYXN5bmMoKSA9PiB7XG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnNjaGVkdWxlKHtcblx0XHRcdG5vdGlmaWNhdGlvbnM6IFtcblx0XHRcdCAge1xuXHRcdFx0XHR0aXRsZTogXCJXYWtlIHVwIVwiLFxuXHRcdFx0XHRib2R5OiBcIkEgbG92ZWx5IGRheSBpcyB3YWl0aW5nIGZvciB5b3UuXCIsXG5cdFx0XHRcdGlkOiAxLFxuXHRcdFx0ICB9XG5cdFx0XHRdXG5cdFx0fSk7XG5cblx0XHRhdWRpby5wbGF5KCk7XG5cblx0XHRIYXB0aWNzLnZpYnJhdGUoKTtcblxuXHRcdGNvbnNvbGUubG9nKCdwbGF5IHNvdW5kJyk7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVSZXNldCA9ICgpID0+IHtcblx0XHRjbGVhckludGVydmFsKHRpbWVyKTtcblxuXHRcdGVsYXBzZWRUaW1lID0gdGltZTtcblx0XHR0aW1lciA9IG51bGw7XG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSAwO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlRGV2TW9kZSA9IGFzeW5jKCkgPT4ge1xuXHRcdGRldk1vZGUgPSAhZGV2TW9kZTtcblxuXHRcdGF3YWl0IFRvYXN0LnNob3coe1xuXHRcdFx0dGV4dDogZGV2TW9kZSA/ICdERVYgbW9kZSBlbmFibGVkJyA6ICdERVYgbW9kZSBkaXNhYmxlZCcsXG5cdFx0XHRwb3NpdGlvbjogJ3RvcCdcblx0XHR9KTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHQ8aGVhZGVyXG5cdFx0Y2xhc3M9XCJoZWFkZXJcIlxuXHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC01MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDk1MH19XG5cdD5cblx0XHQ8YVxuXHRcdFx0aHJlZj1cIi9cIlxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdD5cblx0XHRcdDxJY29uXG5cdFx0XHRcdHNyYz1cIi9pbmZvLnN2Z1wiXG5cdFx0XHRcdHc9XCI2XCJcblx0XHRcdD5cblx0XHRcdDwvSWNvbj5cblx0XHQ8L2E+XG5cblx0XHQ8aDEgY2xhc3M9XCJoZWFkZXJfX3RleHRcIj5cblx0XHRcdGNvbWF0ZVxuXHRcdDwvaDE+XG5cblx0XHQ8YnV0dG9uXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0XHRjbGFzczpoaWRkZW49eyEhdGltZXJ9XG5cdFx0XHRvbjpjbGljaz17aGFuZGxlRGV2TW9kZX1cblx0XHQ+XG5cdFx0XHR7I2lmICFkZXZNb2RlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jb2RlLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2Nsb2NrLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7L2lmfVxuXHRcdDwvYnV0dG9uPlxuXHQ8L2hlYWRlcj5cblxuXHQ8ZGl2PlxuXHRcdDxzcGFuXG5cdFx0XHRpbjpzY2FsZT17e29wYWNpdHk6IDAsIHN0YXJ0OiAwLjUsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAxMDAwfX1cblx0XHRcdGNsYXNzPVwidGltZVwiXG5cdFx0PlxuXHRcdFx0eyNpZiBkZXZNb2RlfVxuXHRcdFx0XHQ8c3BhblxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fc2Vjb25kc1wiXG5cdFx0XHRcdFx0aW46ZmFkZVxuXHRcdFx0XHQ+XG5cdFx0XHRcdFx0eyRlbGFwc2VkVGltZS5taW51dGVzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JGVsYXBzZWRUaW1lLnNlY29uZHN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PHNwYW4gaW46ZmFkZT5cblx0XHRcdFx0XHR7JGVsYXBzZWRUaW1lLmhvdXJzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JGVsYXBzZWRUaW1lLm1pbnV0ZXN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHsvaWZ9XG5cblx0XHRcdDxzdmcgY2xhc3M9XCJ0aW1lX19wcm9ncmVzc1wiPlxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kXCJcblx0XHRcdFx0XHRyPXsxMjUgLSAocHJvZ3Jlc3NXaWR0aCAvIDIpfVxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdGJpbmQ6dGhpcz17Y2lyY2xlfVxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtcmluZ1wiXG5cdFx0XHRcdFx0cj17MTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKX1cblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXHRcdFx0PC9zdmc+XG5cdFx0PC9zcGFuPlxuXG5cdFx0PGRpdiBjbGFzcz1cImF1ZGlvXCI+XG5cdFx0XHR7I2VhY2ggc291bmRzIGFzIHNvdW5kfVxuXHRcdFx0XHQ8QXVkaW9QbGF5ZXJcblx0XHRcdFx0XHR7Li4uc291bmR9XG5cdFx0XHRcdD5cblx0XHRcdFx0PC9BdWRpb1BsYXllcj5cblx0XHRcdHsvZWFjaH1cblxuXHRcdFx0PGJ1dHRvblxuXHRcdFx0XHRjbGFzcz1cImF1ZGlvX19idXR0b25cIlxuXHRcdFx0PlxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9hdWRpby5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9idXR0b24+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdHsjaWYgIXRpbWVyfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b24gb246Y2xpY2s9e2hhbmRsZVN0YXJ0fT5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlN0YXJ0IHNsZWVwIGN5Y2xlPC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3BsYXkuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTRcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7OmVsc2V9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvblxuXHRcdFx0XHRhbHRcblx0XHRcdFx0b246Y2xpY2s9e2hhbmRsZVJlc2V0fVxuXHRcdFx0PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+UmVzZXQ8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcmVzZXQuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7L2lmfVxuPC9tYWluPlxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXJnaW46IDAgYXV0bztcblx0XHRwYWRkaW5nOiAxNXB4IDIwcHggNTBweDtcblx0fVxuXG5cdC5oZWFkZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5oZWFkZXJfX2ljb24ge1xuXHRcdHdpZHRoOiAyNXB4O1xuXHRcdGhlaWdodDogMjVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1oaWdobGlnaHQtY29sb3IpO1xuXHR9XG5cblx0LmhlYWRlcl9fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAxNnB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdH1cblxuXHQuaGlkZGVuIHtcblx0XHRvcGFjaXR5OiAwO1xuXHRcdHZpc2liaWxpdHk6IGhpZGRlbjtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0fVxuXG5cdC50aW1lIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0d2lkdGg6IDI1MHB4O1xuXHRcdGhlaWdodDogMjUwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRmb250LXNpemU6IDYwcHg7XG5cdFx0dGV4dC1zaGFkb3c6IDAgMTVweCAzMHB4IHJnYmEoMCwgMCwgMCwgMC44KTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcyB7XG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRsZWZ0OiAwO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kLFxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlLXdpZHRoOiB2YXIoLS1wcm9ncmVzcy13aWR0aCk7XG5cdFx0ZmlsbDogdHJhbnNwYXJlbnQ7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yKTtcblxuXHRcdHRyYW5zaXRpb246IHN0cm9rZS1kYXNob2Zmc2V0IDAuM3MgZWFzZS1vdXQ7XG5cdFx0dHJhbnNmb3JtOiByb3RhdGUoLTkwZGVnKTtcblx0XHR0cmFuc2Zvcm0tb3JpZ2luOiBjZW50ZXI7XG5cdH1cblxuXHQudGltZV9fc2Vjb25kcyB7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuYXVkaW8ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cblx0LmF1ZGlvX19idXR0b24ge1xuXHRcdHdpZHRoOiAzMHB4O1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRtYXJnaW4tbGVmdDogMTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LnB1bHNlIHtcblx0XHRhbmltYXRpb246IGZsYXNoIDJzIGVhc2UtaW4gaW5maW5pdGU7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIGZsYXNoIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYxJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cdH1cbjwvc3R5bGU+Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQXlPQyxLQUFLLGNBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsZUFBZSxDQUFFLGFBQWEsQ0FDOUIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxBQUN4QixDQUFDLEFBRUQsT0FBTyxjQUFDLENBQUMsQUFDUixPQUFPLENBQUUsSUFBSSxDQUNiLFdBQVcsQ0FBRSxNQUFNLENBQ25CLEtBQUssQ0FBRSxJQUFJLEFBQ1osQ0FBQyxBQUVELGFBQWEsY0FBQyxDQUFDLEFBQ2QsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUVaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsS0FBSyxDQUFFLElBQUksaUJBQWlCLENBQUMsQUFDOUIsQ0FBQyxBQUVELGFBQWEsY0FBQyxDQUFDLEFBQ2QsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsR0FBRyxDQUNoQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDZixDQUFDLEFBRUQsT0FBTyxjQUFDLENBQUMsQUFDUixPQUFPLENBQUUsQ0FBQyxDQUNWLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLGNBQWMsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFFRCxLQUFLLGNBQUMsQ0FBQyxBQUNOLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQ0FFYixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLFNBQVMsQ0FBRSxJQUFJLENBQ2YsV0FBVyxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLEFBQzVDLENBQUMsQUFFRCxlQUFlLGNBQUMsQ0FBQyxBQUNoQixRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsQ0FBQyxDQUNOLElBQUksQ0FBRSxDQUFDLENBQ1AsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxBQUNiLENBQUMsQUFFRCx3Q0FBMEIsQ0FDMUIsb0JBQW9CLGNBQUMsQ0FBQyxBQUNyQixZQUFZLENBQUUsSUFBSSxnQkFBZ0IsQ0FBQyxDQUNuQyxJQUFJLENBQUUsV0FBVyxBQUNsQixDQUFDLEFBRUQsMEJBQTBCLGNBQUMsQ0FBQyxBQUMzQixNQUFNLENBQUUsSUFBSSx1QkFBdUIsQ0FBQyxBQUNyQyxDQUFDLEFBRUQsb0JBQW9CLGNBQUMsQ0FBQyxBQUNyQixNQUFNLENBQUUsSUFBSSxpQkFBaUIsQ0FBQyxDQUU5QixVQUFVLENBQUUsaUJBQWlCLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FDM0MsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLENBQ3pCLGdCQUFnQixDQUFFLE1BQU0sQUFDekIsQ0FBQyxBQUVELGNBQWMsY0FBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksb0JBQW9CLENBQUMsQUFDakMsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUNuQixVQUFVLENBQUUsSUFBSSxBQUNqQixDQUFDLEFBRUQsY0FBYyxjQUFDLENBQUMsQUFDZixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osV0FBVyxDQUFFLElBQUksQ0FFakIsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUVuQixLQUFLLENBQUUsSUFBSSxjQUFjLENBQUMsQUFDM0IsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLG1CQUFLLENBQUMsRUFBRSxDQUFDLE9BQU8sQ0FBQyxRQUFRLEFBQ3JDLENBQUMsQUFFRCxXQUFXLG1CQUFNLENBQUMsQUFDakIsRUFBRSxBQUFDLENBQUMsQUFDSCxPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxHQUFHLEFBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxDQUFDLEFBQ1gsQ0FBQyxBQUVELEdBQUcsQUFBQyxDQUFDLEFBQ0osT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsSUFBSSxBQUFDLENBQUMsQUFDTCxPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFDRixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[17] = list[i];
	return child_ctx;
}

// (137:3) {:else}
function create_else_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/clock.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_2.name,
		type: "else",
		source: "(137:3) {:else}",
		ctx
	});

	return block;
}

// (131:3) {#if !devMode}
function create_if_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/code.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(131:3) {#if !devMode}",
		ctx
	});

	return block;
}

// (159:3) {:else}
function create_else_block_1(ctx) {
	let span1;
	let t0_value = /*$elapsedTime*/ ctx[4].hours + "";
	let t0;
	let span0;
	let t1;
	let t2_value = /*$elapsedTime*/ ctx[4].minutes + "";
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t2_value);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", {});
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t0_value);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t2_value);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 160, 25, 3099);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 159, 4, 3059);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$elapsedTime*/ 16 && t0_value !== (t0_value = /*$elapsedTime*/ ctx[4].hours + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$elapsedTime*/ 16 && t2_value !== (t2_value = /*$elapsedTime*/ ctx[4].minutes + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, t2_value);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_1.name,
		type: "else",
		source: "(159:3) {:else}",
		ctx
	});

	return block;
}

// (152:3) {#if devMode}
function create_if_block_1(ctx) {
	let span1;
	let t0_value = /*$elapsedTime*/ ctx[4].minutes + "";
	let t0;
	let span0;
	let t1;
	let t2_value = /*$elapsedTime*/ ctx[4].seconds + "";
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t2_value);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t0_value);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t2_value);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 156, 27, 2975);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "time__seconds svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 152, 4, 2896);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$elapsedTime*/ 16 && t0_value !== (t0_value = /*$elapsedTime*/ ctx[4].minutes + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$elapsedTime*/ 16 && t2_value !== (t2_value = /*$elapsedTime*/ ctx[4].seconds + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, t2_value);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(152:3) {#if devMode}",
		ctx
	});

	return block;
}

// (184:3) {#each sounds as sound}
function create_each_block(ctx) {
	let audioplayer;
	let current;
	const audioplayer_spread_levels = [/*sound*/ ctx[17]];
	let audioplayer_props = {};

	for (let i = 0; i < audioplayer_spread_levels.length; i += 1) {
		audioplayer_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(audioplayer_props, audioplayer_spread_levels[i]);
	}

	audioplayer = new _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"]({ props: audioplayer_props, $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(audioplayer.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(audioplayer.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(audioplayer, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const audioplayer_changes = (dirty & /*sounds*/ 32)
			? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(audioplayer_spread_levels, [Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_object"])(/*sound*/ ctx[17])])
			: {};

			if (dirty & /*$$scope*/ 1048576) {
				audioplayer_changes.$$scope = { dirty, ctx };
			}

			audioplayer.$set(audioplayer_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(audioplayer.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(audioplayer.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(audioplayer, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(184:3) {#each sounds as sound}",
		ctx
	});

	return block;
}

// (215:1) {:else}
function create_else_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				alt: true,
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleReset*/ ctx[7]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 215, 2, 4033);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(215:1) {:else}",
		ctx
	});

	return block;
}

// (203:1) {#if !timer}
function create_if_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleStart*/ ctx[6]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 203, 2, 3762);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(203:1) {#if !timer}",
		ctx
	});

	return block;
}

// (217:3) <Button     alt     on:click={handleReset}    >
function create_default_slot_2(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/reset.svg", w: "16" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Reset");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Reset");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 220, 4, 4171);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(217:3) <Button     alt     on:click={handleReset}    >",
		ctx
	});

	return block;
}

// (205:3) <Button on:click={handleStart}>
function create_default_slot(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/play.svg", w: "14" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Start sleep cycle");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Start sleep cycle");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 205, 4, 3884);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(205:3) <Button on:click={handleStart}>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let main;
	let header;
	let a;
	let icon0;
	let t1;
	let h1;
	let t2;
	let t3;
	let button0;
	let current_block_type_index;
	let if_block0;
	let header_intro;
	let t4;
	let div1;
	let span;
	let t5;
	let svg;
	let circle0;
	let circle0_r_value;
	let circle1;
	let circle1_r_value;
	let span_intro;
	let t6;
	let div0;
	let t7;
	let button1;
	let icon1;
	let t8;
	let current_block_type_index_1;
	let if_block2;
	let current;
	let mounted;
	let dispose;

	document_1.title = title_value = "comate ‒ " + (/*devMode*/ ctx[1]
	? /*$elapsedTime*/ ctx[4].minutes
	: /*$elapsedTime*/ ctx[4].hours) + ":" + (/*devMode*/ ctx[1]
	? /*$elapsedTime*/ ctx[4].seconds
	: /*$elapsedTime*/ ctx[4].minutes);

	icon0 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/info.svg", w: "6" },
			$$inline: true
		});

	const if_block_creators = [create_if_block_2, create_else_block_2];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (!/*devMode*/ ctx[1]) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	function select_block_type_1(ctx, dirty) {
		if (/*devMode*/ ctx[1]) return create_if_block_1;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_1(ctx, -1);
	let if_block1 = current_block_type(ctx);
	let each_value = /*sounds*/ ctx[5];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	icon1 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/audio.svg", w: "16" },
			$$inline: true
		});

	const if_block_creators_1 = [create_if_block, create_else_block];
	const if_blocks_1 = [];

	function select_block_type_2(ctx, dirty) {
		if (!/*timer*/ ctx[0]) return 0;
		return 1;
	}

	current_block_type_index_1 = select_block_type_2(ctx, -1);
	if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon0.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("comate");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon1.$$.fragment);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if_block2.c();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-8mgq0t\"]", document_1.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "HEADER", { class: true });
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "A", { href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon0.$$.fragment, a_nodes);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "comate");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "BUTTON", { class: true });
			var button0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button0);
			if_block0.l(button0_nodes);
			button0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			if_block1.l(span_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "svg", { class: true }, 1);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div0_nodes);
			}

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon1.$$.fragment, button1_nodes);
			button1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			if_block2.l(main_nodes);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 110, 2, 2322);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "header__text svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 121, 2, 2430);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button0, "class", "header__icon svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button0, file, 125, 2, 2477);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(header, "class", "header svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 106, 1, 2212);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "class", "time__progress-background svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", circle0_r_value = 125 - /*progressWidth*/ ctx[2] / 2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle0, file, 165, 4, 3214);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "class", "time__progress-ring svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", circle1_r_value = 125 - /*progressWidth*/ ctx[2] / 2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle1, file, 172, 4, 3336);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "class", "time__progress svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 164, 3, 3181);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "time svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 147, 2, 2761);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button1, "class", "audio__button svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button1, file, 190, 3, 3614);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "audio svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 182, 2, 3494);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 146, 1, 2753);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "class", "root svelte-9n5j34");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 105, 0, 2191);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon0, a, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, button0);
			if_blocks[current_block_type_index].m(button0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, span);
			if_block1.m(span, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle1);
			/*circle1_binding*/ ctx[9](circle1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon1, button1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t8);
			if_blocks_1[current_block_type_index_1].m(main, null);
			current = true;

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button0, "click", /*handleDevMode*/ ctx[8], false, false, false);
				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if ((!current || dirty & /*devMode, $elapsedTime*/ 18) && title_value !== (title_value = "comate ‒ " + (/*devMode*/ ctx[1]
			? /*$elapsedTime*/ ctx[4].minutes
			: /*$elapsedTime*/ ctx[4].hours) + ":" + (/*devMode*/ ctx[1]
			? /*$elapsedTime*/ ctx[4].seconds
			: /*$elapsedTime*/ ctx[4].minutes))) {
				document_1.title = title_value;
			}

			const icon0_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				icon0_changes.$$scope = { dirty, ctx };
			}

			icon0.$set(icon0_changes);
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index !== previous_block_index) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block0 = if_blocks[current_block_type_index];

				if (!if_block0) {
					if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block0.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
				if_block0.m(button0, null);
			}

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			}

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block1) {
				if_block1.p(ctx, dirty);
			} else {
				if_block1.d(1);
				if_block1 = current_block_type(ctx);

				if (if_block1) {
					if_block1.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					if_block1.m(span, t5);
				}
			}

			if (!current || dirty & /*progressWidth*/ 4 && circle0_r_value !== (circle0_r_value = 125 - /*progressWidth*/ ctx[2] / 2)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", circle0_r_value);
			}

			if (!current || dirty & /*progressWidth*/ 4 && circle1_r_value !== (circle1_r_value = 125 - /*progressWidth*/ ctx[2] / 2)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", circle1_r_value);
			}

			if (dirty & /*sounds*/ 32) {
				each_value = /*sounds*/ ctx[5];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(div0, t7);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			const icon1_changes = {};

			if (dirty & /*$$scope*/ 1048576) {
				icon1_changes.$$scope = { dirty, ctx };
			}

			icon1.$set(icon1_changes);
			let previous_block_index_1 = current_block_type_index_1;
			current_block_type_index_1 = select_block_type_2(ctx, dirty);

			if (current_block_type_index_1 === previous_block_index_1) {
				if_blocks_1[current_block_type_index_1].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks_1[previous_block_index_1], 1, 1, () => {
					if_blocks_1[previous_block_index_1] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block2 = if_blocks_1[current_block_type_index_1];

				if (!if_block2) {
					if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);
					if_block2.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2, 1);
				if_block2.m(main, null);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0);

			if (!header_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					header_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(header, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: -50,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 950
					});

					header_intro.start();
				});
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1);

			if (!span_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"], {
						opacity: 0,
						start: 0.5,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 1000
					});

					span_intro.start();
				});
			}

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0);
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block2);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon0);
			if_blocks[current_block_type_index].d();
			if_block1.d();
			/*circle1_binding*/ ctx[9](null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon1);
			if_blocks_1[current_block_type_index_1].d();
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $elapsedTime,
		$$unsubscribe_elapsedTime = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		$$subscribe_elapsedTime = () => ($$unsubscribe_elapsedTime(), $$unsubscribe_elapsedTime = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["subscribe"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], $$value => $$invalidate(4, $elapsedTime = $$value)), _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"]);

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], "elapsedTime");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], $$value => $$invalidate(4, $elapsedTime = $$value));
	$$self.$$.on_destroy.push(() => $$unsubscribe_elapsedTime());
	const { Haptics, LocalNotifications, Toast } = _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"];

	const sounds = [
		{
			src: "/audio/sound1.mp3",
			title: "Alane",
			maker: "Robin Schulz & Wes"
		}
	];

	let timer = null;
	let devMode = false;
	let progressWidth = 0;
	let circle = null;
	let circumference = 0;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		initProgressRing();
		await LocalNotifications.requestPermission();
	});

	const initProgressRing = () => {
		$$invalidate(2, progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue("--progress-width"));
		circumference = circle.r.baseVal.value * 2 * Math.PI;
		$$invalidate(3, circle.style.strokeDasharray = `${circumference} ${circumference}`, circle);
		$$invalidate(3, circle.style.strokeDashoffset = 0, circle);
	};

	const handleProgress = elapsedTime => {
		const progress = 1 - elapsedTime / _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["time"];
		const offset = circumference * progress;
		$$invalidate(3, circle.style.strokeDashoffset = offset, circle);
	};

	const handleStart = () => {
		$$invalidate(0, timer = setInterval(
			() => {
				elapsedTime -= 1000;
				handleProgress(elapsedTime);

				if (elapsedTime <= 0) {
					handleReset();
					handleStop();
				}
			},
			1000
		));
	};

	const handleStop = async () => {
		await LocalNotifications.schedule({
			notifications: [
				{
					title: "Wake up!",
					body: "A lovely day is waiting for you.",
					id: 1
				}
			]
		});

		audio.play();
		Haptics.vibrate();
		console.log("play sound");
	};

	const handleReset = () => {
		clearInterval(timer);
		elapsedTime = _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["time"];
		$$invalidate(0, timer = null);
		$$invalidate(3, circle.style.strokeDashoffset = 0, circle);
	};

	const handleDevMode = async () => {
		$$invalidate(1, devMode = !devMode);

		await Toast.show({
			text: devMode ? "DEV mode enabled" : "DEV mode disabled",
			position: "top"
		});
	};

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<App> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("App", $$slots, []);

	function circle1_binding($$value) {
		svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"][$$value ? "unshift" : "push"](() => {
			circle = $$value;
			$$invalidate(3, circle);
		});
	}

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"],
		scale: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"],
		elasticOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
		Plugins: _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"],
		Button: _components__WEBPACK_IMPORTED_MODULE_5__["Button"],
		Icon: _components__WEBPACK_IMPORTED_MODULE_5__["Icon"],
		AudioPlayer: _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"],
		time: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["time"],
		elapsedTime: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"],
		Haptics,
		LocalNotifications,
		Toast,
		sounds,
		timer,
		devMode,
		progressWidth,
		circle,
		circumference,
		initProgressRing,
		handleProgress,
		handleStart,
		handleStop,
		handleReset,
		handleDevMode,
		$elapsedTime
	});

	$$self.$inject_state = $$props => {
		if ("timer" in $$props) $$invalidate(0, timer = $$props.timer);
		if ("devMode" in $$props) $$invalidate(1, devMode = $$props.devMode);
		if ("progressWidth" in $$props) $$invalidate(2, progressWidth = $$props.progressWidth);
		if ("circle" in $$props) $$invalidate(3, circle = $$props.circle);
		if ("circumference" in $$props) circumference = $$props.circumference;
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*devMode*/ 2) {
			$: if (devMode) {
				_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["time"].set(10000);
			} else {
				_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["time"].set(28800000);
			}
		}
	};

	return [
		timer,
		devMode,
		progressWidth,
		circle,
		$elapsedTime,
		sounds,
		handleStart,
		handleReset,
		handleDevMode,
		circle1_binding
	];
}

class App extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-9n5j34-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (App);

/***/ }),

/***/ "./src/store/timer.js":
/*!****************************!*\
  !*** ./src/store/timer.js ***!
  \****************************/
/*! exports provided: time, elapsedTime */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "time", function() { return time; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "elapsedTime", function() { return elapsedTime; });
/* harmony import */ var svelte_store__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/store */ "./node_modules/svelte/store/index.mjs");


const leadingZero = (value) => {
	return ('0' + value).slice(-2);
};

const time = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["writable"])(28800000);

const createStore = () => {
	const { subscribe, set } = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["writable"])(time);

	const elapsedTime = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(time, $time => $time);
	console.log($elapsedTime);
	const hours = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / (1000 * 60 * 60)) % 24 )));
	const minutes = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000 / 60) % 60 )));
	const seconds = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000) % 60 )));

	// const handleStart = () => {
	// 	set(null);
	// }

	// const handleReset = () => {
	// 	set(null);
	// }

	return {
		subscribe,
		set,
		hours,
		minutes,
		seconds
	};
}

const elapsedTime = createStore();

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2FwcC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3N0b3JlL3RpbWVyLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFLa0M7QUFDb0I7QUFDVjtBQUNEO0FBQ2dCO0FBQ0o7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpQ0FzSmpELEdBQVksSUFBQyxLQUFLOzs7O2lDQUFvQyxHQUFZLElBQUMsT0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tHQUFwQyxHQUFLOzs7Ozs7Ozs7Ozs7Z0ZBQTNDLEdBQVksSUFBQyxLQUFLOzs7bUdBQW9CLEdBQUs7OztnRkFBVyxHQUFZLElBQUMsT0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lDQUoxRSxHQUFZLElBQUMsT0FBTzs7OztpQ0FBb0MsR0FBWSxJQUFDLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrR0FBcEMsR0FBSzs7Ozs7Ozs7Ozs7OztnRkFBN0MsR0FBWSxJQUFDLE9BQU87OzttR0FBb0IsR0FBSzs7O2dGQUFXLEdBQVksSUFBQyxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhDQTZCekUsR0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrTEFBTCxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQ0FpQ0EsR0FBVzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01BSFQsT0FBTyxFQUFFLENBQUM7TUFBRSxDQUFDLEVBQUUsRUFBRTtNQUFFLE1BQU0sRUFBRSx3REFBVTtNQUFFLFFBQVEsRUFBRSxJQUFJO01BQUUsS0FBSyxFQUFFLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQ0FYNUQsR0FBVzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01BRGhCLE9BQU8sRUFBRSxDQUFDO01BQUUsQ0FBQyxFQUFFLEVBQUU7TUFBRSxNQUFNLEVBQUUsd0RBQVU7TUFBRSxRQUFRLEVBQUUsSUFBSTtNQUFFLEtBQUssRUFBRSxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2REExTS9ELEdBQU87b0JBQUcsR0FBWSxJQUFDLE9BQU87b0JBQUcsR0FBWSxJQUFDLEtBQUssdUJBQUcsR0FBTztvQkFBRyxHQUFZLElBQUMsT0FBTztvQkFBRyxHQUFZLElBQUMsT0FBTzs7Ozs7Ozs7Ozs7bUJBaUlwSCxHQUFPOzs7Ozs7OztrQkFxQlIsR0FBTzs7Ozs7OzZCQWdDTCxHQUFNOzs7O2dDQUFYLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O2lCQW1CRixHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1R0EzRU8sR0FBSzs7Ozs7b0dBd0NoQixHQUFHLHFCQUFJLEdBQWEsTUFBRyxDQUFDOzs7OztvR0FReEIsR0FBRyxxQkFBSSxHQUFhLE1BQUcsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxSEEvQ25CLEdBQWE7Ozs7O3VIQS9IUixHQUFPO3NCQUFHLEdBQVksSUFBQyxPQUFPO3NCQUFHLEdBQVksSUFBQyxLQUFLLHVCQUFHLEdBQU87c0JBQUcsR0FBWSxJQUFDLE9BQU87c0JBQUcsR0FBWSxJQUFDLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0dBOEgxRyxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7O3lGQXdDaEIsR0FBRyxxQkFBSSxHQUFhLE1BQUcsQ0FBQzs7Ozt5RkFReEIsR0FBRyxxQkFBSSxHQUFhLE1BQUcsQ0FBQzs7Ozs7NEJBUXRCLEdBQU07Ozs7K0JBQVgsTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozt3QkFBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01BM0VFLE9BQU8sRUFBRSxDQUFDO01BQUUsQ0FBQyxHQUFHLEVBQUU7TUFBRSxNQUFNLEVBQUUsd0RBQVU7TUFBRSxRQUFRLEVBQUUsSUFBSTtNQUFFLEtBQUssRUFBRSxHQUFHOzs7Ozs7Ozs7Ozs7TUF3Qy9ELE9BQU8sRUFBRSxDQUFDO01BQUUsS0FBSyxFQUFFLEdBQUc7TUFBRSxNQUFNLEVBQUUsd0RBQVU7TUFBRSxRQUFRLEVBQUUsSUFBSTtNQUFFLEtBQUssRUFBRSxJQUFJOzs7Ozs7O2tDQW1DaEYsTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztTQTNLQSxPQUFPLEVBQUUsa0JBQWtCLEVBQUUsS0FBSyxLQUFLLHVEQUFPOztPQVFoRCxNQUFNOztHQUVWLEdBQUcsRUFBRSxtQkFBbUI7R0FDeEIsS0FBSyxFQUFFLE9BQU87R0FDZCxLQUFLLEVBQUUsb0JBQW9COzs7O0tBSXpCLEtBQUssR0FBRyxJQUFJO0tBQ1osT0FBTyxHQUFHLEtBQUs7S0FFZixhQUFhLEdBQUcsQ0FBQztLQUNqQixNQUFNLEdBQUcsSUFBSTtLQUNiLGFBQWEsR0FBRyxDQUFDOztDQUVyQixzREFBTztFQUNOLGdCQUFnQjtRQUVWLGtCQUFrQixDQUFDLGlCQUFpQjs7O09BR3JDLGdCQUFnQjtrQkFDckIsYUFBYSxHQUFHLE1BQU0sQ0FBQyxnQkFBZ0IsQ0FBQyxRQUFRLENBQUMsZUFBZSxFQUFFLGdCQUFnQixDQUFDLGtCQUFrQjtFQUVyRyxhQUFhLEdBQUcsTUFBTSxDQUFDLENBQUMsQ0FBQyxPQUFPLENBQUMsS0FBSyxHQUFHLENBQUMsR0FBRyxJQUFJLENBQUMsRUFBRTtrQkFFcEQsTUFBTSxDQUFDLEtBQUssQ0FBQyxlQUFlLE1BQU0sYUFBYSxJQUFJLGFBQWE7a0JBQ2hFLE1BQU0sQ0FBQyxLQUFLLENBQUMsZ0JBQWdCLEdBQUcsQ0FBQzs7O09BRzVCLGNBQWMsR0FBSSxXQUFXO1FBQzVCLFFBQVEsR0FBRyxDQUFDLEdBQUksV0FBVyxHQUFHLG9EQUFJO1FBQ2xDLE1BQU0sR0FBRyxhQUFhLEdBQUcsUUFBUTtrQkFDdkMsTUFBTSxDQUFDLEtBQUssQ0FBQyxnQkFBZ0IsR0FBRyxNQUFNOzs7T0FHakMsV0FBVztrQkFDaEIsS0FBSyxHQUFHLFdBQVc7O0lBQ2xCLFdBQVcsSUFBSSxJQUFJO0lBRW5CLGNBQWMsQ0FBQyxXQUFXOztRQUV0QixXQUFXLElBQUksQ0FBQztLQUNuQixXQUFXO0tBQ1gsVUFBVTs7O0dBRVQsSUFBSTs7OztPQUdGLFVBQVU7UUFDVCxrQkFBa0IsQ0FBQyxRQUFRO0dBQ2hDLGFBQWE7O0tBRVosS0FBSyxFQUFFLFVBQVU7S0FDakIsSUFBSSxFQUFFLGtDQUFrQztLQUN4QyxFQUFFLEVBQUUsQ0FBQzs7Ozs7RUFLUCxLQUFLLENBQUMsSUFBSTtFQUVWLE9BQU8sQ0FBQyxPQUFPO0VBRWYsT0FBTyxDQUFDLEdBQUcsQ0FBQyxZQUFZOzs7T0FHbkIsV0FBVztFQUNoQixhQUFhLENBQUMsS0FBSztFQUVuQixXQUFXLEdBQUcsb0RBQUk7a0JBQ2xCLEtBQUssR0FBRyxJQUFJO2tCQUNaLE1BQU0sQ0FBQyxLQUFLLENBQUMsZ0JBQWdCLEdBQUcsQ0FBQzs7O09BRzVCLGFBQWE7a0JBQ2xCLE9BQU8sSUFBSSxPQUFPOztRQUVaLEtBQUssQ0FBQyxJQUFJO0dBQ2YsSUFBSSxFQUFFLE9BQU8sR0FBRyxrQkFBa0IsR0FBRyxtQkFBbUI7R0FDeEQsUUFBUSxFQUFFLEtBQUs7Ozs7Ozs7Ozs7Ozs7OztHQXlFRixNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBL0pyQixDQUFDLE1BQU0sT0FBTztJQUNiLG9EQUFJLENBQUMsR0FBRyxDQUFDLEtBQUs7O0lBRWQsb0RBQUksQ0FBQyxHQUFHLENBQUMsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ2pCbkI7QUFBQTtBQUFBO0FBQUE7QUFBaUQ7O0FBRWpEO0FBQ0E7QUFDQTs7QUFFTyxhQUFhLDZEQUFROztBQUU1QjtBQUNBLFFBQVEsaUJBQWlCLEdBQUcsNkRBQVE7O0FBRXBDLHFCQUFxQiw0REFBTztBQUM1QjtBQUNBLGVBQWUsNERBQU87QUFDdEIsaUJBQWlCLDREQUFPO0FBQ3hCLGlCQUFpQiw0REFBTzs7QUFFeEI7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVPLGtDIiwiZmlsZSI6IjZjNTY0NWFjOWM1ZDRkOTFhMTNhL2FwcC5hcHAuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5jb21hdGUg4oCSIHtkZXZNb2RlID8gJGVsYXBzZWRUaW1lLm1pbnV0ZXMgOiAkZWxhcHNlZFRpbWUuaG91cnN9OntkZXZNb2RlID8gJGVsYXBzZWRUaW1lLnNlY29uZHMgOiAkZWxhcHNlZFRpbWUubWludXRlc308L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZhZGUsIGZseSwgc2NhbGUgfSBmcm9tICdzdmVsdGUvdHJhbnNpdGlvbic7XG5cdGltcG9ydCB7IGVsYXN0aWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgUGx1Z2lucyB9IGZyb20gJ0BjYXBhY2l0b3IvY29yZSc7XG5cdGltcG9ydCB7IEJ1dHRvbiwgSWNvbiwgQXVkaW9QbGF5ZXIgfSBmcm9tICcuLi9jb21wb25lbnRzJztcblx0aW1wb3J0IHsgdGltZSwgZWxhcHNlZFRpbWUgfSBmcm9tICcuLi9zdG9yZS90aW1lci5qcyc7XG5cblx0Y29uc3QgeyBIYXB0aWNzLCBMb2NhbE5vdGlmaWNhdGlvbnMsIFRvYXN0IH0gPSBQbHVnaW5zO1xuXG5cdCQ6IGlmIChkZXZNb2RlKSB7XG5cdFx0dGltZS5zZXQoMTAwMDApO1xuXHR9IGVsc2Uge1xuXHRcdHRpbWUuc2V0KDI4ODAwMDAwKTtcblx0fVxuXG5cdGNvbnN0IHNvdW5kcyA9IFtcblx0XHR7XG5cdFx0XHRzcmM6ICcvYXVkaW8vc291bmQxLm1wMycsXG5cdFx0XHR0aXRsZTogJ0FsYW5lJyxcblx0XHRcdG1ha2VyOiAnUm9iaW4gU2NodWx6ICYgV2VzJ1xuXHRcdH1cblx0XVxuXG5cdGxldCB0aW1lciA9IG51bGw7XG5cdGxldCBkZXZNb2RlID0gZmFsc2U7XG5cblx0bGV0IHByb2dyZXNzV2lkdGggPSAwO1xuXHRsZXQgY2lyY2xlID0gbnVsbDtcblx0bGV0IGNpcmN1bWZlcmVuY2UgPSAwO1xuXG5cdG9uTW91bnQoYXN5bmMoKSA9PiB7XG5cdFx0aW5pdFByb2dyZXNzUmluZygpO1xuXG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnJlcXVlc3RQZXJtaXNzaW9uKCk7XG5cdH0pO1xuXG5cdGNvbnN0IGluaXRQcm9ncmVzc1JpbmcgPSAoKSA9PiB7XG5cdFx0cHJvZ3Jlc3NXaWR0aCA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuZ2V0UHJvcGVydHlWYWx1ZSgnLS1wcm9ncmVzcy13aWR0aCcpO1xuXG5cdFx0Y2lyY3VtZmVyZW5jZSA9IGNpcmNsZS5yLmJhc2VWYWwudmFsdWUgKiAyICogTWF0aC5QSTtcblxuXHRcdGNpcmNsZS5zdHlsZS5zdHJva2VEYXNoYXJyYXkgPSBgJHtjaXJjdW1mZXJlbmNlfSAke2NpcmN1bWZlcmVuY2V9YDtcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IDA7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVQcm9ncmVzcyA9IChlbGFwc2VkVGltZSkgPT4ge1xuXHRcdGNvbnN0IHByb2dyZXNzID0gMSAtIChlbGFwc2VkVGltZSAvIHRpbWUpO1xuXHRcdGNvbnN0IG9mZnNldCA9IGNpcmN1bWZlcmVuY2UgKiBwcm9ncmVzcztcblx0XHRjaXJjbGUuc3R5bGUuc3Ryb2tlRGFzaG9mZnNldCA9IG9mZnNldDtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0YXJ0ID0gKCkgPT4ge1xuXHRcdHRpbWVyID0gc2V0SW50ZXJ2YWwoKCkgPT4ge1xuXHRcdFx0ZWxhcHNlZFRpbWUgLT0gMTAwMDtcblxuXHRcdFx0aGFuZGxlUHJvZ3Jlc3MoZWxhcHNlZFRpbWUpO1xuXG5cdFx0XHRpZiAoZWxhcHNlZFRpbWUgPD0gMCkge1xuXHRcdFx0XHRoYW5kbGVSZXNldCgpO1xuXHRcdFx0XHRoYW5kbGVTdG9wKCk7XG5cdFx0XHR9XG5cdFx0fSwgMTAwMCk7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVTdG9wID0gYXN5bmMoKSA9PiB7XG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnNjaGVkdWxlKHtcblx0XHRcdG5vdGlmaWNhdGlvbnM6IFtcblx0XHRcdCAge1xuXHRcdFx0XHR0aXRsZTogXCJXYWtlIHVwIVwiLFxuXHRcdFx0XHRib2R5OiBcIkEgbG92ZWx5IGRheSBpcyB3YWl0aW5nIGZvciB5b3UuXCIsXG5cdFx0XHRcdGlkOiAxLFxuXHRcdFx0ICB9XG5cdFx0XHRdXG5cdFx0fSk7XG5cblx0XHRhdWRpby5wbGF5KCk7XG5cblx0XHRIYXB0aWNzLnZpYnJhdGUoKTtcblxuXHRcdGNvbnNvbGUubG9nKCdwbGF5IHNvdW5kJyk7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVSZXNldCA9ICgpID0+IHtcblx0XHRjbGVhckludGVydmFsKHRpbWVyKTtcblxuXHRcdGVsYXBzZWRUaW1lID0gdGltZTtcblx0XHR0aW1lciA9IG51bGw7XG5cdFx0Y2lyY2xlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSAwO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlRGV2TW9kZSA9IGFzeW5jKCkgPT4ge1xuXHRcdGRldk1vZGUgPSAhZGV2TW9kZTtcblxuXHRcdGF3YWl0IFRvYXN0LnNob3coe1xuXHRcdFx0dGV4dDogZGV2TW9kZSA/ICdERVYgbW9kZSBlbmFibGVkJyA6ICdERVYgbW9kZSBkaXNhYmxlZCcsXG5cdFx0XHRwb3NpdGlvbjogJ3RvcCdcblx0XHR9KTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHQ8aGVhZGVyXG5cdFx0Y2xhc3M9XCJoZWFkZXJcIlxuXHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC01MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDk1MH19XG5cdD5cblx0XHQ8YVxuXHRcdFx0aHJlZj1cIi9cIlxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdD5cblx0XHRcdDxJY29uXG5cdFx0XHRcdHNyYz1cIi9pbmZvLnN2Z1wiXG5cdFx0XHRcdHc9XCI2XCJcblx0XHRcdD5cblx0XHRcdDwvSWNvbj5cblx0XHQ8L2E+XG5cblx0XHQ8aDEgY2xhc3M9XCJoZWFkZXJfX3RleHRcIj5cblx0XHRcdGNvbWF0ZVxuXHRcdDwvaDE+XG5cblx0XHQ8YnV0dG9uXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0XHRjbGFzczpoaWRkZW49eyEhdGltZXJ9XG5cdFx0XHRvbjpjbGljaz17aGFuZGxlRGV2TW9kZX1cblx0XHQ+XG5cdFx0XHR7I2lmICFkZXZNb2RlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jb2RlLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2Nsb2NrLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7L2lmfVxuXHRcdDwvYnV0dG9uPlxuXHQ8L2hlYWRlcj5cblxuXHQ8ZGl2PlxuXHRcdDxzcGFuXG5cdFx0XHRpbjpzY2FsZT17e29wYWNpdHk6IDAsIHN0YXJ0OiAwLjUsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAxMDAwfX1cblx0XHRcdGNsYXNzPVwidGltZVwiXG5cdFx0PlxuXHRcdFx0eyNpZiBkZXZNb2RlfVxuXHRcdFx0XHQ8c3BhblxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fc2Vjb25kc1wiXG5cdFx0XHRcdFx0aW46ZmFkZVxuXHRcdFx0XHQ+XG5cdFx0XHRcdFx0eyRlbGFwc2VkVGltZS5taW51dGVzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JGVsYXBzZWRUaW1lLnNlY29uZHN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PHNwYW4gaW46ZmFkZT5cblx0XHRcdFx0XHR7JGVsYXBzZWRUaW1lLmhvdXJzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JGVsYXBzZWRUaW1lLm1pbnV0ZXN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHsvaWZ9XG5cblx0XHRcdDxzdmcgY2xhc3M9XCJ0aW1lX19wcm9ncmVzc1wiPlxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kXCJcblx0XHRcdFx0XHRyPXsxMjUgLSAocHJvZ3Jlc3NXaWR0aCAvIDIpfVxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cblx0XHRcdFx0PGNpcmNsZVxuXHRcdFx0XHRcdGJpbmQ6dGhpcz17Y2lyY2xlfVxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtcmluZ1wiXG5cdFx0XHRcdFx0cj17MTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKX1cblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXHRcdFx0PC9zdmc+XG5cdFx0PC9zcGFuPlxuXG5cdFx0PGRpdiBjbGFzcz1cImF1ZGlvXCI+XG5cdFx0XHR7I2VhY2ggc291bmRzIGFzIHNvdW5kfVxuXHRcdFx0XHQ8QXVkaW9QbGF5ZXJcblx0XHRcdFx0XHR7Li4uc291bmR9XG5cdFx0XHRcdD5cblx0XHRcdFx0PC9BdWRpb1BsYXllcj5cblx0XHRcdHsvZWFjaH1cblxuXHRcdFx0PGJ1dHRvblxuXHRcdFx0XHRjbGFzcz1cImF1ZGlvX19idXR0b25cIlxuXHRcdFx0PlxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9hdWRpby5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9idXR0b24+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdHsjaWYgIXRpbWVyfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b24gb246Y2xpY2s9e2hhbmRsZVN0YXJ0fT5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlN0YXJ0IHNsZWVwIGN5Y2xlPC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3BsYXkuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTRcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7OmVsc2V9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvblxuXHRcdFx0XHRhbHRcblx0XHRcdFx0b246Y2xpY2s9e2hhbmRsZVJlc2V0fVxuXHRcdFx0PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+UmVzZXQ8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcmVzZXQuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvQnV0dG9uPlxuXHRcdDwvZGl2PlxuXHR7L2lmfVxuPC9tYWluPlxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXJnaW46IDAgYXV0bztcblx0XHRwYWRkaW5nOiAxNXB4IDIwcHggNTBweDtcblx0fVxuXG5cdC5oZWFkZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5oZWFkZXJfX2ljb24ge1xuXHRcdHdpZHRoOiAyNXB4O1xuXHRcdGhlaWdodDogMjVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1oaWdobGlnaHQtY29sb3IpO1xuXHR9XG5cblx0LmhlYWRlcl9fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAxNnB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdH1cblxuXHQuaGlkZGVuIHtcblx0XHRvcGFjaXR5OiAwO1xuXHRcdHZpc2liaWxpdHk6IGhpZGRlbjtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0fVxuXG5cdC50aW1lIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0d2lkdGg6IDI1MHB4O1xuXHRcdGhlaWdodDogMjUwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRmb250LXNpemU6IDYwcHg7XG5cdFx0dGV4dC1zaGFkb3c6IDAgMTVweCAzMHB4IHJnYmEoMCwgMCwgMCwgMC44KTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcyB7XG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRsZWZ0OiAwO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kLFxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlLXdpZHRoOiB2YXIoLS1wcm9ncmVzcy13aWR0aCk7XG5cdFx0ZmlsbDogdHJhbnNwYXJlbnQ7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yKTtcblxuXHRcdHRyYW5zaXRpb246IHN0cm9rZS1kYXNob2Zmc2V0IDAuM3MgZWFzZS1vdXQ7XG5cdFx0dHJhbnNmb3JtOiByb3RhdGUoLTkwZGVnKTtcblx0XHR0cmFuc2Zvcm0tb3JpZ2luOiBjZW50ZXI7XG5cdH1cblxuXHQudGltZV9fc2Vjb25kcyB7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuYXVkaW8ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cblx0LmF1ZGlvX19idXR0b24ge1xuXHRcdHdpZHRoOiAzMHB4O1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRtYXJnaW4tbGVmdDogMTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LnB1bHNlIHtcblx0XHRhbmltYXRpb246IGZsYXNoIDJzIGVhc2UtaW4gaW5maW5pdGU7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIGZsYXNoIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYxJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cdH1cbjwvc3R5bGU+IiwiaW1wb3J0IHsgd3JpdGFibGUsIGRlcml2ZWQgfSBmcm9tICdzdmVsdGUvc3RvcmUnO1xuXG5jb25zdCBsZWFkaW5nWmVybyA9ICh2YWx1ZSkgPT4ge1xuXHRyZXR1cm4gKCcwJyArIHZhbHVlKS5zbGljZSgtMik7XG59O1xuXG5leHBvcnQgY29uc3QgdGltZSA9IHdyaXRhYmxlKDI4ODAwMDAwKTtcblxuY29uc3QgY3JlYXRlU3RvcmUgPSAoKSA9PiB7XG5cdGNvbnN0IHsgc3Vic2NyaWJlLCBzZXQgfSA9IHdyaXRhYmxlKHRpbWUpO1xuXG5cdGNvbnN0IGVsYXBzZWRUaW1lID0gZGVyaXZlZCh0aW1lLCAkdGltZSA9PiAkdGltZSk7XG5cdGNvbnNvbGUubG9nKCRlbGFwc2VkVGltZSk7XG5cdGNvbnN0IGhvdXJzID0gZGVyaXZlZChlbGFwc2VkVGltZSwgJGVsYXBzZWRUaW1lID0+IGxlYWRpbmdaZXJvKE1hdGguZmxvb3IoKCRlbGFwc2VkVGltZSAvICgxMDAwICogNjAgKiA2MCkpICUgMjQgKSkpO1xuXHRjb25zdCBtaW51dGVzID0gZGVyaXZlZChlbGFwc2VkVGltZSwgJGVsYXBzZWRUaW1lID0+IGxlYWRpbmdaZXJvKE1hdGguZmxvb3IoKCRlbGFwc2VkVGltZSAvIDEwMDAgLyA2MCkgJSA2MCApKSk7XG5cdGNvbnN0IHNlY29uZHMgPSBkZXJpdmVkKGVsYXBzZWRUaW1lLCAkZWxhcHNlZFRpbWUgPT4gbGVhZGluZ1plcm8oTWF0aC5mbG9vcigoJGVsYXBzZWRUaW1lIC8gMTAwMCkgJSA2MCApKSk7XG5cblx0Ly8gY29uc3QgaGFuZGxlU3RhcnQgPSAoKSA9PiB7XG5cdC8vIFx0c2V0KG51bGwpO1xuXHQvLyB9XG5cblx0Ly8gY29uc3QgaGFuZGxlUmVzZXQgPSAoKSA9PiB7XG5cdC8vIFx0c2V0KG51bGwpO1xuXHQvLyB9XG5cblx0cmV0dXJuIHtcblx0XHRzdWJzY3JpYmUsXG5cdFx0c2V0LFxuXHRcdGhvdXJzLFxuXHRcdG1pbnV0ZXMsXG5cdFx0c2Vjb25kc1xuXHR9O1xufVxuXG5leHBvcnQgY29uc3QgZWxhcHNlZFRpbWUgPSBjcmVhdGVTdG9yZSgpOyJdLCJzb3VyY2VSb290IjoiIn0=