(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["app"],{

/***/ "./src/data/sounds.js":
/*!****************************!*\
  !*** ./src/data/sounds.js ***!
  \****************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = ([
	{
		src: '/audio/sound1.mp3',
		title: 'Alane',
		maker: 'Robin Schulz & Wes'
	},
	{
		src: '/audio/sound2.mp3',
		title: 'Heat Waves',
		maker: 'Glass Animals'
	},
	{
		src: '/audio/sound3.mp3',
		title: 'Fairytale Gone Bad',
		maker: 'Sunrise Avenue'
	},
]);

/***/ }),

/***/ "./src/hooks/progress.js":
/*!*******************************!*\
  !*** ./src/hooks/progress.js ***!
  \*******************************/
/*! exports provided: progress, progressBackground */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "progress", function() { return progress; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "progressBackground", function() { return progressBackground; });
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");


const progress = (node) => {
	let circumference = 0;

	const progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue('--progress-width');

	circumference = node.r.baseVal.value * 2 * Math.PI;

	node.style.strokeDasharray = `${circumference} ${circumference}`;
	node.style.strokeDashoffset = 0;

	node.setAttribute('r', 125 - (progressWidth / 2));

	return {
		update({ time, devMode }) {
			const progress = 1 - (time / _store_timer_js__WEBPACK_IMPORTED_MODULE_0__["elapsedTime"].time(devMode));
			const offset = circumference * progress;
			node.style.strokeDashoffset = offset;
		}
	};
}

const progressBackground = (node) => {
	const progressWidth = window.getComputedStyle(document.documentElement).getPropertyValue('--progress-width');

	node.setAttribute('r', 125 - (progressWidth / 2));
}

/***/ }),

/***/ "./src/routes/app.svelte":
/*!*******************************!*\
  !*** ./src/routes/app.svelte ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _capacitor_core__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @capacitor/core */ "./node_modules/@capacitor/core/dist/esm/index.js");
/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../components */ "./src/components/index.js");
/* harmony import */ var _store_timer_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../store/timer.js */ "./src/store/timer.js");
/* harmony import */ var _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../hooks/progress.js */ "./src/hooks/progress.js");
/* harmony import */ var _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../data/sounds.js */ "./src/data/sounds.js");
/* src/routes/app.svelte generated by Svelte v3.24.1 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];








const file = "src/routes/app.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-egeauz-style";
	style.textContent = ".root.svelte-egeauz{display:flex;flex-direction:column;justify-content:space-between;align-items:center;margin:0 auto;padding:15px 20px 50px}.header.svelte-egeauz{display:flex;align-items:center;width:100%}.header__icon.svelte-egeauz{width:25px;height:25px;display:flex;justify-content:center;align-items:center;color:var(--highlight-color)}.header__text.svelte-egeauz{font-size:16px;font-weight:200;margin:0 auto}.hidden.svelte-egeauz{opacity:0;visibility:hidden;pointer-events:none}.time.svelte-egeauz{position:relative;width:250px;height:250px;display:flex;justify-content:center;align-items:center;font-size:60px;text-shadow:0 15px 30px rgba(0, 0, 0, 0.8)}.time__progress.svelte-egeauz{position:absolute;top:0;left:0;width:100%;height:100%}.time__progress-background.svelte-egeauz,.time__progress-ring.svelte-egeauz{stroke-width:var(--progress-width);fill:transparent}.time__progress-background.svelte-egeauz{stroke:var(--alternate-color-faded)}.time__progress-ring.svelte-egeauz{stroke:var(--alternate-color);transition:stroke-dashoffset 0.3s ease-out;transform:rotate(-90deg);transform-origin:center}.time__seconds.svelte-egeauz{color:var(--silver-color-faded)}.audio.svelte-egeauz{display:flex;justify-content:center;align-items:center;margin-top:30px}.audio__button.svelte-egeauz{width:30px;height:30px;margin-left:15px;display:flex;justify-content:center;align-items:center;color:var(--silver-color)}.pulse.svelte-egeauz{animation:svelte-egeauz-flash 2s ease-in infinite}@keyframes svelte-egeauz-flash{0%{opacity:1}60%{opacity:1}61%{opacity:0}100%{opacity:0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXBwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiYXBwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5jb21hdGUg4oCSIHtkZXZNb2RlID8gJG1pbnV0ZXMgOiAkaG91cnN9OntkZXZNb2RlID8gJHNlY29uZHMgOiAkbWludXRlc308L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG5cdGltcG9ydCB7IGZhZGUsIGZseSwgc2NhbGUgfSBmcm9tICdzdmVsdGUvdHJhbnNpdGlvbic7XG5cdGltcG9ydCB7IGVsYXN0aWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcblx0aW1wb3J0IHsgUGx1Z2lucyB9IGZyb20gJ0BjYXBhY2l0b3IvY29yZSc7XG5cdGltcG9ydCB7IEJ1dHRvbiwgSWNvbiwgQXVkaW9QbGF5ZXIsIE1vZGFsIH0gZnJvbSAnLi4vY29tcG9uZW50cyc7XG5cdGltcG9ydCB7IGVsYXBzZWRUaW1lLCBob3VycywgbWludXRlcywgc2Vjb25kcyB9IGZyb20gJy4uL3N0b3JlL3RpbWVyLmpzJztcblx0aW1wb3J0IHsgcHJvZ3Jlc3MsIHByb2dyZXNzQmFja2dyb3VuZCB9IGZyb20gJy4uL2hvb2tzL3Byb2dyZXNzLmpzJztcblx0aW1wb3J0IHNvdW5kcyBmcm9tICcuLi9kYXRhL3NvdW5kcy5qcyc7XG5cblx0Y29uc3QgeyBIYXB0aWNzLCBMb2NhbE5vdGlmaWNhdGlvbnMsIFRvYXN0IH0gPSBQbHVnaW5zO1xuXG5cdGxldCB0aW1lciA9IG51bGw7XG5cdGxldCBkZXZNb2RlID0gZmFsc2U7XG5cdGxldCBzaG93TW9kYWwgPSBmYWxzZTtcblx0bGV0IGFjdGl2ZVNvdW5kID0gMDtcblxuXHQkOiBlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblxuXHRvbk1vdW50KGFzeW5jKCkgPT4ge1xuXHRcdGF3YWl0IExvY2FsTm90aWZpY2F0aW9ucy5yZXF1ZXN0UGVybWlzc2lvbigpO1xuXHR9KTtcblxuXHRjb25zdCBoYW5kbGVTdGFydCA9ICgpID0+IHtcblx0XHR0aW1lciA9IHNldEludGVydmFsKCgpID0+IHtcblx0XHRcdGVsYXBzZWRUaW1lLnVwZGF0ZSh0aW1lID0+IHRpbWUgLSAxMDAwKTtcblxuXHRcdFx0aWYgKCRlbGFwc2VkVGltZSA8PSAwKSB7XG5cdFx0XHRcdGhhbmRsZVJlc2V0KCk7XG5cdFx0XHRcdGhhbmRsZVN0b3AoKTtcblx0XHRcdH1cblx0XHR9LCAxMDAwKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVN0b3AgPSBhc3luYygpID0+IHtcblx0XHRhd2FpdCBMb2NhbE5vdGlmaWNhdGlvbnMuc2NoZWR1bGUoe1xuXHRcdFx0bm90aWZpY2F0aW9uczogW1xuXHRcdFx0ICB7XG5cdFx0XHRcdHRpdGxlOiBcIldha2UgdXAhXCIsXG5cdFx0XHRcdGJvZHk6IFwiQSBsb3ZlbHkgZGF5IGlzIHdhaXRpbmcgZm9yIHlvdS5cIixcblx0XHRcdFx0aWQ6IDEsXG5cdFx0XHQgIH1cblx0XHRcdF1cblx0XHR9KTtcblxuXHRcdEF1ZGlvUGxheWVyLnBsYXkoYWN0aXZlU291bmQpO1xuXG5cdFx0SGFwdGljcy52aWJyYXRlKCk7XG5cblx0XHRjb25zb2xlLmxvZygncGxheSBzb3VuZCcpO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlUmVzZXQgPSAoKSA9PiB7XG5cdFx0Y2xlYXJJbnRlcnZhbCh0aW1lcik7XG5cblx0XHRlbGFwc2VkVGltZS5yZXNldChkZXZNb2RlKTtcblx0XHR0aW1lciA9IG51bGw7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVEZXZNb2RlID0gYXN5bmMoKSA9PiB7XG5cdFx0ZGV2TW9kZSA9ICFkZXZNb2RlO1xuXG5cdFx0YXdhaXQgVG9hc3Quc2hvdyh7XG5cdFx0XHR0ZXh0OiBkZXZNb2RlID8gJ0RFViBtb2RlIGVuYWJsZWQnIDogJ0RFViBtb2RlIGRpc2FibGVkJyxcblx0XHRcdHBvc2l0aW9uOiAndG9wJ1xuXHRcdH0pO1xuXHR9XG48L3NjcmlwdD5cblxuPG1haW4gY2xhc3M9XCJyb290XCI+XG5cdDxoZWFkZXJcblx0XHRjbGFzcz1cImhlYWRlclwiXG5cdFx0aW46Zmx5PXt7b3BhY2l0eTogMCwgeTogLTUwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogOTUwfX1cblx0PlxuXHRcdDxhXG5cdFx0XHRocmVmPVwiL1wiXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0PlxuXHRcdFx0PEljb25cblx0XHRcdFx0c3JjPVwiL2luZm8uc3ZnXCJcblx0XHRcdFx0dz1cIjZcIlxuXHRcdFx0PlxuXHRcdFx0PC9JY29uPlxuXHRcdDwvYT5cblxuXHRcdDxoMSBjbGFzcz1cImhlYWRlcl9fdGV4dFwiPlxuXHRcdFx0Y29tYXRlXG5cdFx0PC9oMT5cblxuXHRcdDxidXR0b25cblx0XHRcdGNsYXNzPVwiaGVhZGVyX19pY29uXCJcblx0XHRcdGNsYXNzOmhpZGRlbj17ISF0aW1lcn1cblx0XHRcdG9uOmNsaWNrPXtoYW5kbGVEZXZNb2RlfVxuXHRcdD5cblx0XHRcdHsjaWYgIWRldk1vZGV9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2NvZGUuc3ZnXCJcblx0XHRcdFx0XHR3PVwiMThcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvY2xvY2suc3ZnXCJcblx0XHRcdFx0XHR3PVwiMThcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdHsvaWZ9XG5cdFx0PC9idXR0b24+XG5cdDwvaGVhZGVyPlxuXG5cdDxkaXY+XG5cdFx0PHNwYW5cblx0XHRcdGluOnNjYWxlPXt7b3BhY2l0eTogMCwgc3RhcnQ6IDAuNSwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDEwMDB9fVxuXHRcdFx0Y2xhc3M9XCJ0aW1lXCJcblx0XHQ+XG5cdFx0XHR7I2lmIGRldk1vZGV9XG5cdFx0XHRcdDxzcGFuXG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19zZWNvbmRzXCJcblx0XHRcdFx0XHRpbjpmYWRlXG5cdFx0XHRcdD5cblx0XHRcdFx0XHR7JG1pbnV0ZXN9PHNwYW4gY2xhc3M6cHVsc2U9e3RpbWVyfT46PC9zcGFuPnskc2Vjb25kc31cblx0XHRcdFx0PC9zcGFuPlxuXHRcdFx0ezplbHNlfVxuXHRcdFx0XHQ8c3BhbiBpbjpmYWRlPlxuXHRcdFx0XHRcdHskaG91cnN9PHNwYW4gY2xhc3M6cHVsc2U9e3RpbWVyfT46PC9zcGFuPnskbWludXRlc31cblx0XHRcdFx0PC9zcGFuPlxuXHRcdFx0ey9pZn1cblxuXHRcdFx0PHN2ZyBjbGFzcz1cInRpbWVfX3Byb2dyZXNzXCI+XG5cdFx0XHRcdDxjaXJjbGVcblx0XHRcdFx0XHR1c2U6cHJvZ3Jlc3NCYWNrZ3JvdW5kXG5cdFx0XHRcdFx0Y2xhc3M9XCJ0aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kXCJcblx0XHRcdFx0XHRyPVwiMTI1XCJcblx0XHRcdFx0XHRjeD1cIjEyNVwiXG5cdFx0XHRcdFx0Y3k9XCIxMjVcIlxuXHRcdFx0XHQvPlxuXG5cdFx0XHRcdDxjaXJjbGVcblx0XHRcdFx0XHR1c2U6cHJvZ3Jlc3M9e3tcblx0XHRcdFx0XHRcdHRpbWU6ICRlbGFwc2VkVGltZSxcblx0XHRcdFx0XHRcdGRldk1vZGVcblx0XHRcdFx0XHR9fVxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtcmluZ1wiXG5cdFx0XHRcdFx0cj1cIjEyNVwiXG5cdFx0XHRcdFx0Y3g9XCIxMjVcIlxuXHRcdFx0XHRcdGN5PVwiMTI1XCJcblx0XHRcdFx0Lz5cblx0XHRcdDwvc3ZnPlxuXHRcdDwvc3Bhbj5cblxuXHRcdDxkaXYgY2xhc3M9XCJhdWRpb1wiPlxuXHRcdFx0PEF1ZGlvUGxheWVyXG5cdFx0XHRcdHsuLi5zb3VuZHNbYWN0aXZlU291bmRdfVxuXHRcdFx0PlxuXHRcdFx0PC9BdWRpb1BsYXllcj5cblxuXHRcdFx0PGJ1dHRvblxuXHRcdFx0XHRjbGFzcz1cImF1ZGlvX19idXR0b25cIlxuXHRcdFx0XHRvbjpjbGljaz17KCkgPT4gc2hvd01vZGFsID0gdHJ1ZX1cblx0XHRcdD5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvYXVkaW8uc3ZnXCJcblx0XHRcdFx0XHR3PVwiMTZcIlxuXHRcdFx0XHQ+XG5cdFx0XHRcdDwvSWNvbj5cblx0XHRcdDwvYnV0dG9uPlxuXHRcdDwvZGl2PlxuXHQ8L2Rpdj5cblxuXHR7I2lmICF0aW1lcn1cblx0XHQ8ZGl2IGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMjAwfX0+XG5cdFx0XHQ8QnV0dG9uIG9uOmNsaWNrPXtoYW5kbGVTdGFydH0+XG5cdFx0XHRcdDxzcGFuIGNsYXNzPVwidS1pY29uLXNwYWNpbmdcIj5TdGFydCBzbGVlcCBjeWNsZTwvc3Bhbj5cblxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9wbGF5LnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE0XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L0J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0ezplbHNlfVxuXHRcdDxkaXYgaW46Zmx5PXt7b3BhY2l0eTogMCwgeTogMzAsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAyMDB9fT5cblx0XHRcdDxCdXR0b25cblx0XHRcdFx0YWx0XG5cdFx0XHRcdG9uOmNsaWNrPXtoYW5kbGVSZXNldH1cblx0XHRcdD5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJ1LWljb24tc3BhY2luZ1wiPlJlc2V0PC9zcGFuPlxuXG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL3Jlc2V0LnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE2XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L0J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0ey9pZn1cbjwvbWFpbj5cblxueyNpZiBzaG93TW9kYWx9XG5cdDxNb2RhbFxuXHRcdHRpdGxlPVwiUGljayBhIHNvbmdcIlxuXHRcdG9uOmNsb3NlPVwieygpID0+IHNob3dNb2RhbCA9IGZhbHNlfVwiXG5cdD5cblx0XHR7I2VhY2ggc291bmRzIGFzIHNvdW5kLCBpfVxuXHRcdFx0PEF1ZGlvUGxheWVyXG5cdFx0XHRcdGludmVydGVkXG5cdFx0XHRcdHsuLi5zb3VuZH1cblx0XHRcdFx0b246Y2xpY2s9eygpID0+IHtcblx0XHRcdFx0XHRhY3RpdmVTb3VuZCA9IGk7XG5cdFx0XHRcdFx0c2hvd01vZGFsID0gZmFsc2U7XG5cdFx0XHRcdH19XG5cdFx0XHQ+XG5cdFx0XHQ8L0F1ZGlvUGxheWVyPlxuXHRcdHsvZWFjaH1cblx0PC9Nb2RhbD5cbnsvaWZ9XG5cbjxzdHlsZT5cblx0LnJvb3Qge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0ZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdG1hcmdpbjogMCBhdXRvO1xuXHRcdHBhZGRpbmc6IDE1cHggMjBweCA1MHB4O1xuXHR9XG5cblx0LmhlYWRlciB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHR9XG5cblx0LmhlYWRlcl9faWNvbiB7XG5cdFx0d2lkdGg6IDI1cHg7XG5cdFx0aGVpZ2h0OiAyNXB4O1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0Y29sb3I6IHZhcigtLWhpZ2hsaWdodC1jb2xvcik7XG5cdH1cblxuXHQuaGVhZGVyX190ZXh0IHtcblx0XHRmb250LXNpemU6IDE2cHg7XG5cdFx0Zm9udC13ZWlnaHQ6IDIwMDtcblx0XHRtYXJnaW46IDAgYXV0bztcblx0fVxuXG5cdC5oaWRkZW4ge1xuXHRcdG9wYWNpdHk6IDA7XG5cdFx0dmlzaWJpbGl0eTogaGlkZGVuO1xuXHRcdHBvaW50ZXItZXZlbnRzOiBub25lO1xuXHR9XG5cblx0LnRpbWUge1xuXHRcdHBvc2l0aW9uOiByZWxhdGl2ZTtcblx0XHR3aWR0aDogMjUwcHg7XG5cdFx0aGVpZ2h0OiAyNTBweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGZvbnQtc2l6ZTogNjBweDtcblx0XHR0ZXh0LXNoYWRvdzogMCAxNXB4IDMwcHggcmdiYSgwLCAwLCAwLCAwLjgpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzIHtcblx0XHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdFx0dG9wOiAwO1xuXHRcdGxlZnQ6IDA7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdFx0aGVpZ2h0OiAxMDAlO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLWJhY2tncm91bmQsXG5cdC50aW1lX19wcm9ncmVzcy1yaW5nIHtcblx0XHRzdHJva2Utd2lkdGg6IHZhcigtLXByb2dyZXNzLXdpZHRoKTtcblx0XHRmaWxsOiB0cmFuc3BhcmVudDtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kIHtcblx0XHRzdHJva2U6IHZhcigtLWFsdGVybmF0ZS1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3IpO1xuXG5cdFx0dHJhbnNpdGlvbjogc3Ryb2tlLWRhc2hvZmZzZXQgMC4zcyBlYXNlLW91dDtcblx0XHR0cmFuc2Zvcm06IHJvdGF0ZSgtOTBkZWcpO1xuXHRcdHRyYW5zZm9ybS1vcmlnaW46IGNlbnRlcjtcblx0fVxuXG5cdC50aW1lX19zZWNvbmRzIHtcblx0XHRjb2xvcjogdmFyKC0tc2lsdmVyLWNvbG9yLWZhZGVkKTtcblx0fVxuXG5cdC5hdWRpbyB7XG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXHRcdG1hcmdpbi10b3A6IDMwcHg7XG5cdH1cblxuXHQuYXVkaW9fX2J1dHRvbiB7XG5cdFx0d2lkdGg6IDMwcHg7XG5cdFx0aGVpZ2h0OiAzMHB4O1xuXHRcdG1hcmdpbi1sZWZ0OiAxNXB4O1xuXG5cdFx0ZGlzcGxheTogZmxleDtcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRhbGlnbi1pdGVtczogY2VudGVyO1xuXG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvcik7XG5cdH1cblxuXHQucHVsc2Uge1xuXHRcdGFuaW1hdGlvbjogZmxhc2ggMnMgZWFzZS1pbiBpbmZpbml0ZTtcblx0fVxuXG5cdEBrZXlmcmFtZXMgZmxhc2gge1xuXHRcdDAlIHtcblx0XHRcdG9wYWNpdHk6IDE7XG5cdFx0fVxuXG5cdFx0NjAlIHtcblx0XHRcdG9wYWNpdHk6IDE7XG5cdFx0fVxuXG5cdFx0NjElIHtcblx0XHRcdG9wYWNpdHk6IDA7XG5cdFx0fVxuXG5cdFx0MTAwJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblx0fVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBK05DLEtBQUssY0FBQyxDQUFDLEFBQ04sT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxDQUN0QixlQUFlLENBQUUsYUFBYSxDQUM5QixXQUFXLENBQUUsTUFBTSxDQUVuQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxPQUFPLENBQUUsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLEFBQ3hCLENBQUMsQUFFRCxPQUFPLGNBQUMsQ0FBQyxBQUNSLE9BQU8sQ0FBRSxJQUFJLENBQ2IsV0FBVyxDQUFFLE1BQU0sQ0FDbkIsS0FBSyxDQUFFLElBQUksQUFDWixDQUFDLEFBRUQsYUFBYSxjQUFDLENBQUMsQUFDZCxLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBRVosT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxDQUVuQixLQUFLLENBQUUsSUFBSSxpQkFBaUIsQ0FBQyxBQUM5QixDQUFDLEFBRUQsYUFBYSxjQUFDLENBQUMsQUFDZCxTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxBQUNmLENBQUMsQUFFRCxPQUFPLGNBQUMsQ0FBQyxBQUNSLE9BQU8sQ0FBRSxDQUFDLENBQ1YsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsY0FBYyxDQUFFLElBQUksQUFDckIsQ0FBQyxBQUVELEtBQUssY0FBQyxDQUFDLEFBQ04sUUFBUSxDQUFFLFFBQVEsQ0FDbEIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsS0FBSyxDQUViLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQ0FFbkIsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQUFDNUMsQ0FBQyxBQUVELGVBQWUsY0FBQyxDQUFDLEFBQ2hCLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEdBQUcsQ0FBRSxDQUFDLENBQ04sSUFBSSxDQUFFLENBQUMsQ0FDUCxLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLEFBQ2IsQ0FBQyxBQUVELHdDQUEwQixDQUMxQixvQkFBb0IsY0FBQyxDQUFDLEFBQ3JCLFlBQVksQ0FBRSxJQUFJLGdCQUFnQixDQUFDLENBQ25DLElBQUksQ0FBRSxXQUFXLEFBQ2xCLENBQUMsQUFFRCwwQkFBMEIsY0FBQyxDQUFDLEFBQzNCLE1BQU0sQ0FBRSxJQUFJLHVCQUF1QixDQUFDLEFBQ3JDLENBQUMsQUFFRCxvQkFBb0IsY0FBQyxDQUFDLEFBQ3JCLE1BQU0sQ0FBRSxJQUFJLGlCQUFpQixDQUFDLENBRTlCLFVBQVUsQ0FBRSxpQkFBaUIsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUMzQyxTQUFTLENBQUUsT0FBTyxNQUFNLENBQUMsQ0FDekIsZ0JBQWdCLENBQUUsTUFBTSxBQUN6QixDQUFDLEFBRUQsY0FBYyxjQUFDLENBQUMsQUFDZixLQUFLLENBQUUsSUFBSSxvQkFBb0IsQ0FBQyxBQUNqQyxDQUFDLEFBRUQsTUFBTSxjQUFDLENBQUMsQUFDUCxPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBQ25CLFVBQVUsQ0FBRSxJQUFJLEFBQ2pCLENBQUMsQUFFRCxjQUFjLGNBQUMsQ0FBQyxBQUNmLEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQ0FDWixXQUFXLENBQUUsSUFBSSxDQUVqQixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLENBRW5CLEtBQUssQ0FBRSxJQUFJLGNBQWMsQ0FBQyxBQUMzQixDQUFDLEFBRUQsTUFBTSxjQUFDLENBQUMsQUFDUCxTQUFTLENBQUUsbUJBQUssQ0FBQyxFQUFFLENBQUMsT0FBTyxDQUFDLFFBQVEsQUFDckMsQ0FBQyxBQUVELFdBQVcsbUJBQU0sQ0FBQyxBQUNqQixFQUFFLEFBQUMsQ0FBQyxBQUNILE9BQU8sQ0FBRSxDQUFDLEFBQ1gsQ0FBQyxBQUVELEdBQUcsQUFBQyxDQUFDLEFBQ0osT0FBTyxDQUFFLENBQUMsQUFDWCxDQUFDLEFBRUQsR0FBRyxBQUFDLENBQUMsQUFDSixPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxJQUFJLEFBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxDQUFDLEFBQ1gsQ0FBQyxBQUNGLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[18] = list[i];
	child_ctx[20] = i;
	return child_ctx;
}

// (105:3) {:else}
function create_else_block_2(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/clock.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_2.name,
		type: "else",
		source: "(105:3) {:else}",
		ctx
	});

	return block;
}

// (99:3) {#if !devMode}
function create_if_block_3(ctx) {
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/code.svg", w: "18" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_3.name,
		type: "if",
		source: "(99:3) {#if !devMode}",
		ctx
	});

	return block;
}

// (127:3) {:else}
function create_else_block_1(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$hours*/ ctx[6]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[5]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", {});
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$hours*/ ctx[6]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[5]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 128, 13, 2446);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 127, 4, 2418);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$hours*/ 64) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$hours*/ ctx[6]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$minutes*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$minutes*/ ctx[5]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block_1.name,
		type: "else",
		source: "(127:3) {:else}",
		ctx
	});

	return block;
}

// (120:3) {#if devMode}
function create_if_block_2(ctx) {
	let span1;
	let t0;
	let span0;
	let t1;
	let t2;
	let span1_intro;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$minutes*/ ctx[5]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*$seconds*/ ctx[7]);
			this.h();
		},
		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$minutes*/ ctx[5]);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, /*$seconds*/ ctx[7]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 124, 15, 2346);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "time__seconds svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 120, 4, 2279);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t2);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$minutes*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*$minutes*/ ctx[5]);

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span0, "pulse", /*timer*/ ctx[0]);
			}

			if (dirty & /*$seconds*/ 128) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, /*$seconds*/ ctx[7]);
		},
		i: function intro(local) {
			if (!span1_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span1_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span1, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"], {});
					span1_intro.start();
				});
			}
		},
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(120:3) {#if devMode}",
		ctx
	});

	return block;
}

// (186:1) {:else}
function create_else_block(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				alt: true,
				$$slots: { default: [create_default_slot_4] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleReset*/ ctx[9]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 186, 2, 3407);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(186:1) {:else}",
		ctx
	});

	return block;
}

// (174:1) {#if !timer}
function create_if_block_1(ctx) {
	let div;
	let button;
	let div_intro;
	let current;

	button = new _components__WEBPACK_IMPORTED_MODULE_5__["Button"]({
			props: {
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", /*handleStart*/ ctx[8]);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 174, 2, 3136);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, div, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);

			if (!div_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					div_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(div, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: 30,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 200
					});

					div_intro.start();
				});
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(174:1) {#if !timer}",
		ctx
	});

	return block;
}

// (188:3) <Button     alt     on:click={handleReset}    >
function create_default_slot_4(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/reset.svg", w: "16" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Reset");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Reset");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 191, 4, 3545);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_4.name,
		type: "slot",
		source: "(188:3) <Button     alt     on:click={handleReset}    >",
		ctx
	});

	return block;
}

// (176:3) <Button on:click={handleStart}>
function create_default_slot_2(ctx) {
	let span;
	let t0;
	let t1;
	let icon;
	let current;

	icon = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/play.svg", w: "14" },
			$$inline: true
		});

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Start sleep cycle");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "Start sleep cycle");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "u-icon-spacing");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 176, 4, 3258);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const icon_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				icon_changes.$$scope = { dirty, ctx };
			}

			icon.$set(icon_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(176:3) <Button on:click={handleStart}>",
		ctx
	});

	return block;
}

// (204:0) {#if showModal}
function create_if_block(ctx) {
	let modal;
	let current;

	modal = new _components__WEBPACK_IMPORTED_MODULE_5__["Modal"]({
			props: {
				title: "Pick a song",
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	modal.$on("close", /*close_handler*/ ctx[13]);

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(modal.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(modal.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(modal, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const modal_changes = {};

			if (dirty & /*$$scope, activeSound, showModal*/ 2097164) {
				modal_changes.$$scope = { dirty, ctx };
			}

			modal.$set(modal_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(modal.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(modal.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(modal, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(204:0) {#if showModal}",
		ctx
	});

	return block;
}

// (209:2) {#each sounds as sound, i}
function create_each_block(ctx) {
	let audioplayer;
	let current;
	const audioplayer_spread_levels = [{ inverted: true }, /*sound*/ ctx[18]];

	function click_handler_1(...args) {
		return /*click_handler_1*/ ctx[12](/*i*/ ctx[20], ...args);
	}

	let audioplayer_props = {};

	for (let i = 0; i < audioplayer_spread_levels.length; i += 1) {
		audioplayer_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(audioplayer_props, audioplayer_spread_levels[i]);
	}

	audioplayer = new _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"]({ props: audioplayer_props, $$inline: true });
	audioplayer.$on("click", click_handler_1);

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(audioplayer.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(audioplayer.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(audioplayer, target, anchor);
			current = true;
		},
		p: function update(new_ctx, dirty) {
			ctx = new_ctx;

			const audioplayer_changes = (dirty & /*sounds*/ 0)
			? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(audioplayer_spread_levels, [audioplayer_spread_levels[0], Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_object"])(/*sound*/ ctx[18])])
			: {};

			if (dirty & /*$$scope*/ 2097152) {
				audioplayer_changes.$$scope = { dirty, ctx };
			}

			audioplayer.$set(audioplayer_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(audioplayer.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(audioplayer.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(audioplayer, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(209:2) {#each sounds as sound, i}",
		ctx
	});

	return block;
}

// (205:1) <Modal   title="Pick a song"   on:close="{() => showModal = false}"  >
function create_default_slot(ctx) {
	let each_1_anchor;
	let current;
	let each_value = _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	const block = {
		c: function create() {
			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			each_1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		l: function claim(nodes) {
			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(nodes);
			}

			each_1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		m: function mount(target, anchor) {
			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(target, anchor);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, each_1_anchor, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			if (dirty & /*sounds, activeSound, showModal*/ 12) {
				each_value = _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(each_1_anchor.parentNode, each_1_anchor);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(each_1_anchor);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(205:1) <Modal   title=\\\"Pick a song\\\"   on:close=\\\"{() => showModal = false}\\\"  >",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let main;
	let header;
	let a;
	let icon0;
	let t1;
	let h1;
	let t2;
	let t3;
	let button0;
	let current_block_type_index;
	let if_block0;
	let header_intro;
	let t4;
	let div1;
	let span;
	let t5;
	let svg;
	let circle0;
	let progressBackground_action;
	let circle1;
	let progress_action;
	let span_intro;
	let t6;
	let div0;
	let audioplayer;
	let t7;
	let button1;
	let icon1;
	let t8;
	let current_block_type_index_1;
	let if_block2;
	let t9;
	let if_block3_anchor;
	let current;
	let mounted;
	let dispose;

	document.title = title_value = "comate ‒ " + (/*devMode*/ ctx[1]
	? /*$minutes*/ ctx[5]
	: /*$hours*/ ctx[6]) + ":" + (/*devMode*/ ctx[1]
	? /*$seconds*/ ctx[7]
	: /*$minutes*/ ctx[5]);

	icon0 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/info.svg", w: "6" },
			$$inline: true
		});

	const if_block_creators = [create_if_block_3, create_else_block_2];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (!/*devMode*/ ctx[1]) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	function select_block_type_1(ctx, dirty) {
		if (/*devMode*/ ctx[1]) return create_if_block_2;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_1(ctx, -1);
	let if_block1 = current_block_type(ctx);
	const audioplayer_spread_levels = [_data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"][/*activeSound*/ ctx[3]]];
	let audioplayer_props = {};

	for (let i = 0; i < audioplayer_spread_levels.length; i += 1) {
		audioplayer_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(audioplayer_props, audioplayer_spread_levels[i]);
	}

	audioplayer = new _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"]({ props: audioplayer_props, $$inline: true });

	icon1 = new _components__WEBPACK_IMPORTED_MODULE_5__["Icon"]({
			props: { src: "/audio.svg", w: "16" },
			$$inline: true
		});

	const if_block_creators_1 = [create_if_block_1, create_else_block];
	const if_blocks_1 = [];

	function select_block_type_2(ctx, dirty) {
		if (!/*timer*/ ctx[0]) return 0;
		return 1;
	}

	current_block_type_index_1 = select_block_type_2(ctx, -1);
	if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);
	let if_block3 = /*showModal*/ ctx[2] && create_if_block(ctx);

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("header");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon0.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("comate");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("circle");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(audioplayer.$$.fragment);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon1.$$.fragment);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if_block2.c();
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block3) if_block3.c();
			if_block3_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1rk5ch9\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true });
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);
			header = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "HEADER", { class: true });
			var header_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(header);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "A", { href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon0.$$.fragment, a_nodes);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "comate");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(header_nodes);
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(header_nodes, "BUTTON", { class: true });
			var button0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button0);
			if_block0.l(button0_nodes);
			button0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			header_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			if_block1.l(span_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "svg", { class: true }, 1);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);
			circle0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			circle1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "circle", { class: true, r: true, cx: true, cy: true }, 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(circle1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(audioplayer.$$.fragment, div0_nodes);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon1.$$.fragment, button1_nodes);
			button1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(main_nodes);
			if_block2.l(main_nodes);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			if (if_block3) if_block3.l(nodes);
			if_block3_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "header__icon svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 78, 2, 1705);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "header__text svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 89, 2, 1813);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button0, "class", "header__icon svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button0, file, 93, 2, 1860);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(header, "class", "header svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(header, file, 74, 1, 1595);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "class", "time__progress-background svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "r", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle0, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle0, file, 133, 4, 2549);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "class", "time__progress-ring svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "r", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cx", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(circle1, "cy", "125");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(circle1, file, 141, 4, 2677);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "class", "time__progress svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 132, 3, 2516);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "time svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 115, 2, 2144);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button1, "class", "audio__button svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button1, file, 160, 3, 2950);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "audio svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 154, 2, 2858);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 114, 1, 2136);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(main, "class", "root svelte-egeauz");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 73, 0, 1574);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, header);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon0, a, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(header, button0);
			if_blocks[current_block_type_index].m(button0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, span);
			if_block1.m(span, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, circle1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(audioplayer, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon1, button1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(main, t8);
			if_blocks_1[current_block_type_index_1].m(main, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t9, anchor);
			if (if_block3) if_block3.m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, if_block3_anchor, anchor);
			current = true;

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button0, "click", /*handleDevMode*/ ctx[10], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["action_destroyer"])(progressBackground_action = _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progressBackground"].call(null, circle0)),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["action_destroyer"])(progress_action = _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progress"].call(null, circle1, {
						time: /*$elapsedTime*/ ctx[4],
						devMode: /*devMode*/ ctx[1]
					})),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button1, "click", /*click_handler*/ ctx[11], false, false, false)
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if ((!current || dirty & /*devMode, $minutes, $hours, $seconds*/ 226) && title_value !== (title_value = "comate ‒ " + (/*devMode*/ ctx[1]
			? /*$minutes*/ ctx[5]
			: /*$hours*/ ctx[6]) + ":" + (/*devMode*/ ctx[1]
			? /*$seconds*/ ctx[7]
			: /*$minutes*/ ctx[5]))) {
				document.title = title_value;
			}

			const icon0_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				icon0_changes.$$scope = { dirty, ctx };
			}

			icon0.$set(icon0_changes);
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index !== previous_block_index) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block0 = if_blocks[current_block_type_index];

				if (!if_block0) {
					if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block0.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
				if_block0.m(button0, null);
			}

			if (dirty & /*timer*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(button0, "hidden", !!/*timer*/ ctx[0]);
			}

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block1) {
				if_block1.p(ctx, dirty);
			} else {
				if_block1.d(1);
				if_block1 = current_block_type(ctx);

				if (if_block1) {
					if_block1.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					if_block1.m(span, t5);
				}
			}

			if (progress_action && Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(progress_action.update) && dirty & /*$elapsedTime, devMode*/ 18) progress_action.update.call(null, {
				time: /*$elapsedTime*/ ctx[4],
				devMode: /*devMode*/ ctx[1]
			});

			const audioplayer_changes = (dirty & /*sounds, activeSound*/ 8)
			? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(audioplayer_spread_levels, [Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_object"])(_data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"][/*activeSound*/ ctx[3]])])
			: {};

			if (dirty & /*$$scope*/ 2097152) {
				audioplayer_changes.$$scope = { dirty, ctx };
			}

			audioplayer.$set(audioplayer_changes);
			const icon1_changes = {};

			if (dirty & /*$$scope*/ 2097152) {
				icon1_changes.$$scope = { dirty, ctx };
			}

			icon1.$set(icon1_changes);
			let previous_block_index_1 = current_block_type_index_1;
			current_block_type_index_1 = select_block_type_2(ctx, dirty);

			if (current_block_type_index_1 === previous_block_index_1) {
				if_blocks_1[current_block_type_index_1].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks_1[previous_block_index_1], 1, 1, () => {
					if_blocks_1[previous_block_index_1] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block2 = if_blocks_1[current_block_type_index_1];

				if (!if_block2) {
					if_block2 = if_blocks_1[current_block_type_index_1] = if_block_creators_1[current_block_type_index_1](ctx);
					if_block2.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2, 1);
				if_block2.m(main, null);
			}

			if (/*showModal*/ ctx[2]) {
				if (if_block3) {
					if_block3.p(ctx, dirty);

					if (dirty & /*showModal*/ 4) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block3, 1);
					}
				} else {
					if_block3 = create_if_block(ctx);
					if_block3.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block3, 1);
					if_block3.m(if_block3_anchor.parentNode, if_block3_anchor);
				}
			} else if (if_block3) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block3, 1, 1, () => {
					if_block3 = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0);

			if (!header_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					header_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(header, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"], {
						opacity: 0,
						y: -50,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 950
					});

					header_intro.start();
				});
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1);

			if (!span_intro) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
					span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"], {
						opacity: 0,
						start: 0.5,
						easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
						duration: 1000,
						delay: 1000
					});

					span_intro.start();
				});
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(audioplayer.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block3);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(audioplayer.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block3);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(main);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon0);
			if_blocks[current_block_type_index].d();
			if_block1.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(audioplayer);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon1);
			if_blocks_1[current_block_type_index_1].d();
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t9);
			if (if_block3) if_block3.d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(if_block3_anchor);
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $elapsedTime;
	let $minutes;
	let $hours;
	let $seconds;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], "elapsedTime");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"], $$value => $$invalidate(4, $elapsedTime = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], "minutes");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"], $$value => $$invalidate(5, $minutes = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], "hours");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"], $$value => $$invalidate(6, $hours = $$value));
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], "seconds");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"], $$value => $$invalidate(7, $seconds = $$value));
	const { Haptics, LocalNotifications, Toast } = _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"];
	let timer = null;
	let devMode = false;
	let showModal = false;
	let activeSound = 0;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await LocalNotifications.requestPermission();
	});

	const handleStart = () => {
		$$invalidate(0, timer = setInterval(
			() => {
				_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].update(time => time - 1000);

				if ($elapsedTime <= 0) {
					handleReset();
					handleStop();
				}
			},
			1000
		));
	};

	const handleStop = async () => {
		await LocalNotifications.schedule({
			notifications: [
				{
					title: "Wake up!",
					body: "A lovely day is waiting for you.",
					id: 1
				}
			]
		});

		_components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"].play(activeSound);
		Haptics.vibrate();
		console.log("play sound");
	};

	const handleReset = () => {
		clearInterval(timer);
		_store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		$$invalidate(0, timer = null);
	};

	const handleDevMode = async () => {
		$$invalidate(1, devMode = !devMode);

		await Toast.show({
			text: devMode ? "DEV mode enabled" : "DEV mode disabled",
			position: "top"
		});
	};

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<App> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("App", $$slots, []);
	const click_handler = () => $$invalidate(2, showModal = true);

	const click_handler_1 = i => {
		$$invalidate(3, activeSound = i);
		$$invalidate(2, showModal = false);
	};

	const close_handler = () => $$invalidate(2, showModal = false);

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["fly"],
		scale: svelte_transition__WEBPACK_IMPORTED_MODULE_2__["scale"],
		elasticOut: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["elasticOut"],
		Plugins: _capacitor_core__WEBPACK_IMPORTED_MODULE_4__["Plugins"],
		Button: _components__WEBPACK_IMPORTED_MODULE_5__["Button"],
		Icon: _components__WEBPACK_IMPORTED_MODULE_5__["Icon"],
		AudioPlayer: _components__WEBPACK_IMPORTED_MODULE_5__["AudioPlayer"],
		Modal: _components__WEBPACK_IMPORTED_MODULE_5__["Modal"],
		elapsedTime: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"],
		hours: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["hours"],
		minutes: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["minutes"],
		seconds: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["seconds"],
		progress: _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progress"],
		progressBackground: _hooks_progress_js__WEBPACK_IMPORTED_MODULE_7__["progressBackground"],
		sounds: _data_sounds_js__WEBPACK_IMPORTED_MODULE_8__["default"],
		Haptics,
		LocalNotifications,
		Toast,
		timer,
		devMode,
		showModal,
		activeSound,
		handleStart,
		handleStop,
		handleReset,
		handleDevMode,
		$elapsedTime,
		$minutes,
		$hours,
		$seconds
	});

	$$self.$inject_state = $$props => {
		if ("timer" in $$props) $$invalidate(0, timer = $$props.timer);
		if ("devMode" in $$props) $$invalidate(1, devMode = $$props.devMode);
		if ("showModal" in $$props) $$invalidate(2, showModal = $$props.showModal);
		if ("activeSound" in $$props) $$invalidate(3, activeSound = $$props.activeSound);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*devMode*/ 2) {
			$: _store_timer_js__WEBPACK_IMPORTED_MODULE_6__["elapsedTime"].reset(devMode);
		}
	};

	return [
		timer,
		devMode,
		showModal,
		activeSound,
		$elapsedTime,
		$minutes,
		$hours,
		$seconds,
		handleStart,
		handleReset,
		handleDevMode,
		click_handler,
		click_handler_1,
		close_handler
	];
}

class App extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-egeauz-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (App);

/***/ }),

/***/ "./src/store/timer.js":
/*!****************************!*\
  !*** ./src/store/timer.js ***!
  \****************************/
/*! exports provided: elapsedTime, hours, minutes, seconds */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "elapsedTime", function() { return elapsedTime; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "hours", function() { return hours; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "minutes", function() { return minutes; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "seconds", function() { return seconds; });
/* harmony import */ var svelte_store__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/store */ "./node_modules/svelte/store/index.mjs");


const TIME = 28800000; // 8 hours in milliseconds
const DEV_TIME = 10000; // 10 seconds in milliseconds

const leadingZero = (value) => {
	return ('0' + value).slice(-2);
};

const createStore = () => {
	const { subscribe, set, update } = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["writable"])(TIME);

	const handleReset = (isDev) => {
		if (isDev) {
			set(DEV_TIME);
		} else {
			set(TIME)
		}
	}

	const getTime = (isDev) => {
		if (isDev) {
			return DEV_TIME;
		} else {
			return TIME;
		}
	}

	return {
		subscribe,
		update,
		reset: handleReset,
		time: getTime
	}
}

const elapsedTime = createStore();

const hours = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / (1000 * 60 * 60)) % 24)));
const minutes = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000 / 60) % 60 )));
const seconds = Object(svelte_store__WEBPACK_IMPORTED_MODULE_0__["derived"])(elapsedTime, $elapsedTime => leadingZero(Math.floor(($elapsedTime / 1000) % 60)));

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvZGF0YS9zb3VuZHMuanMiLCJ3ZWJwYWNrOi8vLy4vc3JjL2hvb2tzL3Byb2dyZXNzLmpzIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvYXBwLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvc3RvcmUvdGltZXIuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztBQUFBO0FBQWU7QUFDZjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRjtBQUNBO0FBQ0E7QUFDQTtBQUNBLEVBQUU7QUFDRixDOzs7Ozs7Ozs7Ozs7QUNoQkE7QUFBQTtBQUFBO0FBQUE7QUFBZ0Q7O0FBRXpDO0FBQ1A7O0FBRUE7O0FBRUE7O0FBRUEsaUNBQWlDLGNBQWMsR0FBRyxjQUFjO0FBQ2hFOztBQUVBOztBQUVBO0FBQ0EsVUFBVSxnQkFBZ0I7QUFDMUIsZ0NBQWdDLDJEQUFXO0FBQzNDO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRU87QUFDUDs7QUFFQTtBQUNBLEM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDdEJrQztBQUNvQjtBQUNWO0FBQ0Q7QUFDdUI7QUFDUTtBQUNMO0FBQzdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2dGQW9IbEMsR0FBTTs7O2tGQUFvQyxHQUFROzs7Ozs7bUdBQWxELEdBQU07Ozs7O3FHQUFvQyxHQUFROzs7Ozs7a0dBQXhCLEdBQUs7Ozs7Ozs7Ozs7OztrSEFBL0IsR0FBTTs7O21HQUFvQixHQUFLOzs7c0hBQVcsR0FBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tGQUpsRCxHQUFROzs7a0ZBQW9DLEdBQVE7Ozs7OztxR0FBcEQsR0FBUTs7Ozs7cUdBQW9DLEdBQVE7Ozs7OztrR0FBeEIsR0FBSzs7Ozs7Ozs7Ozs7OztzSEFBakMsR0FBUTs7O21HQUFvQixHQUFLOzs7dUhBQVcsR0FBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQ0FpRTVDLEdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQUhULE9BQU8sRUFBRSxDQUFDO01BQUUsQ0FBQyxFQUFFLEVBQUU7TUFBRSxNQUFNLEVBQUUsd0RBQVU7TUFBRSxRQUFRLEVBQUUsSUFBSTtNQUFFLEtBQUssRUFBRSxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7cUNBWDVELEdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQURoQixPQUFPLEVBQUUsQ0FBQztNQUFFLENBQUMsRUFBRSxFQUFFO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tFQXFDekUsR0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZOQUFMLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tCQUhKLHVEQUFNOzs7O2dDQUFYLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpQkFBQyx1REFBTTs7OzsrQkFBWCxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7O3dCQUFKLE1BQUk7Ozs7Ozs7Ozs7a0NBQUosTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzJEQS9NVSxHQUFPO2dCQUFHLEdBQVE7Y0FBRyxHQUFNLDBCQUFHLEdBQU87Z0JBQUcsR0FBUTtnQkFBRyxHQUFROzs7Ozs7Ozs7OzttQkFpR3BFLEdBQU87Ozs7Ozs7O2tCQXFCUixHQUFPOzs7Ozs7b0NBcUNQLHVEQUFNLGlCQUFDLEdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7OztpQkFpQm5CLEdBQUs7Ozs7OzsrQkE4QlAsR0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1R0E1R0ssR0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0R0FDWCxHQUFhOzs7TUErQ3BCLElBQUksbUJBQUUsR0FBWTtNQUNsQixPQUFPLGNBQVAsR0FBTzs7Ozs7Ozs7O3NJQS9JSyxHQUFPO2tCQUFHLEdBQVE7Z0JBQUcsR0FBTSwwQkFBRyxHQUFPO2tCQUFHLEdBQVE7a0JBQUcsR0FBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3R0E4RjFELEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lBZ0RsQixJQUFJLG1CQUFFLEdBQVk7SUFDbEIsT0FBTyxjQUFQLEdBQU87Ozs7cUxBWUwsdURBQU0saUJBQUMsR0FBVzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQStDckIsR0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQS9ISCxPQUFPLEVBQUUsQ0FBQztNQUFFLENBQUMsR0FBRyxFQUFFO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7O01Bd0MvRCxPQUFPLEVBQUUsQ0FBQztNQUFFLEtBQUssRUFBRSxHQUFHO01BQUUsTUFBTSxFQUFFLHdEQUFVO01BQUUsUUFBUSxFQUFFLElBQUk7TUFBRSxLQUFLLEVBQUUsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O1NBdEc1RSxPQUFPLEVBQUUsa0JBQWtCLEVBQUUsS0FBSyxLQUFLLHVEQUFPO0tBRWxELEtBQUssR0FBRyxJQUFJO0tBQ1osT0FBTyxHQUFHLEtBQUs7S0FDZixTQUFTLEdBQUcsS0FBSztLQUNqQixXQUFXLEdBQUcsQ0FBQzs7Q0FJbkIsc0RBQU87UUFDQSxrQkFBa0IsQ0FBQyxpQkFBaUI7OztPQUdyQyxXQUFXO2tCQUNoQixLQUFLLEdBQUcsV0FBVzs7SUFDbEIsMkRBQVcsQ0FBQyxNQUFNLENBQUMsSUFBSSxJQUFJLElBQUksR0FBRyxJQUFJOztRQUVsQyxZQUFZLElBQUksQ0FBQztLQUNwQixXQUFXO0tBQ1gsVUFBVTs7O0dBRVQsSUFBSTs7OztPQUdGLFVBQVU7UUFDVCxrQkFBa0IsQ0FBQyxRQUFRO0dBQ2hDLGFBQWE7O0tBRVosS0FBSyxFQUFFLFVBQVU7S0FDakIsSUFBSSxFQUFFLGtDQUFrQztLQUN4QyxFQUFFLEVBQUUsQ0FBQzs7Ozs7RUFLUCx1REFBVyxDQUFDLElBQUksQ0FBQyxXQUFXO0VBRTVCLE9BQU8sQ0FBQyxPQUFPO0VBRWYsT0FBTyxDQUFDLEdBQUcsQ0FBQyxZQUFZOzs7T0FHbkIsV0FBVztFQUNoQixhQUFhLENBQUMsS0FBSztFQUVuQiwyREFBVyxDQUFDLEtBQUssQ0FBQyxPQUFPO2tCQUN6QixLQUFLLEdBQUcsSUFBSTs7O09BR1AsYUFBYTtrQkFDbEIsT0FBTyxJQUFJLE9BQU87O1FBRVosS0FBSyxDQUFDLElBQUk7R0FDZixJQUFJLEVBQUUsT0FBTyxHQUFHLGtCQUFrQixHQUFHLG1CQUFtQjtHQUN4RCxRQUFRLEVBQUUsS0FBSzs7Ozs7Ozs7Ozs7OzZDQThGRSxTQUFTLEdBQUcsSUFBSTs7O2tCQW1EL0IsV0FBVyxHQUFHLENBQUM7a0JBQ2YsU0FBUyxHQUFHLEtBQUs7Ozs2Q0FSSCxTQUFTLEdBQUcsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7R0F6TG5DLENBQUMsRUFBRSwyREFBVyxDQUFDLEtBQUssQ0FBQyxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDckI3QjtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBaUQ7O0FBRWpELHNCQUFzQjtBQUN0Qix1QkFBdUI7O0FBRXZCO0FBQ0E7QUFDQTs7QUFFQTtBQUNBLFFBQVEseUJBQXlCLEdBQUcsNkRBQVE7O0FBRTVDO0FBQ0E7QUFDQTtBQUNBLEdBQUc7QUFDSDtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0EsR0FBRztBQUNIO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFTzs7QUFFQSxjQUFjLDREQUFPO0FBQ3JCLGdCQUFnQiw0REFBTztBQUN2QixnQkFBZ0IsNERBQU8sbUYiLCJmaWxlIjoiNDlkOTU1NGE0MGIyOWE0YmRlMGUvYXBwLmFwcC5qcyIsInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBkZWZhdWx0IFtcblx0e1xuXHRcdHNyYzogJy9hdWRpby9zb3VuZDEubXAzJyxcblx0XHR0aXRsZTogJ0FsYW5lJyxcblx0XHRtYWtlcjogJ1JvYmluIFNjaHVseiAmIFdlcydcblx0fSxcblx0e1xuXHRcdHNyYzogJy9hdWRpby9zb3VuZDIubXAzJyxcblx0XHR0aXRsZTogJ0hlYXQgV2F2ZXMnLFxuXHRcdG1ha2VyOiAnR2xhc3MgQW5pbWFscydcblx0fSxcblx0e1xuXHRcdHNyYzogJy9hdWRpby9zb3VuZDMubXAzJyxcblx0XHR0aXRsZTogJ0ZhaXJ5dGFsZSBHb25lIEJhZCcsXG5cdFx0bWFrZXI6ICdTdW5yaXNlIEF2ZW51ZSdcblx0fSxcbl0iLCJpbXBvcnQgeyBlbGFwc2VkVGltZSB9IGZyb20gJy4uL3N0b3JlL3RpbWVyLmpzJztcblxuZXhwb3J0IGNvbnN0IHByb2dyZXNzID0gKG5vZGUpID0+IHtcblx0bGV0IGNpcmN1bWZlcmVuY2UgPSAwO1xuXG5cdGNvbnN0IHByb2dyZXNzV2lkdGggPSB3aW5kb3cuZ2V0Q29tcHV0ZWRTdHlsZShkb2N1bWVudC5kb2N1bWVudEVsZW1lbnQpLmdldFByb3BlcnR5VmFsdWUoJy0tcHJvZ3Jlc3Mtd2lkdGgnKTtcblxuXHRjaXJjdW1mZXJlbmNlID0gbm9kZS5yLmJhc2VWYWwudmFsdWUgKiAyICogTWF0aC5QSTtcblxuXHRub2RlLnN0eWxlLnN0cm9rZURhc2hhcnJheSA9IGAke2NpcmN1bWZlcmVuY2V9ICR7Y2lyY3VtZmVyZW5jZX1gO1xuXHRub2RlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSAwO1xuXG5cdG5vZGUuc2V0QXR0cmlidXRlKCdyJywgMTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKSk7XG5cblx0cmV0dXJuIHtcblx0XHR1cGRhdGUoeyB0aW1lLCBkZXZNb2RlIH0pIHtcblx0XHRcdGNvbnN0IHByb2dyZXNzID0gMSAtICh0aW1lIC8gZWxhcHNlZFRpbWUudGltZShkZXZNb2RlKSk7XG5cdFx0XHRjb25zdCBvZmZzZXQgPSBjaXJjdW1mZXJlbmNlICogcHJvZ3Jlc3M7XG5cdFx0XHRub2RlLnN0eWxlLnN0cm9rZURhc2hvZmZzZXQgPSBvZmZzZXQ7XG5cdFx0fVxuXHR9O1xufVxuXG5leHBvcnQgY29uc3QgcHJvZ3Jlc3NCYWNrZ3JvdW5kID0gKG5vZGUpID0+IHtcblx0Y29uc3QgcHJvZ3Jlc3NXaWR0aCA9IHdpbmRvdy5nZXRDb21wdXRlZFN0eWxlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuZ2V0UHJvcGVydHlWYWx1ZSgnLS1wcm9ncmVzcy13aWR0aCcpO1xuXG5cdG5vZGUuc2V0QXR0cmlidXRlKCdyJywgMTI1IC0gKHByb2dyZXNzV2lkdGggLyAyKSk7XG59IiwiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Y29tYXRlIOKAkiB7ZGV2TW9kZSA/ICRtaW51dGVzIDogJGhvdXJzfTp7ZGV2TW9kZSA/ICRzZWNvbmRzIDogJG1pbnV0ZXN9PC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tICdzdmVsdGUnO1xuXHRpbXBvcnQgeyBmYWRlLCBmbHksIHNjYWxlIH0gZnJvbSAnc3ZlbHRlL3RyYW5zaXRpb24nO1xuXHRpbXBvcnQgeyBlbGFzdGljT3V0IH0gZnJvbSAnc3ZlbHRlL2Vhc2luZyc7XG5cdGltcG9ydCB7IFBsdWdpbnMgfSBmcm9tICdAY2FwYWNpdG9yL2NvcmUnO1xuXHRpbXBvcnQgeyBCdXR0b24sIEljb24sIEF1ZGlvUGxheWVyLCBNb2RhbCB9IGZyb20gJy4uL2NvbXBvbmVudHMnO1xuXHRpbXBvcnQgeyBlbGFwc2VkVGltZSwgaG91cnMsIG1pbnV0ZXMsIHNlY29uZHMgfSBmcm9tICcuLi9zdG9yZS90aW1lci5qcyc7XG5cdGltcG9ydCB7IHByb2dyZXNzLCBwcm9ncmVzc0JhY2tncm91bmQgfSBmcm9tICcuLi9ob29rcy9wcm9ncmVzcy5qcyc7XG5cdGltcG9ydCBzb3VuZHMgZnJvbSAnLi4vZGF0YS9zb3VuZHMuanMnO1xuXG5cdGNvbnN0IHsgSGFwdGljcywgTG9jYWxOb3RpZmljYXRpb25zLCBUb2FzdCB9ID0gUGx1Z2lucztcblxuXHRsZXQgdGltZXIgPSBudWxsO1xuXHRsZXQgZGV2TW9kZSA9IGZhbHNlO1xuXHRsZXQgc2hvd01vZGFsID0gZmFsc2U7XG5cdGxldCBhY3RpdmVTb3VuZCA9IDA7XG5cblx0JDogZWxhcHNlZFRpbWUucmVzZXQoZGV2TW9kZSk7XG5cblx0b25Nb3VudChhc3luYygpID0+IHtcblx0XHRhd2FpdCBMb2NhbE5vdGlmaWNhdGlvbnMucmVxdWVzdFBlcm1pc3Npb24oKTtcblx0fSk7XG5cblx0Y29uc3QgaGFuZGxlU3RhcnQgPSAoKSA9PiB7XG5cdFx0dGltZXIgPSBzZXRJbnRlcnZhbCgoKSA9PiB7XG5cdFx0XHRlbGFwc2VkVGltZS51cGRhdGUodGltZSA9PiB0aW1lIC0gMTAwMCk7XG5cblx0XHRcdGlmICgkZWxhcHNlZFRpbWUgPD0gMCkge1xuXHRcdFx0XHRoYW5kbGVSZXNldCgpO1xuXHRcdFx0XHRoYW5kbGVTdG9wKCk7XG5cdFx0XHR9XG5cdFx0fSwgMTAwMCk7XG5cdH1cblxuXHRjb25zdCBoYW5kbGVTdG9wID0gYXN5bmMoKSA9PiB7XG5cdFx0YXdhaXQgTG9jYWxOb3RpZmljYXRpb25zLnNjaGVkdWxlKHtcblx0XHRcdG5vdGlmaWNhdGlvbnM6IFtcblx0XHRcdCAge1xuXHRcdFx0XHR0aXRsZTogXCJXYWtlIHVwIVwiLFxuXHRcdFx0XHRib2R5OiBcIkEgbG92ZWx5IGRheSBpcyB3YWl0aW5nIGZvciB5b3UuXCIsXG5cdFx0XHRcdGlkOiAxLFxuXHRcdFx0ICB9XG5cdFx0XHRdXG5cdFx0fSk7XG5cblx0XHRBdWRpb1BsYXllci5wbGF5KGFjdGl2ZVNvdW5kKTtcblxuXHRcdEhhcHRpY3MudmlicmF0ZSgpO1xuXG5cdFx0Y29uc29sZS5sb2coJ3BsYXkgc291bmQnKTtcblx0fVxuXG5cdGNvbnN0IGhhbmRsZVJlc2V0ID0gKCkgPT4ge1xuXHRcdGNsZWFySW50ZXJ2YWwodGltZXIpO1xuXG5cdFx0ZWxhcHNlZFRpbWUucmVzZXQoZGV2TW9kZSk7XG5cdFx0dGltZXIgPSBudWxsO1xuXHR9XG5cblx0Y29uc3QgaGFuZGxlRGV2TW9kZSA9IGFzeW5jKCkgPT4ge1xuXHRcdGRldk1vZGUgPSAhZGV2TW9kZTtcblxuXHRcdGF3YWl0IFRvYXN0LnNob3coe1xuXHRcdFx0dGV4dDogZGV2TW9kZSA/ICdERVYgbW9kZSBlbmFibGVkJyA6ICdERVYgbW9kZSBkaXNhYmxlZCcsXG5cdFx0XHRwb3NpdGlvbjogJ3RvcCdcblx0XHR9KTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxtYWluIGNsYXNzPVwicm9vdFwiPlxuXHQ8aGVhZGVyXG5cdFx0Y2xhc3M9XCJoZWFkZXJcIlxuXHRcdGluOmZseT17e29wYWNpdHk6IDAsIHk6IC01MCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDk1MH19XG5cdD5cblx0XHQ8YVxuXHRcdFx0aHJlZj1cIi9cIlxuXHRcdFx0Y2xhc3M9XCJoZWFkZXJfX2ljb25cIlxuXHRcdD5cblx0XHRcdDxJY29uXG5cdFx0XHRcdHNyYz1cIi9pbmZvLnN2Z1wiXG5cdFx0XHRcdHc9XCI2XCJcblx0XHRcdD5cblx0XHRcdDwvSWNvbj5cblx0XHQ8L2E+XG5cblx0XHQ8aDEgY2xhc3M9XCJoZWFkZXJfX3RleHRcIj5cblx0XHRcdGNvbWF0ZVxuXHRcdDwvaDE+XG5cblx0XHQ8YnV0dG9uXG5cdFx0XHRjbGFzcz1cImhlYWRlcl9faWNvblwiXG5cdFx0XHRjbGFzczpoaWRkZW49eyEhdGltZXJ9XG5cdFx0XHRvbjpjbGljaz17aGFuZGxlRGV2TW9kZX1cblx0XHQ+XG5cdFx0XHR7I2lmICFkZXZNb2RlfVxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9jb2RlLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7OmVsc2V9XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2Nsb2NrLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE4XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHR7L2lmfVxuXHRcdDwvYnV0dG9uPlxuXHQ8L2hlYWRlcj5cblxuXHQ8ZGl2PlxuXHRcdDxzcGFuXG5cdFx0XHRpbjpzY2FsZT17e29wYWNpdHk6IDAsIHN0YXJ0OiAwLjUsIGVhc2luZzogZWxhc3RpY091dCwgZHVyYXRpb246IDEwMDAsIGRlbGF5OiAxMDAwfX1cblx0XHRcdGNsYXNzPVwidGltZVwiXG5cdFx0PlxuXHRcdFx0eyNpZiBkZXZNb2RlfVxuXHRcdFx0XHQ8c3BhblxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fc2Vjb25kc1wiXG5cdFx0XHRcdFx0aW46ZmFkZVxuXHRcdFx0XHQ+XG5cdFx0XHRcdFx0eyRtaW51dGVzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JHNlY29uZHN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHs6ZWxzZX1cblx0XHRcdFx0PHNwYW4gaW46ZmFkZT5cblx0XHRcdFx0XHR7JGhvdXJzfTxzcGFuIGNsYXNzOnB1bHNlPXt0aW1lcn0+Ojwvc3Bhbj57JG1pbnV0ZXN9XG5cdFx0XHRcdDwvc3Bhbj5cblx0XHRcdHsvaWZ9XG5cblx0XHRcdDxzdmcgY2xhc3M9XCJ0aW1lX19wcm9ncmVzc1wiPlxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0dXNlOnByb2dyZXNzQmFja2dyb3VuZFxuXHRcdFx0XHRcdGNsYXNzPVwidGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZFwiXG5cdFx0XHRcdFx0cj1cIjEyNVwiXG5cdFx0XHRcdFx0Y3g9XCIxMjVcIlxuXHRcdFx0XHRcdGN5PVwiMTI1XCJcblx0XHRcdFx0Lz5cblxuXHRcdFx0XHQ8Y2lyY2xlXG5cdFx0XHRcdFx0dXNlOnByb2dyZXNzPXt7XG5cdFx0XHRcdFx0XHR0aW1lOiAkZWxhcHNlZFRpbWUsXG5cdFx0XHRcdFx0XHRkZXZNb2RlXG5cdFx0XHRcdFx0fX1cblx0XHRcdFx0XHRjbGFzcz1cInRpbWVfX3Byb2dyZXNzLXJpbmdcIlxuXHRcdFx0XHRcdHI9XCIxMjVcIlxuXHRcdFx0XHRcdGN4PVwiMTI1XCJcblx0XHRcdFx0XHRjeT1cIjEyNVwiXG5cdFx0XHRcdC8+XG5cdFx0XHQ8L3N2Zz5cblx0XHQ8L3NwYW4+XG5cblx0XHQ8ZGl2IGNsYXNzPVwiYXVkaW9cIj5cblx0XHRcdDxBdWRpb1BsYXllclxuXHRcdFx0XHR7Li4uc291bmRzW2FjdGl2ZVNvdW5kXX1cblx0XHRcdD5cblx0XHRcdDwvQXVkaW9QbGF5ZXI+XG5cblx0XHRcdDxidXR0b25cblx0XHRcdFx0Y2xhc3M9XCJhdWRpb19fYnV0dG9uXCJcblx0XHRcdFx0b246Y2xpY2s9eygpID0+IHNob3dNb2RhbCA9IHRydWV9XG5cdFx0XHQ+XG5cdFx0XHRcdDxJY29uXG5cdFx0XHRcdFx0c3JjPVwiL2F1ZGlvLnN2Z1wiXG5cdFx0XHRcdFx0dz1cIjE2XCJcblx0XHRcdFx0PlxuXHRcdFx0XHQ8L0ljb24+XG5cdFx0XHQ8L2J1dHRvbj5cblx0XHQ8L2Rpdj5cblx0PC9kaXY+XG5cblx0eyNpZiAhdGltZXJ9XG5cdFx0PGRpdiBpbjpmbHk9e3tvcGFjaXR5OiAwLCB5OiAzMCwgZWFzaW5nOiBlbGFzdGljT3V0LCBkdXJhdGlvbjogMTAwMCwgZGVsYXk6IDIwMH19PlxuXHRcdFx0PEJ1dHRvbiBvbjpjbGljaz17aGFuZGxlU3RhcnR9PlxuXHRcdFx0XHQ8c3BhbiBjbGFzcz1cInUtaWNvbi1zcGFjaW5nXCI+U3RhcnQgc2xlZXAgY3ljbGU8L3NwYW4+XG5cblx0XHRcdFx0PEljb25cblx0XHRcdFx0XHRzcmM9XCIvcGxheS5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNFwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9CdXR0b24+XG5cdFx0PC9kaXY+XG5cdHs6ZWxzZX1cblx0XHQ8ZGl2IGluOmZseT17e29wYWNpdHk6IDAsIHk6IDMwLCBlYXNpbmc6IGVsYXN0aWNPdXQsIGR1cmF0aW9uOiAxMDAwLCBkZWxheTogMjAwfX0+XG5cdFx0XHQ8QnV0dG9uXG5cdFx0XHRcdGFsdFxuXHRcdFx0XHRvbjpjbGljaz17aGFuZGxlUmVzZXR9XG5cdFx0XHQ+XG5cdFx0XHRcdDxzcGFuIGNsYXNzPVwidS1pY29uLXNwYWNpbmdcIj5SZXNldDwvc3Bhbj5cblxuXHRcdFx0XHQ8SWNvblxuXHRcdFx0XHRcdHNyYz1cIi9yZXNldC5zdmdcIlxuXHRcdFx0XHRcdHc9XCIxNlwiXG5cdFx0XHRcdD5cblx0XHRcdFx0PC9JY29uPlxuXHRcdFx0PC9CdXR0b24+XG5cdFx0PC9kaXY+XG5cdHsvaWZ9XG48L21haW4+XG5cbnsjaWYgc2hvd01vZGFsfVxuXHQ8TW9kYWxcblx0XHR0aXRsZT1cIlBpY2sgYSBzb25nXCJcblx0XHRvbjpjbG9zZT1cInsoKSA9PiBzaG93TW9kYWwgPSBmYWxzZX1cIlxuXHQ+XG5cdFx0eyNlYWNoIHNvdW5kcyBhcyBzb3VuZCwgaX1cblx0XHRcdDxBdWRpb1BsYXllclxuXHRcdFx0XHRpbnZlcnRlZFxuXHRcdFx0XHR7Li4uc291bmR9XG5cdFx0XHRcdG9uOmNsaWNrPXsoKSA9PiB7XG5cdFx0XHRcdFx0YWN0aXZlU291bmQgPSBpO1xuXHRcdFx0XHRcdHNob3dNb2RhbCA9IGZhbHNlO1xuXHRcdFx0XHR9fVxuXHRcdFx0PlxuXHRcdFx0PC9BdWRpb1BsYXllcj5cblx0XHR7L2VhY2h9XG5cdDwvTW9kYWw+XG57L2lmfVxuXG48c3R5bGU+XG5cdC5yb290IHtcblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdFx0anVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRtYXJnaW46IDAgYXV0bztcblx0XHRwYWRkaW5nOiAxNXB4IDIwcHggNTBweDtcblx0fVxuXG5cdC5oZWFkZXIge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdC5oZWFkZXJfX2ljb24ge1xuXHRcdHdpZHRoOiAyNXB4O1xuXHRcdGhlaWdodDogMjVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1oaWdobGlnaHQtY29sb3IpO1xuXHR9XG5cblx0LmhlYWRlcl9fdGV4dCB7XG5cdFx0Zm9udC1zaXplOiAxNnB4O1xuXHRcdGZvbnQtd2VpZ2h0OiAyMDA7XG5cdFx0bWFyZ2luOiAwIGF1dG87XG5cdH1cblxuXHQuaGlkZGVuIHtcblx0XHRvcGFjaXR5OiAwO1xuXHRcdHZpc2liaWxpdHk6IGhpZGRlbjtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0fVxuXG5cdC50aW1lIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0d2lkdGg6IDI1MHB4O1xuXHRcdGhlaWdodDogMjUwcHg7XG5cblx0XHRkaXNwbGF5OiBmbGV4O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG5cblx0XHRmb250LXNpemU6IDYwcHg7XG5cdFx0dGV4dC1zaGFkb3c6IDAgMTVweCAzMHB4IHJnYmEoMCwgMCwgMCwgMC44KTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcyB7XG5cdFx0cG9zaXRpb246IGFic29sdXRlO1xuXHRcdHRvcDogMDtcblx0XHRsZWZ0OiAwO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHRcdGhlaWdodDogMTAwJTtcblx0fVxuXG5cdC50aW1lX19wcm9ncmVzcy1iYWNrZ3JvdW5kLFxuXHQudGltZV9fcHJvZ3Jlc3MtcmluZyB7XG5cdFx0c3Ryb2tlLXdpZHRoOiB2YXIoLS1wcm9ncmVzcy13aWR0aCk7XG5cdFx0ZmlsbDogdHJhbnNwYXJlbnQ7XG5cdH1cblxuXHQudGltZV9fcHJvZ3Jlc3MtYmFja2dyb3VuZCB7XG5cdFx0c3Ryb2tlOiB2YXIoLS1hbHRlcm5hdGUtY29sb3ItZmFkZWQpO1xuXHR9XG5cblx0LnRpbWVfX3Byb2dyZXNzLXJpbmcge1xuXHRcdHN0cm9rZTogdmFyKC0tYWx0ZXJuYXRlLWNvbG9yKTtcblxuXHRcdHRyYW5zaXRpb246IHN0cm9rZS1kYXNob2Zmc2V0IDAuM3MgZWFzZS1vdXQ7XG5cdFx0dHJhbnNmb3JtOiByb3RhdGUoLTkwZGVnKTtcblx0XHR0cmFuc2Zvcm0tb3JpZ2luOiBjZW50ZXI7XG5cdH1cblxuXHQudGltZV9fc2Vjb25kcyB7XG5cdFx0Y29sb3I6IHZhcigtLXNpbHZlci1jb2xvci1mYWRlZCk7XG5cdH1cblxuXHQuYXVkaW8ge1xuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblx0XHRtYXJnaW4tdG9wOiAzMHB4O1xuXHR9XG5cblx0LmF1ZGlvX19idXR0b24ge1xuXHRcdHdpZHRoOiAzMHB4O1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRtYXJnaW4tbGVmdDogMTVweDtcblxuXHRcdGRpc3BsYXk6IGZsZXg7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0YWxpZ24taXRlbXM6IGNlbnRlcjtcblxuXHRcdGNvbG9yOiB2YXIoLS1zaWx2ZXItY29sb3IpO1xuXHR9XG5cblx0LnB1bHNlIHtcblx0XHRhbmltYXRpb246IGZsYXNoIDJzIGVhc2UtaW4gaW5maW5pdGU7XG5cdH1cblxuXHRAa2V5ZnJhbWVzIGZsYXNoIHtcblx0XHQwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYwJSB7XG5cdFx0XHRvcGFjaXR5OiAxO1xuXHRcdH1cblxuXHRcdDYxJSB7XG5cdFx0XHRvcGFjaXR5OiAwO1xuXHRcdH1cblxuXHRcdDEwMCUge1xuXHRcdFx0b3BhY2l0eTogMDtcblx0XHR9XG5cdH1cbjwvc3R5bGU+IiwiaW1wb3J0IHsgd3JpdGFibGUsIGRlcml2ZWQgfSBmcm9tICdzdmVsdGUvc3RvcmUnO1xuXG5jb25zdCBUSU1FID0gMjg4MDAwMDA7IC8vIDggaG91cnMgaW4gbWlsbGlzZWNvbmRzXG5jb25zdCBERVZfVElNRSA9IDEwMDAwOyAvLyAxMCBzZWNvbmRzIGluIG1pbGxpc2Vjb25kc1xuXG5jb25zdCBsZWFkaW5nWmVybyA9ICh2YWx1ZSkgPT4ge1xuXHRyZXR1cm4gKCcwJyArIHZhbHVlKS5zbGljZSgtMik7XG59O1xuXG5jb25zdCBjcmVhdGVTdG9yZSA9ICgpID0+IHtcblx0Y29uc3QgeyBzdWJzY3JpYmUsIHNldCwgdXBkYXRlIH0gPSB3cml0YWJsZShUSU1FKTtcblxuXHRjb25zdCBoYW5kbGVSZXNldCA9IChpc0RldikgPT4ge1xuXHRcdGlmIChpc0Rldikge1xuXHRcdFx0c2V0KERFVl9USU1FKTtcblx0XHR9IGVsc2Uge1xuXHRcdFx0c2V0KFRJTUUpXG5cdFx0fVxuXHR9XG5cblx0Y29uc3QgZ2V0VGltZSA9IChpc0RldikgPT4ge1xuXHRcdGlmIChpc0Rldikge1xuXHRcdFx0cmV0dXJuIERFVl9USU1FO1xuXHRcdH0gZWxzZSB7XG5cdFx0XHRyZXR1cm4gVElNRTtcblx0XHR9XG5cdH1cblxuXHRyZXR1cm4ge1xuXHRcdHN1YnNjcmliZSxcblx0XHR1cGRhdGUsXG5cdFx0cmVzZXQ6IGhhbmRsZVJlc2V0LFxuXHRcdHRpbWU6IGdldFRpbWVcblx0fVxufVxuXG5leHBvcnQgY29uc3QgZWxhcHNlZFRpbWUgPSBjcmVhdGVTdG9yZSgpO1xuXG5leHBvcnQgY29uc3QgaG91cnMgPSBkZXJpdmVkKGVsYXBzZWRUaW1lLCAkZWxhcHNlZFRpbWUgPT4gbGVhZGluZ1plcm8oTWF0aC5mbG9vcigoJGVsYXBzZWRUaW1lIC8gKDEwMDAgKiA2MCAqIDYwKSkgJSAyNCkpKTtcbmV4cG9ydCBjb25zdCBtaW51dGVzID0gZGVyaXZlZChlbGFwc2VkVGltZSwgJGVsYXBzZWRUaW1lID0+IGxlYWRpbmdaZXJvKE1hdGguZmxvb3IoKCRlbGFwc2VkVGltZSAvIDEwMDAgLyA2MCkgJSA2MCApKSk7XG5leHBvcnQgY29uc3Qgc2Vjb25kcyA9IGRlcml2ZWQoZWxhcHNlZFRpbWUsICRlbGFwc2VkVGltZSA9PiBsZWFkaW5nWmVybyhNYXRoLmZsb29yKCgkZWxhcHNlZFRpbWUgLyAxMDAwKSAlIDYwKSkpOyJdLCJzb3VyY2VSb290IjoiIn0=